import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SYSTEM_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'system-rank-reveal',
      name: 'RankRevealSequence',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Result-DNA', 'KRANK Bloom-Idee (Glow-Burst), Scramble-Konvergenz'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Rang-Enthüllung', 'Ergebnis-/Award-Momente'],
      performanceNotes: 'Scramble ist ein Text-Update pro Frame — günstig.',
      mobileNotes: 'Voll touch-tauglich (Auto-Sequenz).',
      reducedMotionNotes: 'Rang sofort sichtbar, keine Sequenz.',
      description: 'Mehrstufige Rang-Enthüllung: Scan-Grid baut auf, Buchstaben-Scramble konvergiert zum Rang-Namen, Glow-Burst zündet, Metrik-Zeilen staggern nach.',
      importPath: '@/motion-arsenal/effects/system/RankRevealSequence',
      usageJsx: '<RankRevealSequence rankName="FORGED" autoReplay />',
      props: [
        { key: 'rankName', label: 'Rank Text', type: 'text', default: 'FORGED', group: 'Content' },
        { key: 'color', label: 'Text Color', type: 'color', default: '#f0ece4', group: 'Colors' },
        { key: 'accentColor', label: 'Accent Color', type: 'color', default: '#C93030', group: 'Colors' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2.5, step: 0.1, group: 'Timing' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true, group: 'Timing' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./RankRevealSequence')),
  },
  {
    meta: {
      id: 'system-scan-complete-pulse',
      name: 'ScanCompletePulse',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash (Checkmark-Draw)', 'nicht-lineares Scan-Timing (Eigenbau)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Analyse-/Lade-Momente', 'NOX Forge NPC-Scan', 'Onboarding-Checks'],
      performanceNotes: 'Segment-Rendering + ein Puls — sehr günstig.',
      mobileNotes: 'Touch-tauglich, Auto-Replay.',
      reducedMotionNotes: '100% + Checkmark sofort.',
      description: 'Segmentierte Scan-Bar mit nicht-linearem Timing (sprintet, stockt bei 42%/78%, sprintet — wie echte Scans), Status-Zeile wechselt mit, bei 100% radialer Puls + Checkmark-Draw + Grid-Blitz.',
      importPath: '@/motion-arsenal/effects/system/ScanCompletePulse',
      usageJsx: '<ScanCompletePulse segments={14} autoReplay />',
      props: [
        { key: 'segments', label: 'Segments', type: 'range', default: 14, min: 6, max: 24, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScanCompletePulse')),
  },
  {
    meta: {
      id: 'system-terminal-boot-stream',
      name: 'TerminalBootStream',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK Filter-Chain (Flicker-Idee)', 'NOX Forge Agent-Terminal-DNA'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Agent-Interfaces', 'Boot-/Lade-Sequenzen', 'Dev-Tool-Branding'],
      performanceNotes: 'Text-Updates + eine Scanline — sehr günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Alle Zeilen sofort da, kein Tippen/Flicker.',
      description: 'Terminal bootet: Zeilen tippen sich mit variablem Tempo und Mikro-Stottern, farbige Status-Tags ([OK]/[WARN]), ASCII-Header, Scanline + dezentes CRT-Flicker, am Ende pulsierender Prompt.',
      importPath: '@/motion-arsenal/effects/system/TerminalBootStream',
      usageJsx: '<TerminalBootStream speed={1} flicker />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'flicker', label: 'Flicker', type: 'boolean', default: true },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TerminalBootStream')),
  },
  {
    meta: {
      id: 'system-progress-ring-charge',
      name: 'ProgressRingCharge',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Bounce bei 100%)', 'Bloom-Idee (Glow-Ring-Kopie)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Dashboards', 'Skill-/XP-Anzeigen', 'Lade-Zustände mit Charakter'],
      performanceNotes: 'conic-gradient + Blur-Kopie — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Ziel-Prozent sofort, kein Zählen.',
      description: 'Ring lädt via conic-gradient mit Glow-Ring-Kopie dahinter und leuchtendem Lauf-Kopf; die Zahl zählt mit outExpo, Schwellen-Pulse bei 25/50/75, bei 100% Overshoot-Bounce.',
      importPath: '@/motion-arsenal/effects/system/ProgressRingCharge',
      usageJsx: '<ProgressRingCharge target={100} duration={3} />',
      props: [
        { key: 'target', label: 'Target %', type: 'range', default: 100, min: 20, max: 100, step: 5 },
        { key: 'duration', label: 'Duration s', type: 'range', default: 3, min: 1, max: 8, step: 0.5 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ProgressRingCharge')),
  },
  {
    meta: {
      id: 'system-xp-fill-surge',
      name: 'XPFillSurge',
      category: 'system',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['Butterflies-CFpdR9tM.js (Wellenmix: sin(a) + sin(2.1b)*0.2)', 'KRANK additive Funken'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['XP-/Level-Systeme (NOX Forge Phase 3!)', 'Gamified Dashboards'],
      performanceNotes: 'Canvas2D: Wellenkante + wenige Funken — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Bar voll, Level-Up-Text statisch.',
      description: 'XP-Bar mit Flüssigkeits-Füllung: die Füllkante ist eine lebendige Doppel-Sinus-Welle (Shopify-Butterfly-Wellenmix), Funken steigen an der Kante auf, bei 100% zündet der Level-Up-Flash mit Overshoot.',
      importPath: '@/motion-arsenal/effects/system/XPFillSurge',
      usageJsx: '<XPFillSurge fillDuration={3.4} sparkAmount={1} />',
      props: [
        { key: 'fillDuration', label: 'Fill s', type: 'range', default: 3.4, min: 1, max: 8, step: 0.2 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'sparkAmount', label: 'Sparks', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./XPFillSurge')),
  },
  {
    meta: {
      id: 'system-agent-log-stream',
      name: 'AgentLogStream',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Agent-DNA', 'Shopify Cascade-Timing (Eintrags-Stagger)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Agent-Dashboards', 'Live-Status-Panels', 'n8n-/Worker-Monitore'],
      performanceNotes: 'DOM-Liste mit CSS-Transitions — sehr günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Statische Log-Liste ohne Stream.',
      description: 'Live-Agent-Log: Einträge streamen mit outExpo herein, ältere dimmen und schrumpfen, Typ-Badges (SCAN/EXEC/DONE/CRIT) mit LEDs, Thinking-Zeilen mit animierten Dots, kritische Einträge zünden einen Border-Blitz.',
      importPath: '@/motion-arsenal/effects/system/AgentLogStream',
      usageJsx: '<AgentLogStream interval={1.1} maxVisible={7} />',
      props: [
        { key: 'interval', label: 'Interval s', type: 'range', default: 1.1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'maxVisible', label: 'Max Rows', type: 'range', default: 7, min: 4, max: 12, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AgentLogStream')),
  },
  {
    meta: {
      id: 'system-gauge-needle-sweep',
      name: 'GaugeNeedleSweep',
      displayName: 'Gauge Needle Sweep',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Result-DNA', 'Codepen-Gauge-/Speedometer-Referenzen'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['KPI-/Performance-Dashboards', 'Gamification-Werte (Level-XP, Fitness-Scores)', 'Live-Messung-Momente in Case Studies (LCP, Score)'],
      performanceNotes: 'SVG-only, einmalige Sequenz beim In-View: rAF nur während des Count-ups (~0.9 s), danach 0 Laufzeitkosten. Kein Canvas, kein WebGL, keine Texturen.',
      mobileNotes: 'SVG skaliert responsiv über width:100%, kompakter Wert-Label-Block bleibt auf Touch-Geräten lesbar.',
      reducedMotionNotes: 'Nadel steht sofort auf dem Zielwert, Skala und Ticks sind sofort gezeichnet, kein Count-up.',
      description: 'Analoges Gold-Tachometer: SVG-Skala zeichnet sich selbst, Ticks staggern deterministisch, die Nadel schwingt mit Feder-Overshoot auf den Zielwert und der Zahlenwert zählt parallel hoch — Performance messbar machen in NOX-Signatur-Optik.',
      importPath: '@/motion-arsenal/effects/system/GaugeNeedleSweep',
      usageJsx: '<GaugeNeedleSweep value={75} min={0} max={100} label="SCORE" unit="pts" />',
      props: [
        { key: 'value', label: 'Target Value', type: 'range', default: 75, min: 0, max: 100, step: 1, group: 'Data' },
        { key: 'min', label: 'Min', type: 'range', default: 0, min: -1000, max: 1000, step: 1, group: 'Data' },
        { key: 'max', label: 'Max', type: 'range', default: 100, min: 1, max: 2000, step: 1, group: 'Data' },
        { key: 'ticks', label: 'Ticks', type: 'range', default: 11, min: 3, max: 31, step: 2, group: 'Data' },
        { key: 'decimals', label: 'Decimals', type: 'range', default: 0, min: 0, max: 2, step: 1, group: 'Data' },
        { key: 'unit', label: 'Unit', type: 'text', default: '', group: 'Data' },
        { key: 'label', label: 'Label', type: 'text', default: '', group: 'Data' },
        { key: 'sweep', label: 'Start Position', type: 'select', default: 'min', options: ['min', 'current'], group: 'Motion' },
        { key: 'overshoot', label: 'Overshoot', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1, group: 'Motion' },
        { key: 'size', label: 'Size', type: 'range', default: 320, min: 160, max: 560, step: 8, group: 'Layout' },
        { key: 'color', label: 'Accent', type: 'color', default: '#d4a24a', group: 'Color' },
        { key: 'accentColor', label: 'Needle Color', type: 'color', default: '#ff4d4d', group: 'Color' },
        { key: 'seed', label: 'Deterministic Seed', type: 'range', default: 7, min: 1, max: 20, step: 1, group: 'Data' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GaugeNeedleSweep')),
  },
];
