import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SYSTEM_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'system-rank-reveal',
      name: 'RankRevealSequence',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Result-DNA', 'KRANK Bloom-Idee (Glow-Burst), Scramble-Konvergenz'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Rang-Enthüllung', 'Ergebnis-/Award-Momente'],
      performanceNotes: 'Scramble ist ein Text-Update pro Frame — günstig.',
      mobileNotes: 'Voll touch-tauglich (Auto-Sequenz).',
      reducedMotionNotes: 'Rang sofort sichtbar, keine Sequenz.',
      description: 'Mehrstufige Rang-Enthüllung: Scan-Grid baut auf, Buchstaben-Scramble konvergiert zum Rang-Namen, Glow-Burst zündet, Metrik-Zeilen staggern nach.',
      importPath: '@/motion-arsenal/effects/system/RankRevealSequence',
      usageJsx: '<RankRevealSequence rankName="FORGED" autoReplay />',
      props: [
        { key: 'rankName', label: 'Rank Text', type: 'text', default: 'FORGED', group: 'Content' },
        { key: 'color', label: 'Text Color', type: 'color', default: '#f0ece4', group: 'Colors' },
        { key: 'accentColor', label: 'Accent Color', type: 'color', default: '#C93030', group: 'Colors' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2.5, step: 0.1, group: 'Timing' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true, group: 'Timing' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./RankRevealSequence')),
  },
  {
    meta: {
      id: 'system-scan-complete-pulse',
      name: 'ScanCompletePulse',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash (Checkmark-Draw)', 'nicht-lineares Scan-Timing (Eigenbau)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Analyse-/Lade-Momente', 'NOX Forge NPC-Scan', 'Onboarding-Checks'],
      performanceNotes: 'Segment-Rendering + ein Puls — sehr günstig.',
      mobileNotes: 'Touch-tauglich, Auto-Replay.',
      reducedMotionNotes: '100% + Checkmark sofort.',
      description: 'Segmentierte Scan-Bar mit nicht-linearem Timing (sprintet, stockt bei 42%/78%, sprintet — wie echte Scans), Status-Zeile wechselt mit, bei 100% radialer Puls + Checkmark-Draw + Grid-Blitz.',
      importPath: '@/motion-arsenal/effects/system/ScanCompletePulse',
      usageJsx: '<ScanCompletePulse segments={14} autoReplay />',
      props: [
        { key: 'segments', label: 'Segments', type: 'range', default: 14, min: 6, max: 24, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScanCompletePulse')),
  },
  {
    meta: {
      id: 'system-terminal-boot-stream',
      name: 'TerminalBootStream',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK Filter-Chain (Flicker-Idee)', 'NOX Forge Agent-Terminal-DNA'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Agent-Interfaces', 'Boot-/Lade-Sequenzen', 'Dev-Tool-Branding'],
      performanceNotes: 'Text-Updates + eine Scanline — sehr günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Alle Zeilen sofort da, kein Tippen/Flicker.',
      description: 'Terminal bootet: Zeilen tippen sich mit variablem Tempo und Mikro-Stottern, farbige Status-Tags ([OK]/[WARN]), ASCII-Header, Scanline + dezentes CRT-Flicker, am Ende pulsierender Prompt.',
      importPath: '@/motion-arsenal/effects/system/TerminalBootStream',
      usageJsx: '<TerminalBootStream speed={1} flicker />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'flicker', label: 'Flicker', type: 'boolean', default: true },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TerminalBootStream')),
  },
  {
    meta: {
      id: 'system-progress-ring-charge',
      name: 'ProgressRingCharge',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Bounce bei 100%)', 'Bloom-Idee (Glow-Ring-Kopie)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Dashboards', 'Skill-/XP-Anzeigen', 'Lade-Zustände mit Charakter'],
      performanceNotes: 'conic-gradient + Blur-Kopie — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Ziel-Prozent sofort, kein Zählen.',
      description: 'Ring lädt via conic-gradient mit Glow-Ring-Kopie dahinter und leuchtendem Lauf-Kopf; die Zahl zählt mit outExpo, Schwellen-Pulse bei 25/50/75, bei 100% Overshoot-Bounce.',
      importPath: '@/motion-arsenal/effects/system/ProgressRingCharge',
      usageJsx: '<ProgressRingCharge target={100} duration={3} />',
      props: [
        { key: 'target', label: 'Target %', type: 'range', default: 100, min: 20, max: 100, step: 5 },
        { key: 'duration', label: 'Duration s', type: 'range', default: 3, min: 1, max: 8, step: 0.5 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ProgressRingCharge')),
  },
  {
    meta: {
      id: 'system-xp-fill-surge',
      name: 'XPFillSurge',
      category: 'system',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['Butterflies-CFpdR9tM.js (Wellenmix: sin(a) + sin(2.1b)*0.2)', 'KRANK additive Funken'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['XP-/Level-Systeme (NOX Forge Phase 3!)', 'Gamified Dashboards'],
      performanceNotes: 'Canvas2D: Wellenkante + wenige Funken — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Bar voll, Level-Up-Text statisch.',
      description: 'XP-Bar mit Flüssigkeits-Füllung: die Füllkante ist eine lebendige Doppel-Sinus-Welle (Shopify-Butterfly-Wellenmix), Funken steigen an der Kante auf, bei 100% zündet der Level-Up-Flash mit Overshoot.',
      importPath: '@/motion-arsenal/effects/system/XPFillSurge',
      usageJsx: '<XPFillSurge fillDuration={3.4} sparkAmount={1} />',
      props: [
        { key: 'fillDuration', label: 'Fill s', type: 'range', default: 3.4, min: 1, max: 8, step: 0.2 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'sparkAmount', label: 'Sparks', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'autoReplay', label: 'Auto-Replay', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./XPFillSurge')),
  },
  {
    meta: {
      id: 'system-agent-log-stream',
      name: 'AgentLogStream',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Agent-DNA', 'Shopify Cascade-Timing (Eintrags-Stagger)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Agent-Dashboards', 'Live-Status-Panels', 'n8n-/Worker-Monitore'],
      performanceNotes: 'DOM-Liste mit CSS-Transitions — sehr günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Statische Log-Liste ohne Stream.',
      description: 'Live-Agent-Log: Einträge streamen mit outExpo herein, ältere dimmen und schrumpfen, Typ-Badges (SCAN/EXEC/DONE/CRIT) mit LEDs, Thinking-Zeilen mit animierten Dots, kritische Einträge zünden einen Border-Blitz.',
      importPath: '@/motion-arsenal/effects/system/AgentLogStream',
      usageJsx: '<AgentLogStream interval={1.1} maxVisible={7} />',
      props: [
        { key: 'interval', label: 'Interval s', type: 'range', default: 1.1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'maxVisible', label: 'Max Rows', type: 'range', default: 7, min: 4, max: 12, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AgentLogStream')),
  },
  {
    meta: {
      id: 'system-gauge-needle-sweep',
      name: 'GaugeNeedleSweep',
      displayName: 'Gauge Needle Sweep',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Result-DNA', 'Codepen-Gauge-/Speedometer-Referenzen'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['KPI-/Performance-Dashboards', 'Gamification-Werte (Level-XP, Fitness-Scores)', 'Live-Messung-Momente in Case Studies (LCP, Score)'],
      performanceNotes: 'SVG-only, einmalige Sequenz beim In-View: rAF nur während des Count-ups (~0.9 s), danach 0 Laufzeitkosten. Kein Canvas, kein WebGL, keine Texturen.',
      mobileNotes: 'SVG skaliert responsiv über width:100%, kompakter Wert-Label-Block bleibt auf Touch-Geräten lesbar.',
      reducedMotionNotes: 'Nadel steht sofort auf dem Zielwert, Skala und Ticks sind sofort gezeichnet, kein Count-up.',
      description: 'Analoges Gold-Tachometer: SVG-Skala zeichnet sich selbst, Ticks staggern deterministisch, die Nadel schwingt mit Feder-Overshoot auf den Zielwert und der Zahlenwert zählt parallel hoch — Performance messbar machen in NOX-Signatur-Optik.',
      importPath: '@/motion-arsenal/effects/system/GaugeNeedleSweep',
      usageJsx: '<GaugeNeedleSweep value={75} min={0} max={100} label="SCORE" unit="pts" />',
      props: [
        { key: 'value', label: 'Target Value', type: 'range', default: 75, min: 0, max: 100, step: 1, group: 'Data' },
        { key: 'min', label: 'Min', type: 'range', default: 0, min: -1000, max: 1000, step: 1, group: 'Data' },
        { key: 'max', label: 'Max', type: 'range', default: 100, min: 1, max: 2000, step: 1, group: 'Data' },
        { key: 'ticks', label: 'Ticks', type: 'range', default: 11, min: 3, max: 31, step: 2, group: 'Data' },
        { key: 'decimals', label: 'Decimals', type: 'range', default: 0, min: 0, max: 2, step: 1, group: 'Data' },
        { key: 'unit', label: 'Unit', type: 'text', default: '', group: 'Data' },
        { key: 'label', label: 'Label', type: 'text', default: '', group: 'Data' },
        { key: 'sweep', label: 'Start Position', type: 'select', default: 'min', options: ['min', 'current'], group: 'Motion' },
        { key: 'overshoot', label: 'Overshoot', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1, group: 'Motion' },
        { key: 'size', label: 'Size', type: 'range', default: 320, min: 160, max: 560, step: 8, group: 'Layout' },
        { key: 'color', label: 'Accent', type: 'color', default: '#d4a24a', group: 'Color' },
        { key: 'accentColor', label: 'Needle Color', type: 'color', default: '#ff4d4d', group: 'Color' },
        { key: 'seed', label: 'Deterministic Seed', type: 'range', default: 7, min: 1, max: 20, step: 1, group: 'Data' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GaugeNeedleSweep')),
  },
  {
    meta: {
      id: 'system-skeleton-shimmer',
      name: 'SkeletonShimmerLoader',
      displayName: 'Skeleton Shimmer Loader',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX System DNA', 'Skeleton-Screen-Muster'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Ladezustaende in Dashboards und Listen', 'Karten- und Feed-Platzhalter vor dem Datenabruf', 'Wahrgenommene Ladezeit senken statt Spinner zeigen'],
      performanceNotes: 'CSS-only. Der Shimmer ist ein ::after-Gradient, der per translateX ueber die Form faehrt - eine Compositor-Transform statt background-position, die jeden Frame neu zeichnen muesste. Kein JS, kein rAF.',
      mobileNotes: 'Bloecke skalieren ueber die Containerbreite; keine Pointer-Abhaengigkeit.',
      reducedMotionNotes: 'Shimmer steht still, die Bloecke bleiben als ruhige Flaechen mit dezenter Aufhellung sichtbar.',
      description: 'Ladeplatzhalter in vier Layouts - Karte, Liste, Avatar-Block oder reine Zeilen. Der ganze Block traegt aria-busy und einen Statustext, damit der Ladezustand nicht rein visuell bleibt.',
      importPath: '@/motion-arsenal/effects/system/SkeletonShimmerLoader',
      usageJsx: '<SkeletonShimmerLoader variant="card" rows={4} speed={1} />',
      props: [
        { key: 'variant', label: 'Layout', type: 'select', default: 'card', options: ['card', 'list', 'avatar', 'line'], group: 'Layout' },
        { key: 'rows', label: 'Zeilen', type: 'range', default: 4, min: 1, max: 12, step: 1, group: 'Layout' },
        { key: 'radius', label: 'Radius', type: 'range', default: 10, min: 0, max: 24, step: 1, group: 'Layout' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'baseColor', label: 'Base', type: 'color', default: '#1a1a1e', group: 'Color' },
        { key: 'shimmerColor', label: 'Shimmer', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SkeletonShimmerLoader')),
  },
  {
    meta: {
      id: 'system-count-up-metric-roller',
      name: 'CountUpMetricRoller',
      displayName: 'Count-Up Metric Roller',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['CSS @property counter-Technik', 'NOX System DNA'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Kennzahlen in Case Studies und Reports', 'Social Proof mit harten Zahlen', 'Dashboard-Kacheln beim ersten Laden'],
      performanceNotes: 'fade-Modus animiert eine registrierte CSS-@property, counter() rendert die Zahl - der Zaehler laeuft im Compositor ohne JS pro Frame. slot-Modus rollt Ziffernspalten per transform. Einmaliger IntersectionObserver, danach keine Laufzeitkosten.',
      mobileNotes: 'Schriftgroesse ueber clamp, tabular-nums verhindert Springen der Breite waehrend des Zaehlens.',
      reducedMotionNotes: 'Zielwert steht sofort, kein Hochzaehlen und kein Rollen.',
      description: 'Kennzahl, die beim Einlaufen von null auf den Zielwert zaehlt - wahlweise als weicher Zaehler oder als rollende Ziffernwalze. Der Wert steht zusaetzlich als Text im DOM, damit Screenreader und Suchmaschinen die Zahl sehen und nicht nur eine Huelle.',
      importPath: '@/motion-arsenal/effects/system/CountUpMetricRoller',
      usageJsx: '<CountUpMetricRoller target={100000} variant="fade" suffix="+" />',
      props: [
        { key: 'target', label: 'Zielwert', type: 'range', default: 100000, min: 0, max: 9999999, step: 1000, group: 'Data' },
        { key: 'decimals', label: 'Nachkommastellen', type: 'range', default: 0, min: 0, max: 2, step: 1, group: 'Data' },
        { key: 'prefix', label: 'Praefix', type: 'text', default: '', group: 'Data' },
        { key: 'suffix', label: 'Suffix', type: 'text', default: '+', group: 'Data' },
        { key: 'label', label: 'Beschriftung', type: 'text', default: 'Aufrufe im Quartal', group: 'Data' },
        { key: 'variant', label: 'Modus', type: 'select', default: 'fade', options: ['fade', 'slot'], group: 'Motion' },
        { key: 'duration', label: 'Dauer ms', type: 'range', default: 1400, min: 300, max: 3000, step: 50, group: 'Motion' },
        { key: 'salt', label: 'Seed', type: 'range', default: 3, min: 1, max: 99, step: 1, group: 'Motion' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./CountUpMetricRoller')),
  },
  {
    meta: {
      id: 'system-barcode-scan-line',
      name: 'BarcodeScanLine',
      displayName: 'Barcode Scan Line',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX System DNA', 'Scanner-Aesthetik'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Status- und Check-in-Oberflaechen', 'Logistik- und Inventar-Dashboards', 'Ticket- und Zugangsbestaetigungen'],
      performanceNotes: 'CSS-only: Streifen als repeating Gradient, Laser per translateY, Beep als scale-Keyframe. Kein Canvas, kein JS pro Frame.',
      mobileNotes: 'Code skaliert ueber die Containerbreite; keine Pointer-Abhaengigkeit.',
      reducedMotionNotes: 'Laser steht mittig still, Beep-Puls pulsiert nicht.',
      description: 'Barcode mit wanderndem Laser und Beep-Puls. Die Streifenbreiten kommen aus einem Seed statt aus Zufall - ein Code, der bei jedem Rendern anders aussieht, wirkt wie ein Fehler.',
      importPath: '@/motion-arsenal/effects/system/BarcodeScanLine',
      usageJsx: '<BarcodeScanLine speed={1} beep code="4 018 293 771 204" />',
      props: [
        { key: 'bars', label: 'Streifen', type: 'range', default: 42, min: 12, max: 90, step: 1, group: 'Code' },
        { key: 'code', label: 'Nummer', type: 'text', default: '4 018 293 771 204', group: 'Code' },
        { key: 'seed', label: 'Seed', type: 'range', default: 11, min: 1, max: 99, step: 1, group: 'Code' },
        { key: 'speed', label: 'Scan-Tempo', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1, group: 'Motion' },
        { key: 'beep', label: 'Beep-Puls', type: 'boolean', default: true, group: 'Motion' },
        { key: 'color', label: 'Laser', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./BarcodeScanLine')),
  },
  {
    meta: {
      id: 'system-progress-ring-scanner',
      name: 'ProgressRingScanner',
      displayName: 'Progress Ring Scanner',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX System DNA', 'Radar-Sweep-Muster'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Auslastung und Fortschritt in Dashboards', 'Analyse- und Pruefvorgaenge', 'KPI-Kacheln mit einem Leitwert'],
      performanceNotes: 'SVG-Bogen ueber stroke-dasharray auf pathLength=1 - der Fortschritt ist direkt der Anteil, unabhaengig von der Rendergroesse. Der Sweep ist ein rotierendes conic-gradient. Kein Canvas.',
      mobileNotes: 'Ring skaliert ueber die Groessen-Prop; der Wert bleibt in der Mitte lesbar.',
      reducedMotionNotes: 'Radar-Keil rotiert nicht und bleibt als ruhige Flaeche stehen; der Bogen springt ohne Transition auf den Wert.',
      description: 'Fortschrittsring mit rotierendem Radar-Keil. Der Wert steht als role progressbar mit aria-valuenow im DOM, damit der Fortschritt nicht nur als Bogen existiert.',
      importPath: '@/motion-arsenal/effects/system/ProgressRingScanner',
      usageJsx: '<ProgressRingScanner progress={0.64} speed={1} label="SCAN" />',
      props: [
        { key: 'progress', label: 'Fortschritt', type: 'range', default: 0.64, min: 0, max: 1, step: 0.01, group: 'Data' },
        { key: 'label', label: 'Beschriftung', type: 'text', default: 'SCAN', group: 'Data' },
        { key: 'showValue', label: 'Wert anzeigen', type: 'boolean', default: true, group: 'Data' },
        { key: 'size', label: 'Durchmesser', type: 'range', default: 190, min: 90, max: 400, step: 5, group: 'Layout' },
        { key: 'thickness', label: 'Strichbreite', type: 'range', default: 6, min: 2, max: 20, step: 1, group: 'Layout' },
        { key: 'speed', label: 'Sweep-Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ProgressRingScanner')),
  },
  { meta: { id: 'system-context-aware-fixed-emblem', name: 'ContextAwareFixedEmblem', displayName: 'Context Aware Fixed Emblem', category: 'system', sourceWebsite: 'codrops', sourceFiles: ['context-aware-fixed-elements'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Fixed Branding', 'Scroll Context'], performanceNotes: 'IntersectionObserver schaltet CSS-Zustaende.', mobileNotes: 'Kompakte Fixposition.', reducedMotionNotes: 'Keine Ausweichbewegung.', description: 'Fixiertes Emblem reagiert auf kollidierende Sektionen.', importPath: '@/motion-arsenal/effects/system/ContextAwareFixedEmblem', usageJsx: '<ContextAwareFixedEmblem />', props: [{ key: 'mode', label: 'Reaktion', type: 'select', default: 'rotate-away', options: ['scale-down', 'rotate-away', 'blur', 'push-up'] }, { key: 'label', label: 'Label', type: 'text', default: 'NOX' }, { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./ContextAwareFixedEmblem')) },
  { meta: { id: 'system-counter-preloader', name: 'CounterPreloader', displayName: 'Counter Preloader', category: 'system', sourceWebsite: 'codrops', sourceFiles: ['counter preloader'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Page Loads', 'Launch Moments'], performanceNotes: 'Ein rAF bis 100.', mobileNotes: 'Lesbare Zahl.', reducedMotionNotes: 'Sofort 100.', description: 'Gold-Zaehler mit Balken und Clip-Path-Wipe.', importPath: '@/motion-arsenal/effects/system/CounterPreloader', usageJsx: '<CounterPreloader />', props: [{ key: 'duration', label: 'Dauer ms', type: 'range', default: 2200, min: 500, max: 5000, step: 100 }, { key: 'label', label: 'Label', type: 'text', default: 'LOADING SYSTEM' }, { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./CounterPreloader')) },
  { meta: { id: 'system-crt-screen-text', name: 'CrtScreenText', displayName: 'CRT Screen Text', category: 'system', sourceWebsite: 'nox-original', sourceFiles: ['NOX CRT terminal treatment'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Terminal UI', 'Retro Status'], performanceNotes: 'CSS-only scanline and glitch.', mobileNotes: 'Tap toggles the signal pulse.', reducedMotionNotes: 'Static scanline.', description: 'Monospace CRT status text with scanlines, phosphor glow and RGB ghosting.', importPath: '@/motion-arsenal/effects/system/CrtScreenText', usageJsx: '<CrtScreenText text="SIGNAL LOCKED" />', props: [{ key: 'text', label: 'Text', type: 'text', default: 'SIGNAL LOCKED' }, { key: 'flicker', label: 'Flicker', type: 'boolean', default: true }, { key: 'scanlines', label: 'Scanlines', type: 'boolean', default: true }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./CrtScreenText')) },
];
export const BATCH6_SYSTEM_CATALOG: EffectEntry[] = [  {
    meta: {
      id: 'system-terminal-typewriter-hover',
      name: 'TerminalTypewriterHover',
      displayName: 'Terminal Typewriter Hover',
      category: 'system',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX System DNA', 'CSS-steps-Typewriter'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Log- und Statusausgaben in Dashboards', 'Entwickler- und Agenten-Oberflaechen', 'Feature-Listen mit Terminal-Charakter'],
      performanceNotes: 'Die Animation laeuft ueber die Breite in ch-Einheiten mit steps(), also genau ein Zeichen pro Schritt - kein JS-Intervall und kein Timer.',
      mobileNotes: 'Ohne Hover stehen die Zeilen vollstaendig da; ueber Tastaturfokus laesst sich das Tippen auch ohne Zeiger ausloesen.',
      reducedMotionNotes: 'Zeilen stehen sofort vollstaendig, Cursor blinkt nicht.',
      description: 'Log-Zeilen, die sich beim Hover Zeichen fuer Zeichen selbst tippen. Die Zeilen stehen vollstaendig im DOM - wer nicht hovert, sieht denselben Text, nur ohne Tippbewegung.',
      importPath: '@/motion-arsenal/effects/system/TerminalTypewriterHover',
      usageJsx: '<TerminalTypewriterHover lines="scan --deep|deploy ready" speed={1} />',
      props: [
        { key: 'lines', label: 'Zeilen (| trennt)', type: 'text', default: 'scan --target arsenal --deep|resolving 285 effects …|contract check: 0 violations|deploy ready', group: 'Content' },
        { key: 'prompt', label: 'Prompt-Zeichen', type: 'text', default: '›', group: 'Content' },
        { key: 'alwaysOn', label: 'Immer tippen', type: 'boolean', default: false, group: 'Motion' },
        { key: 'speed', label: 'Tipp-Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'cursor', label: 'Cursor', type: 'boolean', default: true, group: 'Motion' },
        { key: 'color', label: 'Prompt', type: 'color', default: '#d4a24a', group: 'Color' },
        { key: 'textColor', label: 'Text', type: 'color', default: '#d8d2c6', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TerminalTypewriterHover')),
  },
];
