import { useMemo } from 'react';
import type { CSSProperties } from 'react';

export interface ConnectedGridPulseProps { columns?: number; rows?: number; links?: number; speed?: number; accent?: string; }

export default function ConnectedGridPulse({ columns = 6, rows = 4, links = 7, speed = 1, accent = '#d4a24a' }: ConnectedGridPulseProps) {
  const nodes = useMemo(() => Array.from({ length: Math.max(4, columns * rows) }, (_, index) => ({ index, x: (index % columns) * (100 / Math.max(1, columns - 1)), y: Math.floor(index / columns) * (100 / Math.max(1, rows - 1)) })), [columns, rows]);
  const paths = useMemo(() => Array.from({ length: Math.min(links, nodes.length - 1) }, (_, index) => { const a = nodes[index]; const b = nodes[(index * 3 + 5) % nodes.length]; return { a, b, index }; }), [links, nodes]);
  const style = { '--grid-accent': accent, '--grid-speed': `${Math.max(.2, speed)}s` } as CSSProperties;
  return <div className="nox-connected-grid" style={style} role="img" aria-label="Connected grid pulse visualization">
    <svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{paths.map(({ a, b, index }) => <g key={index}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} pathLength="1" style={{ '--line-delay': `${index * .17}s` } as CSSProperties} /><circle r="1.2" cx={a.x} cy={a.y} className="nox-connected-grid__pulse" style={{ '--pulse-delay': `${index * .17}s`, '--pulse-path': `path('M ${a.x} ${a.y} L ${b.x} ${b.y}')` } as CSSProperties} /></g>)}</svg>
    <div className="nox-connected-grid__nodes">{nodes.map((node) => <span key={node.index} style={{ left: `${node.x}%`, top: `${node.y}%`, '--node-delay': `${(node.index % 8) * .14}s` } as CSSProperties}>{String(node.index + 1).padStart(2, '0')}</span>)}</div><style>{CSS}</style>
  </div>;
}

const CSS = `
.nox-connected-grid{position:relative;min-height:280px;overflow:hidden;background:#090a0f;border:1px solid #3b2d1c;color:#f7e8a4}.nox-connected-grid:before{content:'';position:absolute;inset:0;background:linear-gradient(#d4a24a12 1px,transparent 1px),linear-gradient(90deg,#d4a24a12 1px,transparent 1px);background-size:32px 32px;mask-image:radial-gradient(circle,#000,transparent 80%)}.nox-connected-grid svg{position:absolute;inset:10%;width:80%;height:80%;overflow:visible}.nox-connected-grid line{stroke:var(--grid-accent);stroke-width:.18;stroke-dasharray:.04 .035;stroke-dashoffset:1;animation:noxGridDraw calc(var(--grid-speed) * 3) var(--line-delay) ease-in-out infinite alternate}.nox-connected-grid__pulse{fill:#f7e8a4;filter:drop-shadow(0 0 5px var(--grid-accent));animation:noxGridPulse var(--grid-speed) var(--pulse-delay) linear infinite}.nox-connected-grid__nodes{position:absolute;inset:10%}.nox-connected-grid__nodes span{position:absolute;transform:translate(-50%,-50%);display:grid;place-items:center;width:25px;height:25px;border:1px solid var(--grid-accent);border-radius:50%;background:#0b0d12;font:9px ui-monospace,monospace;box-shadow:0 0 0 4px #d4a24a12;animation:noxNodeGlow calc(var(--grid-speed) * 2) var(--node-delay) ease-in-out infinite alternate}.nox-connected-grid__nodes span:after{content:'';position:absolute;width:5px;height:5px;border-radius:50%;background:var(--grid-accent)}@keyframes noxGridDraw{to{stroke-dashoffset:0}}@keyframes noxGridPulse{0%{opacity:0;offset-distance:0}12%{opacity:1}90%{opacity:.1}100%{offset-distance:100%}}@keyframes noxNodeGlow{to{box-shadow:0 0 0 8px #d4a24a2b,0 0 20px #d4a24a55}}@media(prefers-reduced-motion:reduce){.nox-connected-grid line,.nox-connected-grid__pulse,.nox-connected-grid__nodes span{animation:none}.nox-connected-grid line{stroke-dashoffset:0}.nox-connected-grid__pulse{display:none}}`;
