import { useEffect, useMemo, useState } from 'react';
import type React from 'react';
export interface ContextAwareFixedEmblemProps { label?: string; color?: string; mode?: 'scale-down' | 'rotate-away' | 'blur' | 'push-up'; }
export default function ContextAwareFixedEmblem({ label = 'NOX', color = '#d4a24a', mode = 'rotate-away' }: ContextAwareFixedEmblemProps) {
  const [busy, setBusy] = useState(false);
  const fragments = useMemo(() => Array.from(label), [label]);
  useEffect(() => { const sections = [...document.querySelectorAll<HTMLElement>('[data-nox-context]')]; if (!sections.length) return; const observer = new IntersectionObserver((entries) => setBusy(entries.some((entry) => entry.isIntersecting)), { threshold: .2 }); sections.forEach((section) => observer.observe(section)); return () => observer.disconnect(); }, []);
  return <div className={`nox-emblem nox-emblem--${mode} ${busy ? 'is-busy' : ''}`} style={{ '--emblem-color': color } as React.CSSProperties} aria-label={`${label} context emblem`}>{fragments.map((char, i) => <span key={`${char}-${i}`} style={{ '--emblem-i': i } as React.CSSProperties}>{char}</span>)}<i aria-hidden="true" /><style>{CSS}</style></div>;
}
const CSS = String.raw`.nox-emblem{position:fixed;right:clamp(1rem,4vw,4rem);bottom:clamp(1rem,5vw,4rem);z-index:20;width:76px;height:76px;border:1px solid var(--emblem-color);border-radius:50%;display:grid;place-items:center;color:var(--emblem-color);font:800 13px monospace;letter-spacing:.08em;background:#090a0ecc;box-shadow:0 0 28px #d4a24a33;transition:transform .7s cubic-bezier(.2,.9,.2,1),filter .7s,opacity .7s}.nox-emblem span{display:inline-block;transition:transform .7s}.nox-emblem i{position:absolute;inset:8px;border:1px solid #d4a24a55;border-radius:50%;animation:emblem-pulse 2.8s ease-in-out infinite}.nox-emblem.is-busy{opacity:.72}.nox-emblem--scale-down.is-busy{transform:scale(.62)}.nox-emblem--rotate-away.is-busy{transform:translateX(25px) rotate(28deg)}.nox-emblem--blur.is-busy{filter:blur(4px);transform:scale(.8)}.nox-emblem--push-up.is-busy{transform:translateY(-28vh)}.nox-emblem.is-busy span{transform:translateX(calc((var(--emblem-i) - 1) * 4px))}@keyframes emblem-pulse{50%{transform:scale(1.16);opacity:.35}}@media(prefers-reduced-motion:reduce){.nox-emblem,.nox-emblem span{transition:none}.nox-emblem i{animation:none}}`;
