import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const CARDS_CATALOG: EffectEntry[] = [
  { meta: { id: 'cards-gold-edge-flip-card', name: 'GoldEdgeFlipCard', displayName: 'Gold Edge Flip Card', category: 'cards', sourceWebsite: 'codrops', sourceFiles: ['Vault: nox-gold-edge-flip-card'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Feature Cards', 'Team Cards'], performanceNotes: 'Transform-only 3D flip.', mobileNotes: 'Tap and keyboard toggle.', reducedMotionNotes: 'Flip transition is removed.', description: 'A tactile gold-edged 3D card with hovering title.', importPath: '@/motion-arsenal/effects/cards/GoldEdgeFlipCard', usageJsx: '<GoldEdgeFlipCard />', props: [{ key: 'axis', label: 'Axis', type: 'select', default: 'y', options: ['x','y'] }, { key: 'glow', label: 'Glow', type: 'range', default: .6, min: 0, max: 1, step: .1 }, { key: 'tilt', label: 'Perspective', type: 'range', default: 1, min: .5, max: 2, step: .1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./GoldEdgeFlipCard')) },
  { meta: { id: 'cards-grid-sliced-hover', name: 'GridSlicedHover', displayName: 'Grid Sliced Hover', category: 'cards', sourceWebsite: 'codrops', sourceFiles: ['Vault: nox-grid-sliced-hover'], mode: 'nox-original', complexity: 'low', dependencies: [], bestFor: ['Portfolio Teasers', 'Image Cards'], performanceNotes: 'Bounded transform-only slice transitions.', mobileNotes: 'Focus and tap activate.', reducedMotionNotes: 'Slices remain assembled.', description: 'A visual splits into staggered horizontal slices on hover.', importPath: '@/motion-arsenal/effects/cards/GridSlicedHover', usageJsx: '<GridSlicedHover src="/image.jpg" />', props: [{ key: 'src', label: 'Image', type: 'text', default: '' }, { key: 'alt', label: 'Alt', type: 'text', default: 'Sliced image' }, { key: 'slices', label: 'Slices', type: 'range', default: 6, min: 3, max: 12, step: 1 }, { key: 'intensity', label: 'Intensity', type: 'range', default: .5, min: 0, max: 1, step: .1 }, { key: 'speed', label: 'Speed', type: 'range', default: 1, min: .1, max: 3, step: .1 }], productionSafe: true }, Component: lazy(() => import('./GridSlicedHover')) },
  { meta: { id: 'cards-card-fan-deck', name: 'CardFanDeck', displayName: 'Card Fan Deck', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['wearedevelopers 3D card fan', 'Vault: nox-card-fan-deck'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Card-Showcases', 'Achievements', 'Onboarding'], performanceNotes: 'Nur CSS-Transforms und Transitionen, keine Render-Schleife.', mobileNotes: 'Pointer- und Fokus-Trigger sind touch-fähig.', reducedMotionNotes: 'Stapel bleibt flach, Fokus bleibt sichtbar.', description: 'Ein deterministisch gefächertes 3D-Kartendeck mit Deal-Interaktion und Gold-Kanten.', importPath: '@/motion-arsenal/effects/cards/CardFanDeck', usageJsx: '<CardFanDeck count={6} />', props: [{ key: 'count', label: 'Cards', type: 'range', default: 6, min: 3, max: 12, step: 1 }, { key: 'spread', label: 'Spread', type: 'range', default: 34, min: 10, max: 70, step: 1 }, { key: 'radius', label: 'Radius', type: 'range', default: 14, min: 0, max: 32, step: 1 }, { key: 'speed', label: 'Speed', type: 'range', default: 1, min: .1, max: 3, step: .1 }, { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' }, { key: 'salt', label: 'Seed', type: 'range', default: 11, min: 1, max: 99, step: 1 }], productionSafe: true, status: 'production-safe' }, Component: lazy(() => import('./CardFanDeck')) },
  {
    meta: {
      id: 'cards-glass-metal-panel',
      name: 'GlassMetalPanel',
      category: 'cards',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['shopify.css (Glass-Nav: rgba + backdrop-blur + blend)', 'conic-gradient Anisotropie (Eigenbau)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Pricing-Karten', 'Feature-Panels', 'Premium-Dashboards'],
      performanceNotes: 'backdrop-filter ist die Hauptlast — pro Viewport wenige Panels.',
      mobileNotes: 'Touch: Auto-Demo-Zyklus statt Hover.',
      reducedMotionNotes: 'Statisches Panel, Lichtkante fix.',
      description: 'Premium-Panel: geschichtetes Glas (Blur, Innen-Gradient, Kanten-Highlight) über gebürstetem Metall mit conic-gradient-Anisotropie-Schimmer; Hover kippt die Lichtkante.',
      importPath: '@/motion-arsenal/effects/cards/GlassMetalPanel',
      usageJsx: '<GlassMetalPanel tint="#C93030" blur={12} sheen={0.8} />',
      props: [
        { key: 'tint', label: 'Tint', type: 'color', default: '#C93030' },
        { key: 'blur', label: 'Blur', type: 'range', default: 12, min: 4, max: 22, step: 1 },
        { key: 'sheen', label: 'Sheen', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 2, step: 0.1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GlassMetalPanel')),
  },
  {
    meta: {
      id: 'cards-border-trace-depth',
      name: 'BorderTraceDepth',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash Mechanik + Bloom-Idee (Glow-Kopie hinter der Kante)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Aktive/ausgewählte Karten', 'Rank-Panels', 'Hervorhebungen'],
      performanceNotes: 'conic-gradient-Maske + Blur-Kopie — moderat, GPU-composited.',
      mobileNotes: 'Läuft autonom, touch-tauglich.',
      reducedMotionNotes: 'Statische Kante mit fixem Licht.',
      description: 'Border-Trace mit echter Tiefe: laufendes Kantenlicht (conic-Maske) + versetzte Glow-Kopie dahinter + Innenreflex, der dem Licht folgt — drei gekoppelte Layer statt 0815-Scan.',
      importPath: '@/motion-arsenal/effects/cards/BorderTraceDepth',
      usageJsx: '<BorderTraceDepth speed={1} color="#d4a24a" />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' },
        { key: 'thickness', label: 'Thickness', type: 'range', default: 2, min: 1, max: 5, step: 0.5 },
        { key: 'depthOffset', label: 'Depth', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./BorderTraceDepth')),
  },
  {
    meta: {
      id: 'cards-hover-light-refraction',
      name: 'HoverLightRefraction',
      category: 'cards',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (Velocity-Denken: Effektstärke ∝ Pointer-Geschwindigkeit)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Produkt-/Portfolio-Karten', 'Premium-Grids'],
      performanceNotes: 'Zwei Gradient-Kopien + Transforms — günstig.',
      mobileNotes: 'Touch: Auto-Highlight-Wanderung.',
      reducedMotionNotes: 'Statisches Highlight mittig.',
      description: 'Pointer-abhängige Glas-Refraktion: das Specular-Highlight wandert gegenläufig zum Pointer, ein chromatischer Kanten-Saum (rot/cyan versetzt) wächst mit der Pointer-Velocity.',
      importPath: '@/motion-arsenal/effects/cards/HoverLightRefraction',
      usageJsx: '<HoverLightRefraction refraction={0.6} chroma={1} />',
      props: [
        { key: 'refraction', label: 'Refraction', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
        { key: 'chroma', label: 'Chroma', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'highlightSize', label: 'Highlight px', type: 'range', default: 160, min: 80, max: 280, step: 10 },
        { key: 'tint', label: 'Tint', type: 'color', default: '#d4a24a' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./HoverLightRefraction')),
  },
  {
    meta: {
      id: 'cards-tilt-parallax',
      name: 'TiltParallaxCard',
      category: 'cards',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (damp λ≈12 Pointer-Follow)', 'KRANK/src/index.css (Overshoot-Settle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Rank-/Membercards', 'Showcase-Kacheln', 'NFT-/Sammelkarten-Feel'],
      performanceNotes: 'perspective + wenige translateZ-Ebenen — günstig.',
      mobileNotes: 'Touch: sanfte Auto-Rotation.',
      reducedMotionNotes: 'Karte flach, Ebenen statisch versetzt.',
      description: '3D-Tilt mit inneren Parallax-Ebenen: Badge, Typo, Zahl und Glow schweben auf translateZ-Stufen, ein Glanz-Sweep läuft mit dem Tilt-Winkel, das Settle federt mit KRANK-Overshoot.',
      importPath: '@/motion-arsenal/effects/cards/TiltParallaxCard',
      usageJsx: '<TiltParallaxCard maxTilt={12} depth={1} glare={0.7} />',
      props: [
        { key: 'maxTilt', label: 'Tilt °', type: 'range', default: 12, min: 4, max: 24, step: 1 },
        { key: 'depth', label: 'Depth', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'glare', label: 'Glare', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'overshoot', label: 'Overshoot', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TiltParallaxCard')),
  },
  {
    meta: {
      id: 'cards-lock-unlock-scan',
      name: 'LockUnlockScan',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Filter-Chain saturate/brightness via Var)', 'stroke-dash Border-Trace'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Gating (Black Forge!)', 'Premium-Feature-Locks', 'Fortschritts-Freischaltungen'],
      performanceNotes: 'Scanline + Noise nur im Locked-Zustand; Unlock ist eine einmalige Sequenz.',
      mobileNotes: 'Tap = Unlock, voll touch-tauglich.',
      reducedMotionNotes: 'Direkt entsperrter Zustand ohne Sequenz.',
      description: 'Gating-Karte: Locked = entsättigt mit laufender Scanline und Rausch-Overlay; Klick zündet die Unlock-Sequenz — Scan-Blitz, Border-Trace, Content-Stagger, LED rot→gold.',
      importPath: '@/motion-arsenal/effects/cards/LockUnlockScan',
      usageJsx: '<LockUnlockScan accent="#d4a24a" />',
      props: [
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'scanSpeed', label: 'Scan Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'autoRelock', label: 'Auto-Relock', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./LockUnlockScan')),
  },
  {
    meta: {
      id: 'cards-fold-notch-panel',
      name: 'FoldNotchPanel',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Easing)', 'NOX forge-cut Notch-Ästhetik'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Info-Panels', 'Sequenzielle Content-Enthüllung', 'NOX-System-Module'],
      performanceNotes: 'Ein rotateX-Transform + Schatten — sehr günstig.',
      mobileNotes: 'Auto-Zyklus, touch-tauglich.',
      reducedMotionNotes: 'Panel offen, statisch.',
      description: 'Panel mit clip-path-Notch klappt physisch aus der Oberkante auf (rotateX + Overshoot), der Bodenschatten folgt dem Klappwinkel, die Signal-LED sichert die geschnittene Ecke.',
      importPath: '@/motion-arsenal/effects/cards/FoldNotchPanel',
      usageJsx: '<FoldNotchPanel notchSize={22} accent="#C93030" />',
      props: [
        { key: 'notchSize', label: 'Notch px', type: 'range', default: 22, min: 10, max: 40, step: 2 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 2, step: 0.1 },
        { key: 'autoCycle', label: 'Auto-Cycle', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./FoldNotchPanel')),
  },
  {
    meta: {
      id: 'cards-accordion',
      name: 'AccordionCards',
      displayName: 'Accordion Cards',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['devto-accessible-animated-accordion', 'sophiabits-animated-heights'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['FAQ- und Docs-Sektionen mit Premium-Panel-Optik', 'Gestaffelte Inhalte, bei denen genau ein Block fokussiert sein soll', 'Platzsparende Alternative zu Voll-Karten-Rastern'],
      performanceNotes: 'Hoehenanimation ueber grid-template-rows 0fr zu 1fr: der Browser interpoliert die Content-Hoehe selbst, kein JS-Messen und kein height-Hack. Animiert wird nur beim Oeffnen und Schliessen, kein Dauerbetrieb.',
      mobileNotes: 'Volle Breite, Touch-Targets ueber 44px, native Buttons mit Tastaturbedienung.',
      reducedMotionNotes: 'Panel wechselt hart ohne Slide; Inhalte und Fokusreihenfolge bleiben unveraendert.',
      description: 'Gestapelte Panels als Akkordeon: immer nur eines offen, die Hoehe animiert ueber einen Grid-Track statt gemessener Pixelwerte. Das aktive Panel bekommt Gold-Rahmen und Glow, aria-expanded und aria-controls sind sauber verdrahtet.',
      importPath: '@/motion-arsenal/effects/cards/AccordionCards',
      usageJsx: '<AccordionCards openIndex={0} speed={1} collapsible={false} />',
      props: [
        { key: 'openIndex', label: 'Offenes Panel', type: 'range', default: 0, min: -1, max: 3, step: 1, group: 'Content' },
        { key: 'collapsible', label: 'Alles schliessbar', type: 'boolean', default: false, group: 'Content' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'accent', label: 'Akzent', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AccordionCards')),
  },
  { meta: { id: 'cards-horizontal-accordion-gallery', name: 'HorizontalAccordionGallery', displayName: 'Horizontal Accordion Gallery', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-horizontal-accordion-gallery'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Galleries'], performanceNotes: 'Flex transforms and opacity.', mobileNotes: 'Tap expands panels.', reducedMotionNotes: 'Selected panel stays open.', description: 'A tactile horizontal accordion gallery.', importPath: '@/motion-arsenal/effects/cards/HorizontalAccordionGallery', usageJsx: '<HorizontalAccordionGallery />', props: [], productionSafe: true }, Component: lazy(() => import('./HorizontalAccordionGallery')) },
  { meta: { id: 'cards-liquid-distortion-card', name: 'LiquidDistortionCard', displayName: 'Liquid Distortion Card', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-liquid-distortion-card'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Hover Surfaces'], performanceNotes: 'Scoped SVG displacement.', mobileNotes: 'Tap toggles state.', reducedMotionNotes: 'Filter motion stops.', description: 'A card surface ripples like liquid.', importPath: '@/motion-arsenal/effects/cards/LiquidDistortionCard', usageJsx: '<LiquidDistortionCard />', props: [], productionSafe: true }, Component: lazy(() => import('./LiquidDistortionCard')) },
  { meta: { id: 'cards-polaroid-stack-scroll', name: 'PolaroidStackScroll', displayName: 'Polaroid Stack Scroll', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Polaroid Stack Scroll.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Scroll Stories', 'Portfolio'], performanceNotes: 'rAF-Loop scrubbt transform/opacity/filter, keine Layout-Writes.', mobileNotes: 'Kartenanzahl begrenzt (max 8).', reducedMotionNotes: 'Karten stehen direkt im Stack.', description: 'Gestreute Polaroids ordnen sich beim Scrollen zu einem Stack — Transform-, Blur- und Opacity-Scrub.', importPath: '@/motion-arsenal/effects/cards/PolaroidStackScroll', usageJsx: '<PolaroidStackScroll count={5} />', props: [{ key: 'count', label: 'Polaroids', type: 'range', default: 5, min: 3, max: 8, step: 1 }, { key: 'stackOffset', label: 'Stack-Versatz px', type: 'range', default: 6, min: 2, max: 16, step: 1 }, { key: 'scatter', label: 'Streuung %', type: 'range', default: 30, min: 10, max: 45, step: 1 }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./PolaroidStackScroll')) },
  { meta: { id: 'cards-layered-zoom-dolly', name: 'LayeredZoomDolly', displayName: 'Layered Zoom Dolly', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Layered Zoom Dolly.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Cinematic Scroll', 'Case Studies'], performanceNotes: 'Kamera-Transform pro Frame (1 Element), Ebenen statisch positioniert.', mobileNotes: 'Ebenenanzahl begrenzt (max 6).', reducedMotionNotes: 'Statische Tiefenkomposition.', description: 'Mehrere 2D-Ebenen in preserve-3d erzeugen eine räumliche Kamerafahrt — echte Parallaxe via translateZ.', importPath: '@/motion-arsenal/effects/cards/LayeredZoomDolly', usageJsx: '<LayeredZoomDolly layers={["NOX","ARSENAL","SYSTEM"]} />', props: [{ key: 'layers', label: 'Ebenen', type: 'text', default: '' }, { key: 'depth', label: 'Tiefe px', type: 'range', default: 800, min: 400, max: 1200, step: 50 }, { key: 'mode', label: 'Steuerung', type: 'select', default: 'scroll' }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./LayeredZoomDolly')) },

  { meta: { id: 'cards-tearing-photo-drag', name: 'TearingPhotoDrag', displayName: 'Tearing Photo Drag', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Tearing Photo Drag.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Interactions', 'Showcases'], performanceNotes: 'rAF setzt nur transform auf Streifen; Pointer-Mapping per Rect.', mobileNotes: 'Streifenzahl begrenzt (max 24).', reducedMotionNotes: 'Starrer Drag ohne Riss.', description: 'Foto zerreißt beim Ziehen: Streifen verschieben sich gestaffelt (det-PRNG), beim Loslassen federnder Rückzug.', importPath: '@/motion-arsenal/effects/cards/TearingPhotoDrag', usageJsx: '<TearingPhotoDrag />', props: [{ key: 'src', label: 'Bild-URL', type: 'text', default: '' }, { key: 'strips', label: 'Streifen', type: 'range', default: 12, min: 6, max: 24, step: 1 }, { key: 'tear', label: 'Riss px', type: 'range', default: 14, min: 2, max: 40, step: 1 }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./TearingPhotoDrag')) },
  { meta: { id: 'cards-lenticular-tilt', name: 'LenticularTiltCard', displayName: 'Lenticular Tilt', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Product Cards', 'Interaktive Medien'], performanceNotes: 'Nur transform + background-position-Writes, rAF-gedrosselt.', mobileNotes: 'Touch: Tilt via Pointer-Bewegung.', reducedMotionNotes: 'Statisches Mittelframe.', description: 'Interlaced Multi-Frame-Bild als DOM-Slices; Pointer-Tilt waehlt den sichtbaren Frame (lenticular-typisch gerastert).', importPath: '@/motion-arsenal/effects/cards/LenticularTiltCard', usageJsx: '<LenticularTiltCard />', props: [{ key: "frames", label: "Frames", type: "text", default: "" }, { key: "slices", label: "Slices", type: "range", default: 24, min: 8, max: 48, step: 2 }, { key: "maxTilt", label: "Tilt", type: "range", default: 18, min: 4, max: 30, step: 1 }, { key: "wobble", label: "Wobble", type: "range", default: 0, min: 0, max: 20, step: 1 }], productionSafe: true }, Component: lazy(() => import('./LenticularTiltCard')) },
  { meta: { id: 'cards-gsap-flip-gallery', name: 'GSAPFlipGalleryMorph', displayName: 'GSAP Flip Gallery Morph', category: 'cards', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Portfolio Galleries', 'Case Studies'], performanceNotes: 'Library-freies FLIP via Web Animations API, einmalig pro Oeffnen.', mobileNotes: 'Touch: Tap oeffnet, Backdrop schliesst.', reducedMotionNotes: 'Detail-View erscheint ohne Morph.', description: 'Galerie-Kachel waechst per FLIP (First/Last/Invert/Play, transform-only) in den Detail-View; Fokus-Dialog-Fallback.', importPath: '@/motion-arsenal/effects/cards/GSAPFlipGalleryMorph', usageJsx: '<GSAPFlipGalleryMorph />', props: [{ key: "tiles", label: "Tiles", type: "text", default: "SIGNAL 01,SIGNAL 02,SIGNAL 03,SIGNAL 04,SIGNAL 05,SIGNAL 06" }, { key: "seed", label: "Seed", type: "range", default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./GSAPFlipGalleryMorph')) },
  {
    meta: {
      id: 'cards-magnetic-field',
      name: 'MagneticFieldCards',
      displayName: 'Magnetic Field Cards',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Cards DNA', 'Magnetic-Hover-Mechanik'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Prozess- und Leistungsraster', 'Navigationskacheln mit Spielcharakter', 'Sektionen, die zum Bewegen einladen sollen'],
      performanceNotes: 'Transforms werden direkt im Pointer-Handler gesetzt statt in einer rAF-Schleife - Pointer-Events kommen ohnehin nur bei Bewegung, ein Loop wuerde auch bei stillem Zeiger weiterlaufen. Das Zurueckfedern uebernimmt eine CSS-Transition mit Overshoot.',
      mobileNotes: 'Ohne Zeigergeraet bleiben die Karten ruhig an ihrem Platz und voll bedienbar.',
      reducedMotionNotes: 'Karten bewegen sich nicht; Hover-Rahmen und Schatten bleiben als Rueckmeldung.',
      description: 'Karten weichen dem Zeiger aus oder ziehen ihn an: innerhalb eines Radius bekommt jede Karte einen Versatz, dessen Staerke mit der Entfernung abfaellt.',
      importPath: '@/motion-arsenal/effects/cards/MagneticFieldCards',
      usageJsx: '<MagneticFieldCards radius={190} strength={0.55} polarity="attract" />',
      props: [
        { key: 'count', label: 'Karten', type: 'range', default: 6, min: 2, max: 8, step: 1, group: 'Layout' },
        { key: 'polarity', label: 'Polaritaet', type: 'select', default: 'attract', options: ['attract', 'repel'], group: 'Motion' },
        { key: 'radius', label: 'Wirkradius', type: 'range', default: 190, min: 60, max: 400, step: 10, group: 'Motion' },
        { key: 'strength', label: 'Staerke', type: 'range', default: 0.55, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'tilt', label: 'Kippen', type: 'boolean', default: true, group: 'Motion' },
        { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./MagneticFieldCards')),
  },
];
