import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const CARDS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'cards-glass-metal-panel',
      name: 'GlassMetalPanel',
      category: 'cards',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['shopify.css (Glass-Nav: rgba + backdrop-blur + blend)', 'conic-gradient Anisotropie (Eigenbau)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Pricing-Karten', 'Feature-Panels', 'Premium-Dashboards'],
      performanceNotes: 'backdrop-filter ist die Hauptlast — pro Viewport wenige Panels.',
      mobileNotes: 'Touch: Auto-Demo-Zyklus statt Hover.',
      reducedMotionNotes: 'Statisches Panel, Lichtkante fix.',
      description: 'Premium-Panel: geschichtetes Glas (Blur, Innen-Gradient, Kanten-Highlight) über gebürstetem Metall mit conic-gradient-Anisotropie-Schimmer; Hover kippt die Lichtkante.',
      importPath: '@/motion-arsenal/effects/cards/GlassMetalPanel',
      usageJsx: '<GlassMetalPanel tint="#C93030" blur={12} sheen={0.8} />',
      props: [
        { key: 'tint', label: 'Tint', type: 'color', default: '#C93030' },
        { key: 'blur', label: 'Blur', type: 'range', default: 12, min: 4, max: 22, step: 1 },
        { key: 'sheen', label: 'Sheen', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 2, step: 0.1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GlassMetalPanel')),
  },
  {
    meta: {
      id: 'cards-border-trace-depth',
      name: 'BorderTraceDepth',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash Mechanik + Bloom-Idee (Glow-Kopie hinter der Kante)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Aktive/ausgewählte Karten', 'Rank-Panels', 'Hervorhebungen'],
      performanceNotes: 'Ein rAF treibt nur CSS-Variablen und pausiert offscreen/reduced-motion; conic-gradient-Maske + Blur-Kopie bleiben GPU-komponiert.',
      mobileNotes: 'Touch nutzt nur einen ruhigen Ambient-Boost und lässt vertikales Scrollen über pan-y unangetastet.',
      reducedMotionNotes: 'Statische Kante mit fixem Licht und lesbarer Tiefe; kein rAF.',
      description: 'Border-Trace mit echter Tiefe: laufendes Kantenlicht, versetzte Glow-Kopie und gekoppelter Innenreflex. Runtime pausiert offscreen, Inputs sind defensiv begrenzt und Glow/Interaktionsstärke sind separat steuerbar.',
      importPath: '@/motion-arsenal/effects/cards/BorderTraceDepth',
      usageJsx: '<BorderTraceDepth speed={1} color="#d4a24a" glowStrength={1} interactiveBoost={1} />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0, max: 4, step: 0.1 },
        { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' },
        { key: 'thickness', label: 'Thickness', type: 'range', default: 2, min: 0.5, max: 8, step: 0.5 },
        { key: 'depthOffset', label: 'Depth', type: 'range', default: 1, min: 0, max: 2.5, step: 0.1 },
        { key: 'glowStrength', label: 'Glow', type: 'range', default: 1, min: 0, max: 2, step: 0.05 },
        { key: 'interactiveBoost', label: 'Hover Boost', type: 'range', default: 1, min: 0, max: 2, step: 0.05 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./BorderTraceDepth')),
  },
  {
    meta: {
      id: 'cards-hover-light-refraction',
      name: 'HoverLightRefraction',
      category: 'cards',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (Velocity-Denken: Effektstärke ∝ Pointer-Geschwindigkeit)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Produkt-/Portfolio-Karten', 'Premium-Grids'],
      performanceNotes: 'Zwei Gradient-Kopien + Transforms — günstig.',
      mobileNotes: 'Touch: Auto-Highlight-Wanderung.',
      reducedMotionNotes: 'Statisches Highlight mittig.',
      description: 'Pointer-abhängige Glas-Refraktion: das Specular-Highlight wandert gegenläufig zum Pointer, ein chromatischer Kanten-Saum (rot/cyan versetzt) wächst mit der Pointer-Velocity.',
      importPath: '@/motion-arsenal/effects/cards/HoverLightRefraction',
      usageJsx: '<HoverLightRefraction refraction={0.6} chroma={1} />',
      props: [
        { key: 'refraction', label: 'Refraction', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
        { key: 'chroma', label: 'Chroma', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'highlightSize', label: 'Highlight px', type: 'range', default: 160, min: 80, max: 280, step: 10 },
        { key: 'tint', label: 'Tint', type: 'color', default: '#d4a24a' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./HoverLightRefraction')),
  },
  {
    meta: {
      id: 'cards-tilt-parallax',
      name: 'TiltParallaxCard',
      category: 'cards',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (damp λ≈12 Pointer-Follow)', 'KRANK/src/index.css (Overshoot-Settle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Rank-/Membercards', 'Showcase-Kacheln', 'NFT-/Sammelkarten-Feel'],
      performanceNotes: 'perspective + wenige translateZ-Ebenen — günstig.',
      mobileNotes: 'Touch: sanfte Auto-Rotation.',
      reducedMotionNotes: 'Karte flach, Ebenen statisch versetzt.',
      description: '3D-Tilt mit inneren Parallax-Ebenen: Badge, Typo, Zahl und Glow schweben auf translateZ-Stufen, ein Glanz-Sweep läuft mit dem Tilt-Winkel, das Settle federt mit KRANK-Overshoot.',
      importPath: '@/motion-arsenal/effects/cards/TiltParallaxCard',
      usageJsx: '<TiltParallaxCard maxTilt={12} depth={1} glare={0.7} />',
      props: [
        { key: 'maxTilt', label: 'Tilt °', type: 'range', default: 12, min: 4, max: 24, step: 1 },
        { key: 'depth', label: 'Depth', type: 'range', default: 1, min: 0, max: 2, step: 0.1 },
        { key: 'glare', label: 'Glare', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'overshoot', label: 'Overshoot', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TiltParallaxCard')),
  },
  {
    meta: {
      id: 'cards-lock-unlock-scan',
      name: 'LockUnlockScan',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Filter-Chain saturate/brightness via Var)', 'stroke-dash Border-Trace'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Gating (Black Forge!)', 'Premium-Feature-Locks', 'Fortschritts-Freischaltungen'],
      performanceNotes: 'Scanline/Noise existieren nur locked + in-view; Unlock ist eine einmalige Sequenz und Relock-Timer werden sauber aufgeräumt.',
      mobileNotes: 'Native Button-Interaktion: Tap/Keyboard = Unlock; keine Scroll-Blockade.',
      reducedMotionNotes: 'Direkt lesbarer entsperrter Zustand ohne Sequenz oder Timer-Autorelock.',
      description: 'Gating-Karte mit zugänglichem Button-State: Locked-Scan + Noise, einmalige Unlock-Sequenz, eindeutige SVG-IDs, sauberem Timer-Lifecycle und konfigurierbarer Relock-Dauer.',
      importPath: '@/motion-arsenal/effects/cards/LockUnlockScan',
      usageJsx: '<LockUnlockScan accent="#d4a24a" relockDelay={4500} />',
      props: [
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'scanSpeed', label: 'Scan Speed', type: 'range', default: 1, min: 0.2, max: 4, step: 0.1 },
        { key: 'autoRelock', label: 'Auto-Relock', type: 'boolean', default: true },
        { key: 'relockDelay', label: 'Relock ms', type: 'range', default: 4500, min: 800, max: 20000, step: 200 },
        { key: 'defaultUnlocked', label: 'Default Unlocked', type: 'boolean', default: false },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./LockUnlockScan')),
  },
  {
    meta: {
      id: 'cards-fold-notch-panel',
      name: 'FoldNotchPanel',
      category: 'cards',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Easing)', 'NOX forge-cut Notch-Ästhetik'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Info-Panels', 'Sequenzielle Content-Enthüllung', 'NOX-System-Module'],
      performanceNotes: 'Ein rotateX-Transform + Schatten — sehr günstig.',
      mobileNotes: 'Auto-Zyklus, touch-tauglich.',
      reducedMotionNotes: 'Panel offen, statisch.',
      description: 'Panel mit clip-path-Notch klappt physisch aus der Oberkante auf (rotateX + Overshoot), der Bodenschatten folgt dem Klappwinkel, die Signal-LED sichert die geschnittene Ecke.',
      importPath: '@/motion-arsenal/effects/cards/FoldNotchPanel',
      usageJsx: '<FoldNotchPanel notchSize={22} accent="#C93030" />',
      props: [
        { key: 'notchSize', label: 'Notch px', type: 'range', default: 22, min: 10, max: 40, step: 2 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.3, max: 2, step: 0.1 },
        { key: 'autoCycle', label: 'Auto-Cycle', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./FoldNotchPanel')),
  },
];
