import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const OVERLAYS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'overlays-modal-iris-reveal',
      name: 'ModalIrisReveal',
      category: 'overlays',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (View-Transition-Morph-Ästhetik)', 'KRANK/src/index.css (stroke-dash Border-Trace)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Detail-Dialoge', 'Unlock-/Bestätigungs-Momente'],
      performanceNotes: 'clip-path circle + eine SVG-Trace — günstig.',
      mobileNotes: 'Mobiletauglich; Iris-Ursprung = Touch-Punkt.',
      reducedMotionNotes: 'Modal erscheint ohne Iris/Trace, direkt offen.',
      description: 'Modal öffnet als Iris vom Klickpunkt (clip-path circle wächst), Backdrop blurt choreografiert ein, ein Border-Trace umläuft das Panel nach dem Andocken, Content staggert. ESC/Backdrop schließt.',
      importPath: '@/motion-arsenal/effects/overlays/ModalIrisReveal',
      usageJsx: '<ModalIrisReveal accent="#C93030" blurBackdrop={8} />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'blurBackdrop', label: 'Backdrop Blur', type: 'range', default: 8, min: 0, max: 18, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ModalIrisReveal')),
  },
  {
    meta: {
      id: 'overlays-glass-sheet',
      name: 'GlassSheetOverlay',
      category: 'overlays',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['shopify.css (Glass-Nav: rgba + backdrop-filter blur + blend)', 'KRANK/src/index.css (Overshoot-Settle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Mobile Bottom-Sheets', 'Settings-/Info-Panels', 'Filter-Drawer'],
      performanceNotes: 'backdrop-filter ist die Hauptlast — Fläche klein halten, blur ≤ 16px.',
      mobileNotes: 'Bottom-Sheet ist das native Mobile-Pattern; Drag-Indikator atmet.',
      reducedMotionNotes: 'Sheet erscheint ohne Feder-Einlauf.',
      description: 'Bottom-/Side-Sheet aus geschichtetem Glas: backdrop-blur, Innen-Gradient, Licht-Refraktionskante oben und Noise — federnder outBack-Einlauf, atmender Drag-Indikator, choreografierter Backdrop.',
      importPath: '@/motion-arsenal/effects/overlays/GlassSheetOverlay',
      usageJsx: "<GlassSheetOverlay side=\"bottom\" blur={14} />",
      props: [
        { key: 'side', label: 'Side', type: 'select', default: 'bottom', options: ['bottom', 'right'] },
        { key: 'blur', label: 'Blur', type: 'range', default: 14, min: 4, max: 24, step: 1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GlassSheetOverlay')),
  },
  {
    meta: {
      id: 'overlays-toast-stack-slide',
      name: 'ToastStackSlide',
      displayName: 'Toast Stack Slide',
      category: 'overlays',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Overlays DNA', 'Stacked-Toast-Muster'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Statusmeldungen in Anwendungen und Dashboards', 'Bestaetigungen nach Formularaktionen', 'Fehler- und Systemhinweise ohne Modal'],
      performanceNotes: 'JS haelt nur den Stapelzustand, die Bewegung liegt in CSS-Transitions - kein rAF. Der Fortschrittsbalken ist eine scaleX-Animation mit der Lebensdauer als Dauer, laeuft also ohne Timer-Ticks.',
      mobileNotes: 'Stapelbreite skaliert prozentual, Schliessen-Button mit ausreichendem Touch-Target.',
      reducedMotionNotes: 'Meldungen erscheinen und verschwinden ohne Slide; Fortschritt und Lebensdauer bleiben unveraendert.',
      description: 'Benachrichtigungen fahren seitlich ein und schieben die aelteren per Perspektive in die Tiefe. Der Stapel ist eine aria-live-Region, neue Meldungen werden also vorgelesen, ohne den Fokus zu stehlen.',
      importPath: '@/motion-arsenal/effects/overlays/ToastStackSlide',
      usageJsx: '<ToastStackSlide position="top-right" duration={4200} maxStack={4} />',
      props: [
        { key: 'position', label: 'Position', type: 'select', default: 'top-right', options: ['top-right', 'top-left', 'bottom-right'], group: 'Layout' },
        { key: 'maxStack', label: 'Max Stack', type: 'range', default: 4, min: 1, max: 6, step: 1, group: 'Layout' },
        { key: 'variant', label: 'Typ', type: 'select', default: 'success', options: ['success', 'error', 'info'], group: 'Content' },
        { key: 'duration', label: 'Lebensdauer ms', type: 'range', default: 4200, min: 1500, max: 10000, step: 100, group: 'Motion' },
        { key: 'showProgress', label: 'Fortschritt', type: 'boolean', default: true, group: 'Motion' },
        { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ToastStackSlide')),
  },
  { meta: { id: 'modal-cinema-letterbox', name: 'CinemaLetterboxModal', displayName: 'Cinema Letterbox Modal', category: 'overlays', sourceWebsite: 'codrops', sourceFiles: ['letterbox-theater-modal'], mode: 'nox-original', complexity: 'medium', dependencies: [], bestFor: ['Video-Showcases', 'Galerie-Highlights'], performanceNotes: 'Overlay nur bei Oeffnen montiert; transform/opacity.', mobileNotes: 'Touch- und Escape-Schliessen.', reducedMotionNotes: 'Direkter Dialog.', description: 'Kinomoment mit Letterbox-Balken und Gold-Rahmen.', importPath: '@/motion-arsenal/effects/overlays/CinemaLetterboxModal', usageJsx: '<CinemaLetterboxModal />', props: [{ key: 'duration', label: 'Dauer', type: 'range', default: .7, min: .3, max: 1.5, step: .1 }, { key: 'blur', label: 'Blur', type: 'range', default: 8, min: 0, max: 18, step: 1 }, { key: 'color', label: 'Rahmen', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./CinemaLetterboxModal')) },
  { meta: { id: 'overlays-dynamic-tooltip-fragments', name: 'DynamicTooltipFragments', displayName: 'Dynamic Tooltip Fragments', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['NOX tooltip fragment reveal'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Metadata Hints', 'Dense Interfaces'], performanceNotes: 'Small opacity and transform panel transition.', mobileNotes: 'Focus and tap-friendly trigger.', reducedMotionNotes: 'Tooltip appears without entrance.', description: 'A compact tooltip assembles from staggered gold fragments around a trigger.', importPath: '@/motion-arsenal/effects/overlays/DynamicTooltipFragments', usageJsx: '<DynamicTooltipFragments detail="Signal path / 04" />', props: [{ key: 'label', label: 'Label', type: 'text', default: 'INSPECT' }, { key: 'detail', label: 'Detail', type: 'text', default: 'Signal path / 04' }, { key: 'fragments', label: 'Fragments', type: 'range', default: 6, min: 3, max: 10, step: 1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./DynamicTooltipFragments')) },
  { meta: { id: 'overlays-radial-context-menu', name: 'RadialContextMenu', displayName: 'Radial Context Menu', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-radial-context-menu'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Context Menus'], performanceNotes: 'One-shot transforms per menu item.', mobileNotes: 'Context event and buttons work on touch.', reducedMotionNotes: 'Items appear immediately.', description: 'A pointer-anchored radial gold context menu.', importPath: '@/motion-arsenal/effects/overlays/RadialContextMenu', usageJsx: '<RadialContextMenu />', props: [], productionSafe: true }, Component: lazy(() => import('./RadialContextMenu')) },
  { meta: { id: 'overlays-sheet-drawer-slide', name: 'SheetDrawerSlide', displayName: 'Sheet Drawer Slide', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-sheet-drawer-slide'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Drawers'], performanceNotes: 'Transform/opacity sheet entrance.', mobileNotes: 'Backdrop dismiss works by tap.', reducedMotionNotes: 'Sheet appears without motion.', description: 'A spring-like bottom sheet with a gold grab handle.', importPath: '@/motion-arsenal/effects/overlays/SheetDrawerSlide', usageJsx: '<SheetDrawerSlide />', props: [], productionSafe: true }, Component: lazy(() => import('./SheetDrawerSlide')) },
  { meta: { id: 'overlays-typewriter-command-palette', name: 'TypewriterCommandPalette', displayName: 'Typewriter Command Palette', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Typewriter Command Palette.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Command Menus', 'Product UI'], performanceNotes: 'Kein rAF; Re-Render nur bei Query-Änderung.', mobileNotes: 'Max 6 Treffer, scrollbar.', reducedMotionNotes: 'Ohne Stagger, aber funktional.', description: 'Cmd+K-Palette im Terminal-Look: Monospace-Eingabe, gestaffelte Vorschläge (det-PRNG), Fuzzy-Score, Gold-Highlight.', importPath: '@/motion-arsenal/effects/overlays/TypewriterCommandPalette', usageJsx: '<TypewriterCommandPalette open={true} />', props: [{ key: 'open', label: 'Sichtbar', type: 'boolean', default: false }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./TypewriterCommandPalette')) },
  { meta: { id: 'overlays-peel-reveal-modal', name: 'PeelRevealModal', displayName: 'Peel Reveal Modal', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Feature Teasers', 'Gated Content'], performanceNotes: 'Nur transform/opacity; Modal nur bei open gemountet.', mobileNotes: 'Touch auf Curl schliesst.', reducedMotionNotes: 'Modal erscheint direkt ohne Curl.', description: 'Eine aufrollende Gold-Ecke (Gradient-Curl) enthuellt einen Dialog.', importPath: '@/motion-arsenal/effects/overlays/PeelRevealModal', usageJsx: '<PeelRevealModal open={true} title="CLASSIFIED" />', props: [{ key: "peelSize", label: "Ecke", type: "range", default: 44, min: 24, max: 80, step: 2 }], productionSafe: true }, Component: lazy(() => import('./PeelRevealModal')) },
  { meta: { id: 'overlays-strikethrough-explain-modal', name: 'StrikethroughExplainModal', displayName: 'Strikethrough Explain Modal', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Quiz UI', 'Learn Dashboards'], performanceNotes: 'Nur transform/opacity; Phasen via State + Timeout.', mobileNotes: 'Touch: keine speziellen Gesten.', reducedMotionNotes: 'Durchstreichung erscheint direkt.', description: 'Erklaer-Modal: falsche Antwort wird mit Gold-Strich durchgestrichen, dann klappt die Erklaerung auf.', importPath: '@/motion-arsenal/effects/overlays/StrikethroughExplainModal', usageJsx: '<StrikethroughExplainModal open={true} />', props: [{ key: "wrongAnswer", label: "Falsch", type: "text", default: "42" }, { key: "explanation", label: "Erklaerung", type: "text", default: "The answer is actually 43." }, { key: "duration", label: "Dauer", type: "range", default: 0.7, min: 0.3, max: 1.2, step: 0.1 }], productionSafe: true }, Component: lazy(() => import('./StrikethroughExplainModal')) },
  { meta: { id: 'overlays-backdrop-blur-grain', name: 'BackdropBlurGrainOverlay', displayName: 'Backdrop Blur Grain', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Modals', 'Fullscreen Sections'], performanceNotes: 'Statisch: kein rAF, kein Per-Frame-Write.', mobileNotes: 'Touch: kein Eingriff noetig.', reducedMotionNotes: 'Identisch (statisch).', description: 'Material-Overlay aus Backdrop Blur, statischem SVG-Grain (feTurbulence data-URI) und Goldkante.', importPath: '@/motion-arsenal/effects/overlays/BackdropBlurGrainOverlay', usageJsx: '<BackdropBlurGrainOverlay />', props: [{ key: "blur", label: "Blur", type: "range", default: 8, min: 2, max: 20, step: 1 }, { key: "grain", label: "Grain", type: "range", default: 0.5, min: 0, max: 1, step: 0.05 }, { key: "goldEdge", label: "Goldkante", type: "boolean", default: true }], productionSafe: true }, Component: lazy(() => import('./BackdropBlurGrainOverlay')) },
];
// Batch-6 catalog entries are appended by the batch registration pass.
export const BATCH6_OVERLAYS_CATALOG = [{ meta: { id: 'overlays-cinema-letterbox-modal', name: 'CinemaLetterboxModal', displayName: 'Cinema Letterbox Modal', category: 'overlays', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-cinema-letterbox-modal'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Filmische Medien'], performanceNotes: 'Transform und Opacity.', mobileNotes: 'Responsive Letterbox.', reducedMotionNotes: 'Direkter Dialog.', description: 'Kinomoment mit Letterbox-Balken und Goldrahmen.', importPath: '@/motion-arsenal/effects/overlays/CinemaLetterboxModal', usageJsx: '<CinemaLetterboxModal />', props: [{ key: 'title', label: 'Title', type: 'text', default: 'NIGHT SIGNAL / 01' }, { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./CinemaLetterboxModal')) }
];
