import { useState, type CSSProperties } from 'react';
export interface DynamicTooltipFragmentsProps { label?: string; detail?: string; fragments?: number; color?: string; }
export default function DynamicTooltipFragments({ label = 'INSPECT', detail = 'Signal path / 04', fragments = 6, color = '#d4a24a' }: DynamicTooltipFragmentsProps) {
  const [open, setOpen] = useState(false); const parts = Array.from({ length: Math.max(3, Math.min(10, fragments)) });
  return <span className="nox-tooltip-fragments" onPointerEnter={() => setOpen(true)} onPointerLeave={() => setOpen(false)} onFocus={() => setOpen(true)} onBlur={() => setOpen(false)} style={{ '--tip-color': color } as CSSProperties}>
    <button aria-describedby="nox-tip-copy">{label}</button><span className={`nox-tooltip-fragments__panel ${open ? 'is-open' : ''}`} id="nox-tip-copy"><strong>{detail}</strong><span className="nox-tooltip-fragments__pieces">{parts.map((_, i) => <i key={i} style={{ '--i': i } as CSSProperties} />)}</span></span>
    <style>{`.nox-tooltip-fragments{position:relative;display:inline-block}.nox-tooltip-fragments button{padding:12px 16px;border:1px solid var(--tip-color);background:#0b0907;color:var(--tip-color);font:700 .7rem ui-monospace;letter-spacing:.14em;cursor:pointer}.nox-tooltip-fragments__panel{position:absolute;z-index:3;bottom:calc(100% + 14px);left:50%;width:190px;padding:15px;background:#12100d;border:1px solid var(--tip-color);box-shadow:0 10px 30px #0008;opacity:0;pointer-events:none;transform:translate(-50%,8px) rotateX(-18deg);transform-origin:bottom;transition:opacity .2s,transform .35s cubic-bezier(.2,1.4,.3,1)}.nox-tooltip-fragments__panel.is-open{opacity:1;transform:translate(-50%,0) rotateX(0)}.nox-tooltip-fragments__panel strong{display:block;color:#f7e8a4;font:600 .75rem ui-monospace}.nox-tooltip-fragments__pieces{display:flex;gap:3px;margin-top:12px}.nox-tooltip-fragments__pieces i{display:block;width:calc(100% / var(--count, 6));height:3px;background:var(--tip-color);transform:translateY(calc((var(--i) - 2)*2px));opacity:.65}.nox-tooltip-fragments button:focus-visible{outline:2px solid var(--tip-color);outline-offset:4px}@media(prefers-reduced-motion:reduce){.nox-tooltip-fragments__panel{transition:none;transform:translate(-50%,0)}}`}</style>
  </span>;
}
