import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const BACKGROUNDS_CATALOG: EffectEntry[] = [
  { meta: { id: 'bg-blurry-vhs-image-filter', name: 'BlurryVhsImageFilter', displayName: 'Blurry VHS Image Filter', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['codemyui VHS image filter', 'Vault: nox-blurry-vhs-image-filter'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Galerie-Bilder', 'Retro-Sektionen'], performanceNotes: 'CSS-Filter und Overlay-Layer, kein JS-Loop.', mobileNotes: 'Scanline bleibt als statischer Layer sichtbar.', reducedMotionNotes: 'VHS-Standbild ohne Scanline-Bewegung.', description: 'Blurry VHS-Farbfilter mit RGB-Chroma-Shift und wandernden Scanlines.', importPath: '@/motion-arsenal/effects/backgrounds/BlurryVhsImageFilter', usageJsx: '<BlurryVhsImageFilter src="/image.jpg" />', props: [{ key: 'src', label: 'Image', type: 'text', default: '' }, { key: 'alt', label: 'Alt', type: 'text', default: 'VHS image' }, { key: 'strength', label: 'Strength', type: 'range', default: .5, min: 0, max: 1, step: .1 }, { key: 'scanlines', label: 'Scanlines', type: 'boolean', default: true }, { key: 'chroma', label: 'Chroma', type: 'range', default: .3, min: 0, max: 1, step: .1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true, status: 'production-safe' }, Component: lazy(() => import('./BlurryVhsImageFilter')) },
  { meta: { id: 'bg-aurora-beam-drift', name: 'AuroraBeamDrift', displayName: 'Aurora Beam Drift', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['magic-ui-aurora', 'Vault: nox-aurora-beam-drift'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Hero- und CTA-Hintergründe'], performanceNotes: 'CSS-Transform-Animationen mit begrenzter Blur-Layerzahl.', mobileNotes: 'Dekorative Layer reduzieren sich per CSS.', reducedMotionNotes: 'Beams bleiben statisch sichtbar.', description: 'Konische Gold- und Bernstein-Beams driften weich durch einen dunklen Atmosphärenraum.', importPath: '@/motion-arsenal/effects/backgrounds/AuroraBeamDrift', usageJsx: '<AuroraBeamDrift beams={3} />', props: [{ key: 'beams', label: 'Beams', type: 'range', default: 3, min: 2, max: 6, step: 1 }, { key: 'speed', label: 'Speed', type: 'range', default: 1, min: .1, max: 3, step: .1 }, { key: 'saturation', label: 'Saturation', type: 'range', default: .5, min: 0, max: 1, step: .1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true, status: 'production-safe', fullBleed: true }, Component: lazy(() => import('./AuroraBeamDrift')) },
  {
    meta: {
      id: 'scroll-cosmic-depth-field',
      name: 'NoxCosmicDepthField',
      displayName: 'Cosmic Depth Field',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: [
        'noxlabs-site: CosmicStage (3D-Sterne, Zentralprojektion, Tier-Budget)',
        'NoxCosmicDepthField.tsx (Tiefenschichten, Fokusebene, Bokeh-Sprites)',
      ],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['durchgehende Seitenhintergründe', 'Premium-Dark-Sections', 'Hero → Content-Übergänge'],
      performanceNotes:
        'Ein Canvas2D-Loop mit vorgerenderten Sprite-Atlanten (7 Softness-Stufen) statt createRadialGradient pro Stern pro Frame; Tiefenunschärfe entsteht über die Sprite-Wahl, nicht über einen Canvas-Filter. Offscreen pausiert der Loop über IntersectionObserver, DPR ist auf 2 begrenzt (mobil konfigurierbar).',
      mobileNotes:
        'Eigene Mobile-Regler ab 700px Boxbreite: mobileStarCount (Anteil wird auf Sterne UND Staub angewandt), mobileScrollSpeed, mobileBloom und mobileDpr. Kein Pointer-Input, kein horizontaler Overflow — der Effekt liegt absolut in seiner Box.',
      reducedMotionNotes:
        'Ein einziges statisches Bild: kein Scroll-Parallax, kein Twinkle, keine Trails, kein rAF-Loop. Bloom, Tiefenunschärfe und Vignette bleiben als statische Bildwirkung erhalten.',
      description:
        'Ruhiger kosmischer Tiefenraum: geschichtete Sterne mit echter Fokusebene, weicher Tiefenunschärfe, dezentem Bloom und einer Bewegung, die ausschließlich am Scrollfortschritt hängt. Bewusst kein Screensaver — foregroundStarRatio und foregroundMaxSize deckeln große helle Vordergrundpunkte, trailLength bleibt niedrig, damit nichts durchs Bild schießt. Abgrenzung zu bg-nox-starfield-drift: dort ist die Warp-/Streak-Mechanik für Sektionsübergänge der Kern, hier Tiefe und Ruhe.',
      currentUsage: [],
      technicalBasis:
        'Canvas2D, deterministische 3D-Sternkoordinaten (seeded), Layer-Quantisierung der Tiefe, Fokusabstand → Sprite-Softness, additiver Halo-Pass, Rückfaltung der Position in ein Band für konstante Dichte.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoxCosmicDepthField',
      usageJsx:
        '<NoxCosmicDepthField starCount={520} foregroundStarRatio={0.04} scrollParallax={0.18} scrollSmoothing={0.82} bloom={0.28} depthBlur={0.35} bokehStrength={0.15} trailLength={0.08} />',
      props: [
        { key: 'starCount', label: 'Star Count', type: 'range', default: 520, min: 60, max: 1400, step: 20, group: 'Density' },
        { key: 'dustCount', label: 'Dust Count', type: 'range', default: 140, min: 0, max: 600, step: 10, group: 'Density' },
        { key: 'foregroundStarRatio', label: 'Foreground Ratio', type: 'range', default: 0.04, min: 0, max: 0.3, step: 0.01, group: 'Density' },
        { key: 'mediumStarRatio', label: 'Medium Ratio', type: 'range', default: 0.26, min: 0, max: 1, step: 0.02, group: 'Density' },
        { key: 'backgroundStarRatio', label: 'Background Ratio', type: 'range', default: 0.7, min: 0, max: 1, step: 0.02, group: 'Density' },

        { key: 'minStarSize', label: 'Min Star Size', type: 'range', default: 0.25, min: 0.1, max: 2, step: 0.05, group: 'Size' },
        { key: 'maxStarSize', label: 'Max Star Size', type: 'range', default: 1.15, min: 0.3, max: 4, step: 0.05, group: 'Size' },
        { key: 'foregroundMaxSize', label: 'Foreground Max Size', type: 'range', default: 1.8, min: 0.5, max: 6, step: 0.1, group: 'Size' },
        { key: 'dustSize', label: 'Dust Size', type: 'range', default: 0.55, min: 0.1, max: 2, step: 0.05, group: 'Size' },

        { key: 'depthLayers', label: 'Depth Layers', type: 'range', default: 5, min: 1, max: 12, step: 1, group: 'Depth' },
        { key: 'perspectiveDepth', label: 'Perspective Depth', type: 'range', default: 0.85, min: 0.2, max: 2, step: 0.05, group: 'Depth' },
        { key: 'nearPlane', label: 'Near Plane', type: 'range', default: 0.18, min: 0.05, max: 0.8, step: 0.01, group: 'Depth' },
        { key: 'farPlane', label: 'Far Plane', type: 'range', default: 1, min: 0.3, max: 2, step: 0.05, group: 'Depth' },
        { key: 'depthDistribution', label: 'Depth Distribution', type: 'range', default: 0.62, min: 0, max: 1, step: 0.02, group: 'Depth' },
        { key: 'atmosphericPerspective', label: 'Atmospheric Perspective', type: 'range', default: 0.38, min: 0, max: 1, step: 0.02, group: 'Depth' },

        { key: 'scrollSpeed', label: 'Scroll Speed', type: 'range', default: 0.06, min: 0, max: 0.6, step: 0.01, group: 'Scroll' },
        { key: 'scrollParallax', label: 'Scroll Parallax', type: 'range', default: 0.18, min: 0, max: 1.2, step: 0.02, group: 'Scroll' },
        { key: 'scrollSmoothing', label: 'Scroll Smoothing', type: 'range', default: 0.82, min: 0, max: 0.98, step: 0.02, group: 'Scroll' },
        { key: 'verticalDrift', label: 'Vertical Drift', type: 'range', default: 0.02, min: 0, max: 0.3, step: 0.01, group: 'Scroll' },
        { key: 'horizontalDrift', label: 'Horizontal Drift', type: 'range', default: 0.008, min: 0, max: 0.1, step: 0.002, group: 'Scroll' },
        { key: 'velocityInfluence', label: 'Velocity Influence', type: 'range', default: 0.25, min: 0, max: 1.5, step: 0.05, group: 'Scroll' },

        { key: 'bloom', label: 'Bloom', type: 'range', default: 0.28, min: 0, max: 1.2, step: 0.02, group: 'Glow / Bloom' },
        { key: 'glowRadius', label: 'Glow Radius', type: 'range', default: 1.6, min: 0.2, max: 5, step: 0.1, group: 'Glow / Bloom' },
        { key: 'glowIntensity', label: 'Glow Intensity', type: 'range', default: 0.22, min: 0, max: 1, step: 0.02, group: 'Glow / Bloom' },
        { key: 'coreBrightness', label: 'Core Brightness', type: 'range', default: 1.05, min: 0.2, max: 1.6, step: 0.05, group: 'Glow / Bloom' },
        { key: 'haloOpacity', label: 'Halo Opacity', type: 'range', default: 0.4, min: 0, max: 1, step: 0.02, group: 'Glow / Bloom' },

        { key: 'depthBlur', label: 'Depth Blur', type: 'range', default: 0.35, min: 0, max: 1.5, step: 0.05, group: 'Blur / Bokeh' },
        { key: 'backgroundBlur', label: 'Background Blur', type: 'range', default: 0.8, min: 0, max: 2.5, step: 0.05, group: 'Blur / Bokeh' },
        { key: 'foregroundBlur', label: 'Foreground Blur', type: 'range', default: 0.6, min: 0, max: 2.5, step: 0.05, group: 'Blur / Bokeh' },
        { key: 'bokehStrength', label: 'Bokeh Strength', type: 'range', default: 0.15, min: 0, max: 1, step: 0.01, group: 'Blur / Bokeh' },
        { key: 'focusDepth', label: 'Focus Depth', type: 'range', default: 0.55, min: 0, max: 1, step: 0.02, group: 'Blur / Bokeh' },

        { key: 'trailLength', label: 'Trail Length', type: 'range', default: 0.08, min: 0, max: 1, step: 0.01, group: 'Trails' },
        { key: 'trailOpacity', label: 'Trail Opacity', type: 'range', default: 0.35, min: 0, max: 1, step: 0.02, group: 'Trails' },
        { key: 'motionBlur', label: 'Motion Blur', type: 'range', default: 0.2, min: 0, max: 0.9, step: 0.02, group: 'Trails' },
        { key: 'smear', label: 'Smear', type: 'range', default: 0.12, min: 0, max: 0.9, step: 0.02, group: 'Trails' },

        { key: 'starOpacity', label: 'Star Opacity', type: 'range', default: 1, min: 0.1, max: 1.4, step: 0.02, group: 'Visual' },
        { key: 'dustOpacity', label: 'Dust Opacity', type: 'range', default: 0.28, min: 0, max: 1, step: 0.02, group: 'Visual' },
        { key: 'twinkle', label: 'Twinkle', type: 'range', default: 0.08, min: 0, max: 0.6, step: 0.01, group: 'Visual' },
        { key: 'colorTemperature', label: 'Color Temperature', type: 'range', default: 0.35, min: 0, max: 1, step: 0.02, group: 'Visual' },
        { key: 'vignette', label: 'Vignette', type: 'range', default: 0.25, min: 0, max: 1, step: 0.02, group: 'Visual' },
        { key: 'nebulaOpacity', label: 'Nebula Opacity', type: 'range', default: 0.16, min: 0, max: 0.8, step: 0.02, group: 'Visual' },

        { key: 'mobileStarCount', label: 'Mobile Star Count', type: 'range', default: 220, min: 30, max: 800, step: 10, group: 'Mobile' },
        { key: 'mobileScrollSpeed', label: 'Mobile Scroll Speed', type: 'range', default: 0.04, min: 0, max: 0.4, step: 0.01, group: 'Mobile' },
        { key: 'mobileBloom', label: 'Mobile Bloom', type: 'range', default: 0.18, min: 0, max: 1, step: 0.02, group: 'Mobile' },
        { key: 'mobileDpr', label: 'Mobile DPR', type: 'range', default: 1.5, min: 1, max: 2, step: 0.1, group: 'Mobile' },

        { key: 'seed', label: 'Seed', type: 'range', default: 20260731, min: 1, max: 99999999, step: 1, group: 'Mobile' },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxCosmicDepthField')),
  },
  {
    meta: {
      id: 'bg-nox-starfield-drift',
      name: 'NoxStarfieldDrift',
      displayName: 'NOX Starfield Drift',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: [
        'noxlabs-site-work/src/components/cosmic/CosmicStage.tsx (3D-Sterne, Zentralprojektion, DPR-/Viewport-Tiers)',
        'noxlabs-site-work/src/lib/journey.ts (Scroll-gekoppelte Live-Dramaturgie; im ruhigen Preset bewusst entkoppelt)',
      ],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Premium-Sci-Fi-Sections', 'Journey-Bereiche', 'Hero-/CTA-Flächen mit Text-Overlay'],
      performanceNotes:
        'Ein Canvas2D-Loop, O(n), DPR im gemeinsamen Canvas-Hook auf 2 begrenzt. Das Preset deckelt automatisch auf 320 Sterne unter 560 px und 440 Sterne unter 900 px; Hintergrund-Tabs pausieren.',
      mobileNotes:
        'Mobil automatisch reduzierte Sternzahl, keine Pointer-Abhängigkeit und keine Warp-Streaks. Die dunkle Text-Safe-Zone bleibt in allen Größen erhalten.',
      reducedMotionNotes:
        'Ein statischer, deterministischer Sternenhimmel wird einmal gerendert; Drift und Twinkle laufen nicht.',
      description:
        'Subtiler kosmischer Hintergrund mit sanft bewegten Sternen für Premium-Sci-Fi-Sections und Journey-Bereiche. Ruhige Standardfassung des NOX-CosmicStage-Sternenfelds: keine aggressiven Warp-Streaks, keine hektische Vorwärtsbewegung und eine abgedunkelte Mitte für gut lesbare Text-Overlays.',
      currentUsage: [
        'NOX-Startseite: fixer CosmicStage-Hintergrund hinter der durchgehenden Scroll-Journey',
        'Journey-Phasen vom Mondaufbruch bis zum Event-Horizon-CTA',
      ],
      technicalBasis:
        'Canvas2D mit deterministischen 3D-Sternkoordinaten, Zentralprojektion, z-Recycling und eigener requestAnimationFrame-Logik über den Arsenal-Canvas-Hook; kein CSS-/GSAP-/WebGL-Effekt.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoxStarfieldDrift',
      usageJsx:
        '<NoxStarfieldDrift starCount={520} driftSpeed={0.055} intensity={0.62} depth={0.72} twinkle={0.12} textSafety={0.68} />',
      props: [
        { key: 'starCount', label: 'Stars', type: 'range', default: 520, min: 120, max: 1000, step: 20 },
        { key: 'driftSpeed', label: 'Drift Speed', type: 'range', default: 0.055, min: 0, max: 0.18, step: 0.005 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.62, min: 0.2, max: 1, step: 0.02 },
        { key: 'depth', label: 'Depth', type: 'range', default: 0.72, min: 0.35, max: 1, step: 0.02 },
        { key: 'twinkle', label: 'Twinkle', type: 'range', default: 0.12, min: 0, max: 0.35, step: 0.01 },
        { key: 'textSafety', label: 'Text Safety', type: 'range', default: 0.68, min: 0, max: 1, step: 0.02 },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxStarfieldDrift')),
  },
  {
    meta: {
      id: 'bg-nox-scribble-field',
      name: 'NoxAdaptedScribbleField',
      category: 'backgrounds',
      sourceWebsite: 'oryzo-screenshot',
      sourceFiles: ['ORYZO-Referenz (Farb-/Layer-Klasse)', 'KRANK/src/hoisted.js (Layering: eine Physik-Quelle)', 'KRANK/src/index.css (stroke-dash Draw-Mechanik)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Hero', 'Premium-Landingpage-Hintergrund', 'Section-Atmosphäre hinter Typo'],
      performanceNotes: 'SVG-Blur auf bis zu 14 Layern — Density auf schwacher Hardware senken. Kein Canvas, kein WebGL.',
      mobileNotes: 'Density ≤ 6 empfohlen; Parallax entfällt ohne Pointer (bleibt ruhig-statisch).',
      reducedMotionNotes: 'Drift/Draw aus, statisches Scribble-Feld mit Glow bleibt.',
      description:
        'NOX-Produktionsvariante der ORYZO-Klasse: prozedurale Ember-/Gold-Scribbles mit Blur-Glow-Kopie, mix-blend-screen, organischem Drift, stroke-dash Draw-on — plus echte Pointer-Proximity-Energie: jedes Scribble färbt sich, glüht, verdickt und driftet, wenn der Pointer nah ist, und glimmt danach langsam ab. Symbolset via Registry austauschbar.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoxAdaptedScribbleField',
      usageJsx: "<NoxAdaptedScribbleField colorMode=\"nox\" intensity={0.8} density={7} parallax={0.5} proximityRadius={200} />",
      props: [
        { key: 'colorMode', label: 'Color Mode', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.8, min: 0.2, max: 1, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'density', label: 'Density', type: 'range', default: 7, min: 3, max: 14, step: 1 },
        { key: 'blur', label: 'Blur', type: 'range', default: 14, min: 4, max: 30, step: 1 },
        { key: 'rotation', label: 'Rotation', type: 'range', default: 16, min: 0, max: 45, step: 1 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'proximityRadius', label: 'Proximity Radius', type: 'range', default: 200, min: 60, max: 360, step: 10 },
        { key: 'blendMode', label: 'Blend', type: 'select', default: 'screen', options: ['screen', 'lighten', 'plus-lighter', 'normal'] },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxAdaptedScribbleField')),
  },
  {
  meta: {
    id: 'bg-forge-energy-glyphs',
    name: 'ForgeEnergyGlyphs',
    displayName: 'NOX Forge Energy Glyph System',
    category: 'backgrounds',
    sourceWebsite: 'nox-original',
    sourceFiles: [
      'ForgeEnergyGlyphs.tsx (five semantic glyph families + six operating states)',
      'public/agent-manifests/forge-energy-glyphs-variants.json',
      'Generated NOX glyph reference sheets used as visual direction; final runtime artwork is deterministic SVG.',
    ],
    mode: 'nox-adapted',
    complexity: 'high',
    dependencies: [],
    bestFor: ['NOX Forge', 'Project-X command center', 'Global Sales OS', 'Automation products', 'AI Growth sections'],
    performanceNotes: 'Deterministic SVG field with 8–30 glyphs, lightweight connectors and CSS-composited dust. Hero glows are the main paint cost; keep 12–20 glyphs on mobile.',
    mobileNotes: 'Ambient glyphs are reduced automatically; switchers scroll horizontally and pointer interaction gracefully falls back to ambient/scroll energy.',
    reducedMotionNotes: 'Float, rotation, pulses, noise and heat shimmer stop; the selected semantic field remains fully visible and readable.',
    description:
      'A reusable NOX signature background rather than a random rune field: five semantic symbol families, six operating states, ambient/active/hero depth layers, pointer or scroll ignition, flowing connector pulses, charge rings, heat shimmer and stable agent references.',
    currentUsage: ['NOX product heroes', 'Agent command surfaces', 'Forge progression scenes', 'Customer system presentations'],
    technicalBasis: 'React + deterministic SVG path registry + proximity field + CSS compositing. No WebGL, no runtime network requests, no new dependency.',
    importPath: '@/motion-arsenal/effects/backgrounds/ForgeEnergyGlyphs',
    usageJsx: '<ForgeEnergyGlyphs variant="forge-ember-runes" stateMode="charged" showVariantSwitcher />',
    props: [
      {
        key: 'variant',
        label: 'Glyph Family',
        type: 'select',
        default: 'forge-ember-runes',
        options: ['forge-ember-runes', 'command-nexus-sigils', 'revenue-ascension-seals', 'automation-circuit-glyphs', 'signal-growth-constellations'],
        group: 'Content',
      },
      {
        key: 'stateMode',
        label: 'System State',
        type: 'select',
        default: 'charged',
        options: ['idle', 'warming', 'charged', 'overdrive', 'ritual', 'stealth'],
        group: 'Content',
      },
      { key: 'glyphCount', label: 'Glyphs', type: 'range', default: 18, min: 8, max: 30, step: 1, group: 'Field' },
      { key: 'density', label: 'Density', type: 'range', default: 1, min: 0.5, max: 1.5, step: 0.05, group: 'Field' },
      { key: 'glowStrength', label: 'Glow', type: 'range', default: 1, min: 0.2, max: 1.5, step: 0.05, group: 'Energy' },
      { key: 'energyLevel', label: 'Energy', type: 'range', default: 1, min: 0.2, max: 1.5, step: 0.05, group: 'Energy' },
      { key: 'floatSpeed', label: 'Float Speed', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1, group: 'Motion' },
      { key: 'rotationSpeed', label: 'Rotation', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1, group: 'Motion' },
      { key: 'rareGlyphChance', label: 'Hero Glyphs', type: 'range', default: 0.18, min: 0.05, max: 0.45, step: 0.01, group: 'Field' },
      { key: 'heatDistortion', label: 'Heat Shimmer', type: 'range', default: 0.55, min: 0, max: 1, step: 0.05, group: 'Energy' },
      {
        key: 'interactionMode',
        label: 'Interaction',
        type: 'select',
        default: 'hybrid',
        options: ['none', 'pointer', 'scroll', 'hybrid'],
        group: 'Interaction',
      },
      { key: 'proximityRadius', label: 'Ignite Radius', type: 'range', default: 190, min: 80, max: 360, step: 10, group: 'Interaction' },
      { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Interaction' },
      { key: 'showVariantSwitcher', label: 'Variant Switcher', type: 'boolean', default: true, group: 'Content' },
      { key: 'showStateSwitcher', label: 'State Switcher', type: 'boolean', default: true, group: 'Content' },
    ],
    productionSafe: true,
    status: 'production-safe',
    fullBleed: true,
  },
  Component: lazy(() => import('./ForgeEnergyGlyphs')),
},
  {
    meta: {
      id: 'bg-orbital-light-trails',
      name: 'OrbitalLightTrails',
      category: 'backgrounds',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (Trail-History-Buffer + Decay/Taper, framerateNormalizeLerpAlpha, blendFunc(ONE,ONE))'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Hero-Atmosphäre', 'Loader-/Warte-Screens', 'Agent-Interface-Hintergrund'],
      performanceNotes: 'Canvas2D Line-Strips — sehr günstig. trailLength ≤ 120.',
      mobileNotes: 'Voll touch-tauglich (autonome Orbits, kein Pointer nötig).',
      reducedMotionNotes: 'Loop pausiert, letzter Frame bleibt.',
      description:
        'Autonome Licht-Emitter auf Lissajous-Orbits schreiben additive Trails mit Decay und Breiten-Taper — die Active-Theory-Trail-Mechanik in NOX-Palette (Ember/Gold/Weißglut), atmosphärisch verlangsamt.',
      importPath: '@/motion-arsenal/effects/backgrounds/OrbitalLightTrails',
      usageJsx: '<OrbitalLightTrails orbCount={4} trailLength={60} intensity={0.85} />',
      props: [
        { key: 'orbCount', label: 'Orbs', type: 'range', default: 4, min: 1, max: 8, step: 1 },
        { key: 'trailLength', label: 'Trail Length', type: 'range', default: 60, min: 12, max: 120, step: 4 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.85, min: 0.2, max: 1, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./OrbitalLightTrails')),
  },
  {
    meta: {
      id: 'bg-symbol-storm',
      name: 'BackgroundSymbolStorm',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: ['ORYZO-Referenz (Symbol-Klasse)', 'KRANK/src/hoisted.js (lerp-Strömung, Tiefen-Layering)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['System-/Daten-Sektionen', 'NOX Forge Test-Hintergrund', '404/Empty-States mit Charakter'],
      performanceNotes: 'Canvas2D, O(n) — bis 120 Symbole flüssig. Kein Filter-Einsatz (Blur via Alpha simuliert).',
      mobileNotes: 'Density ≤ 40; Pointer-Strömung entfällt, Basis-Drift bleibt.',
      reducedMotionNotes: 'Loop pausiert, statisches Symbolfeld.',
      description:
        'Sturm aus kleinen System-Symbolen (Kreuze, Ringe, Dreiecke, Fragmente) in drei Tiefenebenen: vorne schnell + scharf mit Glow-Punch, hinten langsam + schwach. Pointer erzeugt eine gedämpfte Strömungs-Ablenkung.',
      importPath: '@/motion-arsenal/effects/backgrounds/BackgroundSymbolStorm',
      usageJsx: "<BackgroundSymbolStorm density={46} color=\"#C93030\" pointerInfluence={0.6} />",
      props: [
        { key: 'density', label: 'Density', type: 'range', default: 46, min: 10, max: 120, step: 2 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'color', label: 'Color', type: 'color', default: '#C93030' },
        { key: 'pointerInfluence', label: 'Pointer Flow', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./BackgroundSymbolStorm')),
  },
  {
    meta: {
      id: 'bg-noise-fog-field',
      name: 'NoiseFogField',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (fbm/Distortion-Pass, getBlueNoise-Grain)', 'activetheory-bundle.js (Fullscreen-Quad-Pattern)'],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['Premium-Hero-Atmosphäre', 'Black-Forge-Gate', 'Kunden-Sites mit Charakter'],
      performanceNotes: 'Ein WebGL-Fragment-Pass, DPR auf 1.5 gekappt. 5-Oktaven-fbm ×3 pro Pixel — auf Low-End scale erhöhen (weniger Detail nötig).',
      mobileNotes: 'Läuft auf Mobile; Pointer-Wärmeblase entfällt ohne Pointer.',
      reducedMotionNotes: 'Eingefrorener Shader-Frame (frozenTime), kein Loop.',
      description:
        'Domain-warped fbm-Nebel als einzelner WebGL-Pass: mehrschichtiger Rauch mit Ember-Tint, Glut-Kernen in den dichtesten Falten, Pointer-Wärmeblase und Grain gegen Banding — die KRANK-Atmosphäre ohne 1MB-Engine.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoiseFogField',
      usageJsx: '<NoiseFogField intensity={0.9} emberAmount={0.8} scale={2.2} />',
      props: [
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.9, min: 0.2, max: 1.4, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'emberAmount', label: 'Ember', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'scale', label: 'Scale', type: 'range', default: 2.2, min: 1, max: 5, step: 0.1 },
      ],
      productionSafe: true,
      clickToRun: false,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoiseFogField')),
  },
  {
    meta: {
      id: 'bg-depth-glow-stack',
      name: 'DepthGlowLayerStack',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Gobo-Light-Projection — weiche projizierte Lichtvolumina)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Ambient-Grundschicht unter anderen Effekten', 'Dashboards', 'lange Content-Seiten (billig!)'],
      performanceNotes: 'Nur CSS-Compositing (blur + screen), kein JS-Loop außer Parallax. Der billigste Atmosphere-Effekt im Arsenal.',
      mobileNotes: 'Uneingeschränkt mobile-tauglich.',
      reducedMotionNotes: 'Drift/Breathe aus; statische Lichtvolumina bleiben.',
      description:
        'Kein einzelner Glow-Kreis: Stapel aus 5-7 unabhängig driftenden, atmenden Licht-Volumina mit pro Ebene eigenem Hue/Blur/Drift + Grain-Overlay + Pointer-Parallax — die Gobo-Lichtflecken-Idee aus dem Lusion-Rendering als reines CSS.',
      importPath: '@/motion-arsenal/effects/backgrounds/DepthGlowLayerStack',
      usageJsx: '<DepthGlowLayerStack layerCount={6} hueMix={0.7} parallax={0.5} />',
      props: [
        { key: 'layerCount', label: 'Layers', type: 'range', default: 6, min: 3, max: 9, step: 1 },
        { key: 'hueMix', label: 'Hue Mix', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'driftSpeed', label: 'Drift', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.85, min: 0.2, max: 1.2, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./DepthGlowLayerStack')),
  },
  {
    meta: {
      id: 'bg-radial-beam-atmosphere',
      name: 'RadialBeamAtmosphere',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Gobo/Lichtkegel-Projektion als Vorbild)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Hero mit „Erleuchtungs"-Moment', 'Pricing-/CTA-Sektionen', 'Launch-/Countdown-Pages'],
      performanceNotes: 'Zwei rotierende conic-gradients + Maske — GPU-composited, sehr günstig. Große Fläche (240vmax) beachten.',
      mobileNotes: 'Mobile-tauglich; rotationSpeed ≥ 60s halten (Ruhe).',
      reducedMotionNotes: 'Rotation/Puls aus; statischer Strahlenkranz bleibt.',
      description:
        'God-Ray-Atmosphäre: zwei gegenläufig rotierende Strahlenkränze (repeating-conic-gradient) mit radialer Auslauf-Maske, pulsierendem Kern-Glow am Ursprung und Grain — cinematisches Licht ohne WebGL.',
      importPath: '@/motion-arsenal/effects/backgrounds/RadialBeamAtmosphere',
      usageJsx: "<RadialBeamAtmosphere beamCount={9} rotationSpeed={60} color=\"#C93030\" originY={78} />",
      props: [
        { key: 'beamCount', label: 'Beams', type: 'range', default: 9, min: 4, max: 18, step: 1 },
        { key: 'rotationSpeed', label: 'Rotation (s)', type: 'range', default: 60, min: 20, max: 160, step: 5 },
        { key: 'color', label: 'Color', type: 'color', default: '#C93030' },
        { key: 'coreGlow', label: 'Core Glow', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'originY', label: 'Origin Y %', type: 'range', default: 78, min: 20, max: 110, step: 2 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./RadialBeamAtmosphere')),
  },
  {
    meta: {
      id: 'bg-ember-curl-drift',
      name: 'EmberCurlDrift',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (curl()-Vektorfeld + Particles-Klasse, additive Bloom-Komposition)'],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['NOX Forge (Schmiede-DNA!)', 'Hard-Mode/Black-Forge-Momente', 'Hero-Unterschicht'],
      performanceNotes: 'Canvas2D additive, O(n) Curl-Auswertung — bis 400 Funken ok, Glow-Höfe nur für heißeste 25%.',
      mobileNotes: 'count ≤ 100 auf Mobile.',
      reducedMotionNotes: 'Loop pausiert; statisches Glut-Bild.',
      description:
        'Schmiede-Funken steigen aus der Glut auf, ein Curl-Noise-Feld verwirbelt sie seitlich, über die Lebenszeit kühlen sie von Weißgold über Orange zu Dunkelrot ab und verlöschen flackernd — die KRANK-Partikel-Mechanik in NOX-Forge-DNA.',
      importPath: '@/motion-arsenal/effects/backgrounds/EmberCurlDrift',
      usageJsx: '<EmberCurlDrift count={140} updraft={1} turbulence={1} />',
      props: [
        { key: 'count', label: 'Sparks', type: 'range', default: 140, min: 30, max: 400, step: 10 },
        { key: 'updraft', label: 'Updraft', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1 },
        { key: 'turbulence', label: 'Turbulence', type: 'range', default: 1, min: 0, max: 2.5, step: 0.1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./EmberCurlDrift')),
  },
  {
    meta: {
      id: 'bg-holographic-mask-shader',
      name: 'HolographicMaskShader',
      displayName: 'Holographic Mask Shader',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: [
        'Technique reference: https://codepen.io/HejChristian/pen/YPzLbYX',
        'HolographicMaskShader.tsx (exact scroll shader structure; base/mask assets self-hosted under public/effects/holographic/)',
      ],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Scroll-driven image reveals', 'Editorial sections with a real image subject', 'Visual feature moments'],
      performanceNotes: 'Exact CSS compositing technique: one base image, one mask image, mix-blend-mode and background-attachment: fixed. No JavaScript animation loop.',
      mobileNotes: 'The original technique relies on background-attachment: fixed, which the author notes does not behave reliably on iOS Safari. The detail view keeps this limitation visible rather than substituting a different effect.',
      reducedMotionNotes: 'The fixed attachment falls back to scroll attachment; the base image and holographic treatment remain visible.',
      description: 'Exact scroll-driven Holographic Masks treatment from Christian Alder’s CodePen: while the document moves, the fixed rainbow gradient passes behind the sparrow mask through color-dodge compositing. Uses the author-hosted base and mask assets with the source attribution retained.',
      technicalBasis: 'Exact CSS structure: .shader container, absolutely positioned multiply mask layer, color-dodge specular gradient and background-attachment: fixed for page-scroll movement.',
      importPath: '@/motion-arsenal/effects/backgrounds/HolographicMaskShader',
      usageJsx: '<HolographicMaskShader palette="spectrum" gradientAngle={0} />',
      props: [
        { key: 'palette', label: 'Palette', type: 'select', default: 'spectrum', options: ['spectrum', 'gold', 'ice', 'ember', 'mono'], group: 'Color' },
        { key: 'gradientAngle', label: 'Gradient Angle', type: 'range', default: 0, min: 0, max: 360, step: 15, group: 'Color' },
        { key: 'saturation', label: 'Saturation', type: 'range', default: 60, min: 0, max: 100, step: 5, group: 'Color' },
        { key: 'lightness', label: 'Lightness', type: 'range', default: 55, min: 20, max: 80, step: 5, group: 'Color' },
        { key: 'motion', label: 'Antrieb', type: 'select', default: 'scroll', options: ['scroll', 'drift', 'static'], group: 'Motion' },
        { key: 'bandCount', label: 'Farbbaender', type: 'range', default: 13, min: 3, max: 26, step: 1, group: 'Color' },
        { key: 'contrast', label: 'Bandkanten', type: 'range', default: 0, min: 0, max: 1, step: 0.05, group: 'Color' },
        { key: 'blendMode', label: 'Blend Mode', type: 'select', default: 'color-dodge', options: ['color-dodge', 'screen', 'overlay', 'hard-light'], group: 'Compositing' },
        { key: 'showNote', label: 'Caption', type: 'boolean', default: true, group: 'Content' },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-08-09T02:00:00.000Z',
      lastImprovedBy: 'skilltree',
      improvementVersion: '1.1.0',
      improvementChangelog: [
        'Fuenf Farbfamilien statt nur Regenbogen: spectrum, gold, ice, ember, mono.',
        'Verlaufsrichtung frei drehbar (0-360 Grad) — der Schimmer laeuft in beliebiger Achse.',
        'Saettigung und Helligkeit regelbar; das Helligkeitsprofil des Originals bleibt als Kurve erhalten.',
        'Blend-Modus waehlbar, Bildunterschrift abschaltbar.',
        'Die Shader-Struktur und die extern gehosteten Assets des Autors bleiben unveraendert.',
      ],
      updatedAt: '2026-08-02T20:00:00.000Z',
      productionSafe: true,
      status: 'experimental',
      fullBleed: true,
    },
    Component: lazy(() => import('./HolographicMaskShader')),
  },
  {
    meta: {
      id: 'bg-bokeh-gold-field',
      name: 'BokehGoldField',
      displayName: 'Bokeh Gold Field',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: [
        'bokeh-depth-field (Bokeh-Scheiben-Optik, eigene NOX-Variante)',
        'NoxCosmicDepthField.tsx (Blur-Ebenen-Disziplin: filter auf Ebene, nicht pro Element)',
      ],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Signature-Background für Hero-/CTA-Flächen', 'Login-/Pricing-Sektionen', 'Galerie-Hintergrund ohne Canvas-Last'],
      performanceNotes:
        'Komplett CSS-only: drei Blur-Ebenen (filter auf Layer-Container statt pro Scheibe), transform-Keyframes auf dem Compositor, max 16 Scheiben. Kein rAF, kein JS pro Frame.',
      mobileNotes:
        'Touch-tauglich; ab 640px wird die Scheiben-Opazität leicht reduziert. Dekorative Layer mit pointer-events: none + aria-hidden.',
      reducedMotionNotes:
        'Drift-Animation aus — das statische Bokeh-Feld bleibt sichtbar (deterministisches Layout, kein Layout-Sprung).',
      description:
        'Tiefenunscharfe Gold-Kreise (Bokeh) driften in drei Schärfe-Ebenen durch den dunklen Grund — elegante Tiefe für Hero-/CTA-Flächen, ganz ohne Canvas: nur CSS-Filter und transform. Deterministisches Layout aus seededRandom, Pointer-frei.',
      importPath: '@/motion-arsenal/effects/backgrounds/BokehGoldField',
      usageJsx: '<BokehGoldField count={10} speed={1} focus={0.5} color="#d4af37" />',
      props: [
        { key: 'count', label: 'Kreise', type: 'range', default: 10, min: 4, max: 16, step: 1, group: 'Feld' },
        { key: 'speed', label: 'Drift-Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Feld' },
        { key: 'focus', label: 'Schärfe-Tiefe', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Feld' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4af37', group: 'Feld' },
        { key: 'seed', label: 'Seed', type: 'range', default: 20260808, min: 1, max: 99999999, step: 1, group: 'Feld' },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./BokehGoldField')),
  },
  {
    meta: {
      id: 'bg-grain-film-overlay',
      name: 'GrainFilmOverlay',
      displayName: 'Grain Film Overlay',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Backgrounds DNA', 'feTurbulence-Kornkachel'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Editorial- und Portfolio-Flaechen mit analoger Anmutung', 'Hero-Hintergruende, die Tiefe ohne Motiv brauchen', 'Video- und Bildsektionen mit Filmcharakter'],
      performanceNotes: 'Eine Rauschkachel als Data-URI wird in acht Schritten versetzt - steps() statt linear, damit das Korn springt wie Filmmaterial. Kein Canvas, kein JS pro Frame; die Kachel liegt inline und braucht keinen Netzwerkzugriff.',
      mobileNotes: 'Kornkachel und Lichtflecken skalieren mit der Flaeche; die Schicht faengt keine Klicks ab.',
      reducedMotionNotes: 'Korn steht still und Lichtflecken driften nicht; die Textur bleibt als ruhige Schicht sichtbar.',
      description: 'Filmkorn als Overlay-Schicht mit zwei driftenden Lichtflecken fuer den Projektor-Charakter. Die Schicht ist rein dekorativ, liegt auf pointer-events none und traegt aria-hidden.',
      importPath: '@/motion-arsenal/effects/backgrounds/GrainFilmOverlay',
      usageJsx: '<GrainFilmOverlay intensity={0.5} speed={1} glow />',
      props: [
        { key: 'intensity', label: 'Korn', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Grain' },
        { key: 'grainScale', label: 'Kornkachel px', type: 'range', default: 160, min: 60, max: 400, step: 10, group: 'Grain' },
        { key: 'grainStyle', label: 'Kornart', type: 'select', default: 'fine', options: ['fine', 'coarse', 'vertical', 'halftone'], group: 'Grain' },
        { key: 'flicker', label: 'Projektor-Flackern', type: 'range', default: 0, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'blobCount', label: 'Lichtflecken', type: 'range', default: 2, min: 0, max: 4, step: 1, group: 'Light' },
        { key: 'speed', label: 'Film-Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'glow', label: 'Lichtflecken', type: 'boolean', default: true, group: 'Light' },
        { key: 'vignette', label: 'Vignette', type: 'boolean', default: true, group: 'Light' },
        { key: 'glowColor', label: 'Lichtfarbe', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./GrainFilmOverlay')),
  },
  { meta: { id: 'bg-dynamic-palette-gradient', name: 'DynamicPaletteGradient', displayName: 'Dynamic Palette Gradient', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX palette flow field'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Hero Atmospheres', 'Brand Backdrops'], performanceNotes: 'CSS gradient layer with compositor animation.', mobileNotes: 'Lightweight on touch devices.', reducedMotionNotes: 'Palette remains fixed.', description: 'A slow multi-stop gradient breathes through a dark NOX palette.', importPath: '@/motion-arsenal/effects/backgrounds/DynamicPaletteGradient', usageJsx: '<DynamicPaletteGradient />', props: [{ key: 'colors', label: 'Colors', type: 'text', default: '#d4a24a,#5b3517,#11100d' }, { key: 'angle', label: 'Angle', type: 'range', default: 120, min: 0, max: 360, step: 1 }, { key: 'speed', label: 'Speed', type: 'range', default: 18, min: 4, max: 40, step: 1 }, { key: 'color', label: 'Accent', type: 'color', default: '#d4a24a' }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./DynamicPaletteGradient')) },
  { meta: { id: 'bg-ken-burns-cinematic-slideshow', name: 'KenBurnsCinematicSlideshow', displayName: 'Ken Burns Cinematic Slideshow', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-ken-burns-cinematic-slideshow'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Cinematic Heroes'], performanceNotes: 'Opacity and transform-only slides.', mobileNotes: 'Touch-safe controls.', reducedMotionNotes: 'Current frame is static.', description: 'A cinematic Ken Burns slideshow with a gold vignette.', importPath: '@/motion-arsenal/effects/backgrounds/KenBurnsCinematicSlideshow', usageJsx: '<KenBurnsCinematicSlideshow />', props: [], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./KenBurnsCinematicSlideshow')) },
  { meta: { id: 'bg-looking-through-water-blur', name: 'LookingThroughWaterBlur', displayName: 'Looking Through Water Blur', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-looking-through-water-blur'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Atmospheres'], performanceNotes: 'Seeded blur pools.', mobileNotes: 'Static pools remain legible.', reducedMotionNotes: 'Pools stop.', description: 'Wandering blur pools make the scene feel submerged.', importPath: '@/motion-arsenal/effects/backgrounds/LookingThroughWaterBlur', usageJsx: '<LookingThroughWaterBlur />', props: [], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./LookingThroughWaterBlur')) },
  { meta: { id: 'bg-mesh-gradient-flow', name: 'MeshGradientFlow', displayName: 'Mesh Gradient Flow', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-mesh-gradient-flow'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Hero Backdrops'], performanceNotes: 'CSS blurred layers.', mobileNotes: 'Bounded layer count.', reducedMotionNotes: 'Mesh freezes.', description: 'A flowing mesh of gold gradient blobs.', importPath: '@/motion-arsenal/effects/backgrounds/MeshGradientFlow', usageJsx: '<MeshGradientFlow />', props: [], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./MeshGradientFlow')) },
  { meta: { id: 'bg-progressive-blur-stack', name: 'ProgressiveBlurStack', displayName: 'Progressive Blur Stack', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Progressive Blur Stack.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Hero-Hintergründe', 'Editorial-Titel', 'Fokus-Inszenierungen'], performanceNotes: 'Kein rAF: @property registriert --pbs-focus (vom Compositor interpoliert), Ebenen animieren nur filter/opacity/transform. backdrop-filter einmalig auf der Overlay-Schicht.', mobileNotes: 'Pointer-basierten Fokus deaktivierbar; der Stack zeigt dann die manuelle Fokus-Position.', reducedMotionNotes: 'Alle Transitionen deaktiviert — der Stack zeigt den Fokus-Punkt statisch.', description: 'Fokus-Stack mit abgestuften Blur- und Opacity-Ebenen: Derselbe Text liegt in N Ebenen übereinander, ein wandernder Fokus-Punkt (Pointer, Scroll oder manuell) verschiebt die Schärfe durch den Stack — @property + backdrop-filter, deterministisch.', importPath: '@/motion-arsenal/effects/backgrounds/ProgressiveBlurStack', usageJsx: '<ProgressiveBlurStack text="NOX" layers={4} pointerDriven />', props: [{ key: 'text', label: 'Text', type: 'text', default: 'NOX' }, { key: 'layers', label: 'Ebenen', type: 'range', default: 4, min: 2, max: 6, step: 1 }, { key: 'maxBlur', label: 'Max. Blur', type: 'range', default: 26, min: 2, max: 40, step: 1 }, { key: 'focus', label: 'Fokus', type: 'range', default: 0, min: 0, max: 1, step: 0.05 }, { key: 'pointerDriven', label: 'Pointer-Fokus', type: 'boolean', default: true }, { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a' }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./ProgressiveBlurStack')) },
  { meta: { id: 'bg-morphing-blob-field', name: 'MorphingBlobField', displayName: 'Morphing Blob Field', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-morphing-blob-field'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Ambient Backdrops'], performanceNotes: 'Seeded CSS blob geometry.', mobileNotes: 'Bounded blobs.', reducedMotionNotes: 'Blobs freeze.', description: 'Organic gold blobs morph beneath the interface.', importPath: '@/motion-arsenal/effects/backgrounds/MorphingBlobField', usageJsx: '<MorphingBlobField />', props: [], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./MorphingBlobField')) },
  { meta: { id: 'bg-aurora-borealis', name: 'AuroraBorealisBackground', displayName: 'Aurora Borealis Background', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Aurora Borealis Background.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Ambient Backdrops', 'Hero Sections'], performanceNotes: 'Transform-only Blobs (CSS Keyframes), kein Canvas, kein Layout-Write.', mobileNotes: 'Leichtgewichtig, DPR-unabhängig.', reducedMotionNotes: 'Statische Komposition.', description: 'Ruhige, goldgesäumte Gradient-Atmosphäre: deterministische Blob-Geometrie, transform-only, kein Canvas.', importPath: '@/motion-arsenal/effects/backgrounds/AuroraBorealisBackground', usageJsx: '<AuroraBorealisBackground seed={20260810} />', props: [{ key: 'speed', label: 'Geschwindigkeit', type: 'range', default: 1, min: 0, max: 2.5, step: 0.1 }, { key: 'goldIntensity', label: 'Gold-Intensität', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 }, { key: 'blobCount', label: 'Blob-Anzahl', type: 'range', default: 4, min: 3, max: 6, step: 1 }, { key: 'accent', label: 'Akzentfarbe', type: 'color', default: '#d4a24a' }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./AuroraBorealisBackground')) },
  { meta: { id: 'bg-scroll-synced-typo', name: 'ScrollSyncedTypoBackground', displayName: 'Scroll-Synced Typo Background', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Scroll-Synced Typo Background.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Brand Backdrops', 'Hero Sections'], performanceNotes: 'Scroll-Driven Timeline (nativer Fallback: rAF + useScrollProgress), transform-only.', mobileNotes: 'Zwei Lagen, keine Bilder.', reducedMotionNotes: 'Statische Typo.', description: 'Große Marken-Typografie rotiert subtil mit der Scrolltiefe — CSS Scroll-Driven mit JS-Fallback.', importPath: '@/motion-arsenal/effects/backgrounds/ScrollSyncedTypoBackground', usageJsx: '<ScrollSyncedTypoBackground lines={["NOX","ARSENAL"]} />', props: [{ key: 'lines', label: 'Zeilen', type: 'text', default: '' }, { key: 'maxRotation', label: 'Max. Rotation °', type: 'range', default: 10, min: 4, max: 24, step: 1 }, { key: 'drift', label: 'Drift %', type: 'range', default: 18, min: 0, max: 40, step: 1 }, { key: 'lineGap', label: 'Zeilenabstand em', type: 'range', default: 0.16, min: 0, max: 0.6, step: 0.02 }, { key: 'showOutline', label: 'Kontur-Lage', type: 'boolean', default: true }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./ScrollSyncedTypoBackground')) },
  { meta: { id: 'bg-dithered-heatmap', name: 'DitheredDataHeatmap', displayName: 'Dithered Data Heatmap', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Dithered Data Heatmap.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Data Viz', 'Debug Ästhetik'], performanceNotes: 'Statisches DOM-Raster + SVG Pattern, kein rAF-Loop (nur optionaler CSS-Scan).', mobileNotes: 'Zellenzahl begrenzt (max 48×32).', reducedMotionNotes: 'Scanline aus; Raster statisch.', description: 'Dichtebasierte Heatmap im Bayer-Print-Look: DOM-Zellen mit SVG-Pattern-Dither, deterministische Datencluster.', importPath: '@/motion-arsenal/effects/backgrounds/DitheredDataHeatmap', usageJsx: '<DitheredDataHeatmap seed={20260810} />', props: [{ key: 'cols', label: 'Spalten', type: 'range', default: 28, min: 8, max: 48, step: 1 }, { key: 'rows', label: 'Zeilen', type: 'range', default: 16, min: 8, max: 32, step: 1 }, { key: 'contrast', label: 'Kontrast', type: 'range', default: 1, min: 0.2, max: 1.5, step: 0.05 }, { key: 'hotRatio', label: 'Heiße Zellen', type: 'range', default: 0.14, min: 0, max: 0.5, step: 0.02 }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }, { key: 'scanline', label: 'Scan-Linie', type: 'boolean', default: true }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./DitheredDataHeatmap')) },
  { meta: { id: 'bg-grid-blind-mask', name: 'GridBlindMaskReveal', displayName: 'Grid Blind Mask Reveal', category: 'backgrounds', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Grid Blind Mask Reveal.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Section Transitions', 'Reveals'], performanceNotes: 'rAF-Loop setzt nur fill-opacity auf SVG-Rects (mask), kein Layout-Write.', mobileNotes: 'Zellenanzahl begrenzt (max 8×8).', reducedMotionNotes: 'Vorder-Ebene bleibt vollständig lesbar.', description: 'Gestaffelte SVG-Grid-Maske legt eine neue Ebene frei — deterministischer Stagger, Scroll oder Auto.', importPath: '@/motion-arsenal/effects/backgrounds/GridBlindMaskReveal', usageJsx: '<GridBlindMaskReveal frontLabel="NOX" backLabel="ARSENAL" />', props: [{ key: 'frontLabel', label: 'Vorder-Ebene', type: 'text', default: 'NOX' }, { key: 'backLabel', label: 'Rück-Ebene', type: 'text', default: 'ARSENAL' }, { key: 'cellsPerAxis', label: 'Zellen/Achse', type: 'range', default: 4, min: 2, max: 8, step: 1 }, { key: 'mode', label: 'Steuerung', type: 'select', default: 'scroll' }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./GridBlindMaskReveal')) },
  {
    meta: {
      id: 'bg-warp-tunnel-depth',
      name: 'WarpTunnelDepth',
      displayName: 'Warp Tunnel Depth',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Backgrounds DNA', 'Sternenflug-Muster'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Hero-Flaechen mit Aufbruch-Thema', 'Lade- und Uebergangsmomente', 'Technik- und Space-Auftritte'],
      performanceNotes: 'Kein Canvas und kein rAF: jeder Streifen ist ein DOM-Element mit transform-Keyframes, die der Compositor uebernimmt. Drei Tiefenebenen mit unterschiedlichem Tempo erzeugen die Raumwirkung.',
      mobileNotes: 'Streifenlaenge in vmax gerechnet, der Tunnel fuellt jedes Seitenverhaeltnis; die Schicht faengt keine Klicks ab.',
      reducedMotionNotes: 'Streifen stehen still in ihrer Ausgangslage; Fluchtpunkt und Tiefenwirkung bleiben als Standbild erhalten.',
      description: 'Lichtstreifen rasen aus der Bildmitte nach aussen und erzeugen einen Tunnel aus drei Tiefenebenen. Winkel, Abstand und Dauer stammen aus einem Seed, damit derselbe Hintergrund immer gleich aussieht.',
      importPath: '@/motion-arsenal/effects/backgrounds/WarpTunnelDepth',
      usageJsx: '<WarpTunnelDepth streaks={70} speed={1} coreGlow />',
      props: [
        { key: 'streaks', label: 'Streifen', type: 'range', default: 70, min: 10, max: 200, step: 5, group: 'Field' },
        { key: 'streakLength', label: 'Laenge', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1, group: 'Field' },
        { key: 'seed', label: 'Seed', type: 'range', default: 9, min: 1, max: 99, step: 1, group: 'Field' },
        { key: 'speed', label: 'Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'coreGlow', label: 'Kern-Leuchten', type: 'boolean', default: true, group: 'Light' },
        { key: 'color', label: 'Streifen', type: 'color', default: '#d4a24a', group: 'Color' },
        { key: 'deepColor', label: 'Ferne Ebene', type: 'color', default: '#8ab4ff', group: 'Color' },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./WarpTunnelDepth')),
  },
];
