import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const FORMS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'forms-answer-lock-in',
      name: 'AnswerLockIn',
      category: 'forms',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/index.css (Overshoot cubic-bezier(.3,0,.66,-.3))', 'stroke-dash Border-Trace'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Assessments', 'Quiz-/Assessment-Funnels', 'Brand-konfigurierte Entscheidungsmodule'],
      performanceNotes: 'CSS-Komposition, ein SVG-Trace und direkte Auswahl-Transforms. Kein per-frame React-State.',
      mobileNotes: 'Horizontales Fünfer-Deck bleibt tap-tauglich; vertikaler Modus ist für enge Einbettungen verfügbar.',
      reducedMotionNotes: 'Auswahl, Status-Rail und Commit-Zustand bleiben vollständig sichtbar; Scan, Overshoot und Flow stoppen.',
      description: 'Premium Decision Command Deck mit mechanischem Lock-In, Glass-Shell, Signal-Scan, Border-Trace, Status-Telemetrie, Energie-Rail und optionalem Brand-/Logo-Slot. Drei produktive Varianten und horizontale oder vertikale Einbettung.',
      importPath: '@/motion-arsenal/effects/forms/AnswerLockIn',
      usageJsx: '<AnswerLockIn variant="command-deck" orientation="horizontal" energyIntensity={1} showProgressRail />',
      props: [
        { key: 'variant', label: 'Variant', type: 'select', default: 'command-deck', options: ['assessment', 'command-deck', 'brand-lock'] },
        { key: 'orientation', label: 'Layout', type: 'select', default: 'horizontal', options: ['horizontal', 'vertical'] },
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'lockDuration', label: 'Lock s', type: 'range', default: 0.58, min: 0.2, max: 1.5, step: 0.05 },
        { key: 'dimOpacity', label: 'Dim', type: 'range', default: 0.28, min: 0.1, max: 0.8, step: 0.05 },
        { key: 'energyIntensity', label: 'Energy', type: 'range', default: 1, min: 0.25, max: 1.5, step: 0.05 },
        { key: 'showEnergyLine', label: 'Energy Line', type: 'boolean', default: true },
        { key: 'showProgressRail', label: 'Progress Rail', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AnswerLockIn')),
  },
  {
    meta: {
      id: 'forms-question-transition',
      name: 'QuestionTransition',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Scan-Linien-Kollaps (Eigenbau)', 'Shopify Cascade-Timing (Content-Stagger)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Mehrstufige Tests/Funnels', 'NOX Forge Frage-Wechsel'],
      performanceNotes: 'scaleY/Blur auf einem Container — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Direkter Frage-Wechsel.',
      description: 'Frage-Wechsel als Scan-Zyklus: alte Frage kollabiert in eine Scan-Linie (scaleY + Blur), die Linie wischt richtungsbewusst zur Seite, die neue Frage expandiert daraus und staggert ihren Content.',
      importPath: '@/motion-arsenal/effects/forms/QuestionTransition',
      usageJsx: "<QuestionTransition direction=\"forward\" autoCycle />",
      props: [
        { key: 'duration', label: 'Duration s', type: 'range', default: 0.9, min: 0.4, max: 2, step: 0.1 },
        { key: 'blurAmount', label: 'Blur', type: 'range', default: 8, min: 0, max: 16, step: 1 },
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'direction', label: 'Direction', type: 'select', default: 'forward', options: ['forward', 'back'] },
        { key: 'autoCycle', label: 'Auto-Cycle', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./QuestionTransition')),
  },
  {
    meta: {
      id: 'forms-validation-pulse',
      name: 'ValidationPulse',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Echte Feder-Physik x = A·e^(-λt)·sin(ωt) statt CSS-Shake', 'NOX Signal-Terminal UI System'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['High-Ticket Signup-/Login-Felder', 'Checkout-Formulare', 'Magic-Link- und Lead-Capture-Terminals'],
      performanceNotes: 'Eine echte Feder-Simulation aktualisiert ausschließlich den Feld-Transform; Pulse, Scan und Telemetrie laufen CSS-komponiert.',
      mobileNotes: 'Panel und Aktion stapeln sich; Telemetrie wird auf kleinen Viewports ausgeblendet.',
      reducedMotionNotes: 'Farb-, Text-, Check- und Statusfeedback bleiben erhalten; Scan, Orbit, Partikel und Feder stoppen.',
      description: 'Premium Signal Validation Terminal mit echtem gedämpftem Feder-Fehler, dreifachen Pulsringen, Scan-Layer, Erfolgspartikeln, Check-Draw, Live-LED und optionaler Telemetrie. Für Formulare in NOX- und Kundenprojekten konfigurierbar.',
      importPath: '@/motion-arsenal/effects/forms/ValidationPulse',
      usageJsx: '<ValidationPulse variant="command" signalStrength={1} showTelemetry />',
      props: [
        { key: 'variant', label: 'Variant', type: 'select', default: 'command', options: ['field', 'command', 'checkout'] },
        { key: 'accent', label: 'Error Color', type: 'color', default: '#C93030' },
        { key: 'successColor', label: 'Success', type: 'color', default: '#39ff8b' },
        { key: 'springDamping', label: 'Damping λ', type: 'range', default: 6, min: 2, max: 14, step: 0.5 },
        { key: 'springFreq', label: 'Freq Hz', type: 'range', default: 9, min: 3, max: 16, step: 0.5 },
        { key: 'signalStrength', label: 'Signal', type: 'range', default: 1, min: 0.3, max: 1.6, step: 0.05 },
        { key: 'autoValidate', label: 'Auto Validate', type: 'boolean', default: false },
        { key: 'showTelemetry', label: 'Telemetry', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ValidationPulse')),
  },
  {
    meta: {
      id: 'forms-selection-energy-ripple',
      name: 'SelectionEnergyRipple',
      category: 'forms',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['CoinRain-BMBoDYha.js (ballistische Integration: vel += gravity*dt)', 'KRANK additive Funken', 'NOX runtime refinement v2'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Gamified Tests (NOX Forge!)', 'Fortschritts-Momente in Funnels'],
      performanceNotes: 'CSS-Ripple + ballistische Canvas-Funken; requestAnimationFrame läuft nur während tatsächlich aktive Sparks existieren und stoppt danach vollständig.',
      mobileNotes: 'Tap-Punkt = Ripple-Ursprung; Keyboard-Aktivierung nutzt die Button-Mitte als deterministischen Ursprung.',
      reducedMotionNotes: 'Auswahl, ARIA-Live-Status und Zähler bleiben erhalten; Ripple, Aura-Sweep und Canvas-Funken stoppen.',
      description: 'Auswahl zündet einen Energie-Ripple vom Aktivierungspunkt; Funken-Partikel fliegen mit echter Wurf-Ballistik zum Fortschritts-Zähler. V2 ergänzt idle-freies Canvas, robuste Keyboard-Origins, eindeutige Ripple-IDs, Timer-Cleanup und Live-Feedback.',
      importPath: '@/motion-arsenal/effects/forms/SelectionEnergyRippleV2',
      usageJsx: '<SelectionEnergyRippleV2 sparkCount={11} gravity={480} />',
      props: [
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'sparkCount', label: 'Sparks', type: 'range', default: 11, min: 4, max: 24, step: 1 },
        { key: 'gravity', label: 'Gravity', type: 'range', default: 480, min: 200, max: 900, step: 20 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SelectionEnergyRippleV2')),
  },
  {
    meta: {
      id: 'forms-fingerprint-scan-submit',
      name: 'FingerprintScanSubmit',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['codemyui „Pay Button to Animated Finger Print Scanner Transition" (Konzept)', 'NOX Scan-Linien-Vokabular (Barcode Scan Line, ValidationPulse)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Checkout-/Confirm-Submits', 'Zwei-Faktor-Flow-Übergänge', 'Security-/Identity-Momente'],
      performanceNotes: 'Reine CSS-Animationen (Scan-Linie, Puls-Ringe, Check-Draw) + zwei Timer mit Cleanup. Kein per-frame JS.',
      mobileNotes: 'Panel stapelt auf kleinen Viewports; Tap auf den Button startet den Scan (Pointer-Events auf Deko aus).',
      reducedMotionNotes: 'Klick wechselt direkt auf Erfolg — kein Scan-Zyklus, keine Puls-Ringe; Status und Check bleiben sichtbar.',
      description: 'Submit-Button, der beim Klick zum Gold-Fingerprint-Scanner wird: Scan-Linie wischt über den Abdruck, Puls-Ringe expandieren, danach Check-Draw und „Verifiziert"-Status. Eigene NOX-Variante des klassischen Fingerprint-Scan-Übergangs.',
      importPath: '@/motion-arsenal/effects/forms/FingerprintScanSubmit',
      usageJsx: '<FingerprintScanSubmit color="#d4af37" scanDuration={2.2} pulseRings={4} />',
      props: [
        { key: 'color', label: 'Gold', type: 'color', default: '#d4a24a' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.1, max: 3, step: 0.05 },
        { key: 'scanDuration', label: 'Scan s', type: 'range', default: 2.2, min: 1, max: 4, step: 0.1 },
        { key: 'pulseRings', label: 'Rings', type: 'range', default: 4, min: 1, max: 6, step: 1 },
        { key: 'label', label: 'Label', type: 'text', default: 'Fingerprint bestätigen' },
        { key: 'successLabel', label: 'Success', type: 'text', default: 'Verifiziert' },
        { key: 'autoReset', label: 'Auto Reset', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./FingerprintScanSubmit')),
  },
  {
    meta: {
      id: 'forms-star-rating-gold-pop',
      name: 'StarRatingGoldPop',
      displayName: 'Star Rating Gold Pop',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['codepen-star-rating (Pop-/Fill-Demos, eigene NOX-Variante mit echter Radio-Group)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Testimonial-/Review-Forms mit Premium-Feedback', 'Produktbewertungen', 'Gamification-Scores'],
      performanceNotes:
        'Nur fill/transform-Transitionen, Pop-Animation einmalig bei Auswahl (deterministischer --i-Stagger), Count-up-rAF nur während der Wert-Änderung, stoppt danach. Kein Dauerbetrieb.',
      mobileNotes:
        'Touch-Ziele ≥ 44px (size + padding); Hover-Vorlauf entfällt auf Touch (Tap = Auswahl).',
      reducedMotionNotes:
        'Kein Pop — Auswahl-Wechsel nur über den fill-Wechsel; Score zusätzlich als Text im aria-label ("n von max").',
      description:
        'Sterne-Bewertung mit Pop-Sequenz: Hover-Vorlauf füllt die Sterne, beim Auswählen springen sie nacheinander mit Feder-Bounce auf (cubic-bezier-Overshoot, Stagger über --i) und der Score zählt im Label hoch. Als echte Radio-Group gebaut — Tastatur und Screenreader sehen die Auswahl (fieldset + legend, native inputs).',
      importPath: '@/motion-arsenal/effects/forms/StarRatingGoldPop',
      usageJsx: '<StarRatingGoldPop value={3} max={5} size={32} pop color="#d4af37" />',
      props: [
        { key: 'value', label: 'Wert', type: 'range', default: 3, min: 0, max: 10, step: 1, group: 'Rating' },
        { key: 'max', label: 'Sterne', type: 'range', default: 5, min: 3, max: 10, step: 1, group: 'Rating' },
        { key: 'size', label: 'Größe px', type: 'range', default: 32, min: 16, max: 64, step: 2, group: 'Rating' },
        { key: 'pop', label: 'Pop-Animation', type: 'boolean', default: true, group: 'Rating' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4af37', group: 'Rating' },
        { key: 'label', label: 'Label', type: 'text', default: '', group: 'Rating' },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./StarRatingGoldPop')),
  },
  {
    meta: {
      id: 'forms-input-focus-glow',
      name: 'InputFocusGlow',
      displayName: 'Input Focus Glow',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forms DNA', 'Dark-Glass-Feldmuster'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Kontaktformulare mit Premium-Anmutung', 'Login- und Checkout-Felder auf dunklem Grund', 'Suchfelder, die den Fokus deutlich zeigen sollen'],
      performanceNotes: 'CSS-only. Der Sweep ist eine Compositor-Transform statt einer background-position-Animation; der Glow ist eine einmalige box-shadow-Transition, kein Loop. Kein JS, kein rAF.',
      mobileNotes: 'Feldhoehe und Touch-Target ueber 44px; auf Touch entfaellt der Hover-Vorlauf, Fokusglow und Sweep laufen beim Antippen.',
      reducedMotionNotes: 'Glow schaltet ohne Transition, der Lichtstreifen entfaellt vollstaendig.',
      description: 'Dark-Glass-Eingabefeld, das beim Fokus einen Gold-Rahmen aufgluehen laesst, einen Lichtstreifen einmal durchschickt und das Label nach oben schweben laesst. Als echtes label-for gebaut, nicht als Placeholder-Trick.',
      importPath: '@/motion-arsenal/effects/forms/InputFocusGlow',
      usageJsx: '<InputFocusGlow label="E-Mail-Adresse" type="email" sweep />',
      props: [
        { key: 'label', label: 'Label', type: 'text', default: 'E-Mail-Adresse', group: 'Content' },
        { key: 'type', label: 'Feldtyp', type: 'select', default: 'email', options: ['text', 'email', 'password', 'search', 'tel'], group: 'Content' },
        { key: 'hint', label: 'Hinweis', type: 'text', default: 'Wir melden uns innerhalb eines Werktags.', group: 'Content' },
        { key: 'labelFloat', label: 'Floating Label', type: 'boolean', default: true, group: 'Motion' },
        { key: 'sweep', label: 'Sweep-Licht', type: 'boolean', default: true, group: 'Motion' },
        { key: 'glowIntensity', label: 'Intensitaet', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'radius', label: 'Radius', type: 'range', default: 12, min: 0, max: 24, step: 1, group: 'Style' },
        { key: 'glowColor', label: 'Glow', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./InputFocusGlow')),
  },
  {
    meta: {
      id: 'forms-password-strength-meter',
      name: 'PasswordStrengthMeter',
      displayName: 'Password Strength Meter',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forms DNA', 'Regelbasierte Passwortbewertung'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Registrierung und Passwortwechsel', 'Sicherheitseinstellungen im Konto', 'Onboarding-Strecken mit Kontoerstellung'],
      performanceNotes: 'Segmente fuellen sich ueber scaleX, also reine Compositor-Arbeit. Die Bewertung laeuft nur bei Eingabe, kein Loop und kein rAF.',
      mobileNotes: 'Feld und Sichtbarkeits-Umschalter mit ausreichendem Touch-Target; Segmente skalieren ueber die Breite.',
      reducedMotionNotes: 'Segmente schalten ohne Federbewegung, die Bewertung bleibt identisch.',
      description: 'Segmentbalken, der die Passwortstaerke nach festen Regeln bewertet - Laenge, Zeichenklassen und die ueblichen Schwaechen wie Wiederholungen, Tastaturfolgen und bekannte Muster. Die Bewertung ist rein deterministisch und die Stufe steht in einer aria-live-Region, nicht nur in der Farbe.',
      importPath: '@/motion-arsenal/effects/forms/PasswordStrengthMeter',
      usageJsx: '<PasswordStrengthMeter segments={4} rules="standard" />',
      props: [
        { key: 'segments', label: 'Segmente', type: 'range', default: 4, min: 2, max: 6, step: 1, group: 'Layout' },
        { key: 'rules', label: 'Pruef-Regeln', type: 'select', default: 'standard', options: ['standard', 'strict'], group: 'Logik' },
        { key: 'label', label: 'Label anzeigen', type: 'boolean', default: true, group: 'Content' },
        { key: 'initialValue', label: 'Vorbelegung', type: 'text', default: '', group: 'Content' },
        { key: 'color', label: 'Gefuellte Segmente', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./PasswordStrengthMeter')),
  },
  {
    meta: {
      id: 'forms-success-stamp-submit',
      name: 'SuccessStampSubmit',
      displayName: 'Success Stamp Submit',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forms DNA', 'Stempel-Bestaetigung'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Antraege und Bewerbungen', 'Checkout-Abschluss', 'Freigaben und Genehmigungen'],
      performanceNotes: 'Stempel und Funken sind einmalige CSS-Keyframes nach dem Zustandswechsel, kein Loop und kein rAF. Der Timer wird beim Abbau geloescht.',
      mobileNotes: 'Button mit ausreichendem Touch-Target; Stempel skaliert mit dem Blatt.',
      reducedMotionNotes: 'Stempel erscheint ohne Aufsetz-Bewegung, Funken entfallen vollstaendig.',
      description: 'Absenden endet mit einem Stempel, der gross und leicht gedreht einfaehrt und mit Feder-Overshoot einrastet. Der Zustandswechsel wird in einer aria-live-Region angesagt - eine Bestaetigung, die nur visuell existiert, ist fuer einen Teil der Nutzer keine.',
      importPath: '@/motion-arsenal/effects/forms/SuccessStampSubmit',
      usageJsx: '<SuccessStampSubmit text="APPROVED" intensity={0.6} />',
      props: [
        { key: 'text', label: 'Stempel-Text', type: 'text', default: 'APPROVED', group: 'Content' },
        { key: 'buttonLabel', label: 'Button-Text', type: 'text', default: 'Antrag absenden', group: 'Content' },
        { key: 'intensity', label: 'Funken', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05, group: 'Motion' },
        { key: 'rotation', label: 'Drehung', type: 'range', default: -8, min: -30, max: 30, step: 1, group: 'Motion' },
        { key: 'delay', label: 'Wartezeit ms', type: 'range', default: 620, min: 0, max: 3000, step: 20, group: 'Motion' },
        { key: 'seed', label: 'Seed', type: 'range', default: 5, min: 1, max: 99, step: 1, group: 'Motion' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SuccessStampSubmit')),
  },
  { meta: { id: 'forms-labyrinth-balance-toggle', name: 'LabyrinthBalanceToggle', displayName: 'Labyrinth Balance Toggle', category: 'forms', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-labyrinth-balance-toggle'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Toggles'], performanceNotes: 'Pointer tilt and transform-only ball.', mobileNotes: 'Tap toggles state.', reducedMotionNotes: 'Ball snaps to target.', description: 'A toggle where a gold ball balances through a miniature labyrinth.', importPath: '@/motion-arsenal/effects/forms/LabyrinthBalanceToggle', usageJsx: '<LabyrinthBalanceToggle />', props: [], productionSafe: true }, Component: lazy(() => import('./LabyrinthBalanceToggle')) },
  { meta: { id: 'forms-scratch-gold-reveal', name: 'ScratchGoldReveal', displayName: 'Scratch Gold Reveal', category: 'forms', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-scratch-gold-reveal'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Promos'], performanceNotes: 'Canvas scratch overlay.', mobileNotes: 'Pointer Events support touch.', reducedMotionNotes: 'Reveal is immediately available.', description: 'Scratch a deterministic gold foil to reveal a secret.', importPath: '@/motion-arsenal/effects/forms/ScratchGoldReveal', usageJsx: '<ScratchGoldReveal />', props: [], productionSafe: true }, Component: lazy(() => import('./ScratchGoldReveal')) },
  { meta: { id: 'forms-tumbler-vault-otp', name: 'TumblerVaultOTP', displayName: 'Tumbler Vault OTP', category: 'forms', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Auth Flows', 'Vault UI'], performanceNotes: 'CSS transform-Raeder, kein rAF; Re-Render nur bei Eingabe.', mobileNotes: 'Touch: Pointer auf Rad waehlt Stelle.', reducedMotionNotes: 'Ziffern springen ohne Roll-Animation.', description: 'Mechanische OTP-Eingabe: rollende Ziffernraeder (transform-Rad), Paste + Keyboard Support.', importPath: '@/motion-arsenal/effects/forms/TumblerVaultOTP', usageJsx: '<TumblerVaultOTP onComplete={(c) => console.log(c)} />', props: [{ key: "length", label: "Stellen", type: "range", default: 6, min: 4, max: 8, step: 1 }, { key: "initial", label: "Initial", type: "text", default: "" }], productionSafe: true }, Component: lazy(() => import('./TumblerVaultOTP')) },
  { meta: { id: 'forms-step-flow-wizard', name: 'StepFlowWizard', displayName: 'Step Flow Wizard', category: 'forms', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Multi-Step Forms', 'Onboarding'], performanceNotes: 'Linien-Fortschritt scaleX (Compositor), Panel translateX/opacity.', mobileNotes: 'Touch-Buttons; Schritte kompakt.', reducedMotionNotes: 'Panel-Wechsel ohne Sliden.', description: 'Mehrstufiges Formular als Gold-Wizard: Fortschrittslinie zeichnet sich, Connector-Kreise fuellen sich, naechster Schritt faehrt ein.', importPath: '@/motion-arsenal/effects/forms/StepFlowWizard', usageJsx: '<StepFlowWizard />', props: [{ key: "steps", label: "Schritte", type: "text", default: "CONFIG,SIGNAL,VERIFY" }], productionSafe: true }, Component: lazy(() => import('./StepFlowWizard')) },
];
