import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const FORMS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'forms-answer-lock-in',
      name: 'AnswerLockIn',
      category: 'forms',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/index.css (Overshoot cubic-bezier(.3,0,.66,-.3))', 'stroke-dash Border-Trace'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Assessments', 'Quiz-/Assessment-Funnels', 'Brand-konfigurierte Entscheidungsmodule'],
      performanceNotes: 'CSS-Komposition, ein SVG-Trace und direkte Auswahl-Transforms. Kein per-frame React-State.',
      mobileNotes: 'Horizontales Fünfer-Deck bleibt tap-tauglich; vertikaler Modus ist für enge Einbettungen verfügbar.',
      reducedMotionNotes: 'Auswahl, Status-Rail und Commit-Zustand bleiben vollständig sichtbar; Scan, Overshoot und Flow stoppen.',
      description: 'Premium Decision Command Deck mit mechanischem Lock-In, Glass-Shell, Signal-Scan, Border-Trace, Status-Telemetrie, Energie-Rail und optionalem Brand-/Logo-Slot. Drei produktive Varianten und horizontale oder vertikale Einbettung.',
      importPath: '@/motion-arsenal/effects/forms/AnswerLockIn',
      usageJsx: '<AnswerLockIn variant="command-deck" orientation="horizontal" energyIntensity={1} showProgressRail />',
      props: [
        { key: 'variant', label: 'Variant', type: 'select', default: 'command-deck', options: ['assessment', 'command-deck', 'brand-lock'] },
        { key: 'orientation', label: 'Layout', type: 'select', default: 'horizontal', options: ['horizontal', 'vertical'] },
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'lockDuration', label: 'Lock s', type: 'range', default: 0.58, min: 0.2, max: 1.5, step: 0.05 },
        { key: 'dimOpacity', label: 'Dim', type: 'range', default: 0.28, min: 0.1, max: 0.8, step: 0.05 },
        { key: 'energyIntensity', label: 'Energy', type: 'range', default: 1, min: 0.25, max: 1.5, step: 0.05 },
        { key: 'showEnergyLine', label: 'Energy Line', type: 'boolean', default: true },
        { key: 'showProgressRail', label: 'Progress Rail', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AnswerLockIn')),
  },
  {
    meta: {
      id: 'forms-question-transition',
      name: 'QuestionTransition',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Scan-Linien-Kollaps (Eigenbau)', 'Shopify Cascade-Timing (Content-Stagger)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Mehrstufige Tests/Funnels', 'NOX Forge Frage-Wechsel'],
      performanceNotes: 'scaleY/Blur auf einem Container — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Direkter Frage-Wechsel.',
      description: 'Frage-Wechsel als Scan-Zyklus: alte Frage kollabiert in eine Scan-Linie (scaleY + Blur), die Linie wischt richtungsbewusst zur Seite, die neue Frage expandiert daraus und staggert ihren Content.',
      importPath: '@/motion-arsenal/effects/forms/QuestionTransition',
      usageJsx: "<QuestionTransition direction=\"forward\" autoCycle />",
      props: [
        { key: 'duration', label: 'Duration s', type: 'range', default: 0.9, min: 0.4, max: 2, step: 0.1 },
        { key: 'blurAmount', label: 'Blur', type: 'range', default: 8, min: 0, max: 16, step: 1 },
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'direction', label: 'Direction', type: 'select', default: 'forward', options: ['forward', 'back'] },
        { key: 'autoCycle', label: 'Auto-Cycle', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./QuestionTransition')),
  },
  {
    meta: {
      id: 'forms-validation-pulse',
      name: 'ValidationPulse',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Echte Feder-Physik x = A·e^(-λt)·sin(ωt) statt CSS-Shake', 'NOX Signal-Terminal UI System'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['High-Ticket Signup-/Login-Felder', 'Checkout-Formulare', 'Magic-Link- und Lead-Capture-Terminals'],
      performanceNotes: 'Eine echte Feder-Simulation aktualisiert ausschließlich den Feld-Transform; Pulse, Scan und Telemetrie laufen CSS-komponiert.',
      mobileNotes: 'Panel und Aktion stapeln sich; Telemetrie wird auf kleinen Viewports ausgeblendet.',
      reducedMotionNotes: 'Farb-, Text-, Check- und Statusfeedback bleiben erhalten; Scan, Orbit, Partikel und Feder stoppen.',
      description: 'Premium Signal Validation Terminal mit echtem gedämpftem Feder-Fehler, dreifachen Pulsringen, Scan-Layer, Erfolgspartikeln, Check-Draw, Live-LED und optionaler Telemetrie. Für Formulare in NOX- und Kundenprojekten konfigurierbar.',
      importPath: '@/motion-arsenal/effects/forms/ValidationPulse',
      usageJsx: '<ValidationPulse variant="command" signalStrength={1} showTelemetry />',
      props: [
        { key: 'variant', label: 'Variant', type: 'select', default: 'command', options: ['field', 'command', 'checkout'] },
        { key: 'accent', label: 'Error Color', type: 'color', default: '#C93030' },
        { key: 'successColor', label: 'Success', type: 'color', default: '#39ff8b' },
        { key: 'springDamping', label: 'Damping λ', type: 'range', default: 6, min: 2, max: 14, step: 0.5 },
        { key: 'springFreq', label: 'Freq Hz', type: 'range', default: 9, min: 3, max: 16, step: 0.5 },
        { key: 'signalStrength', label: 'Signal', type: 'range', default: 1, min: 0.3, max: 1.6, step: 0.05 },
        { key: 'autoValidate', label: 'Auto Validate', type: 'boolean', default: false },
        { key: 'showTelemetry', label: 'Telemetry', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ValidationPulse')),
  },
  {
    meta: {
      id: 'forms-selection-energy-ripple',
      name: 'SelectionEnergyRipple',
      category: 'forms',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['CoinRain-BMBoDYha.js (ballistische Integration: vel += gravity*dt)', 'KRANK additive Funken'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Gamified Tests (NOX Forge!)', 'Fortschritts-Momente in Funnels'],
      performanceNotes: 'Ripple (CSS) + ≤24 ballistische Funken auf Canvas — günstig.',
      mobileNotes: 'Tap-Punkt = Ripple-Ursprung.',
      reducedMotionNotes: 'Auswahl + Zähler ohne Ripple/Funken.',
      description: 'Auswahl zündet einen Energie-Ripple vom Klickpunkt; Funken-Partikel fliegen mit echter Wurf-Ballistik (Gravitations-Bogen, CoinRain-Integration) zum Fortschritts-Zähler, der beim Einschlag aufblitzt und hochzählt.',
      importPath: '@/motion-arsenal/effects/forms/SelectionEnergyRipple',
      usageJsx: '<SelectionEnergyRipple sparkCount={11} gravity={480} />',
      props: [
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'sparkCount', label: 'Sparks', type: 'range', default: 11, min: 4, max: 24, step: 1 },
        { key: 'gravity', label: 'Gravity', type: 'range', default: 480, min: 200, max: 900, step: 20 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SelectionEnergyRipple')),
  },
  {
    meta: {
      id: 'forms-star-rating-gold-pop',
      name: 'StarRatingGoldPop',
      displayName: 'Star Rating Gold Pop',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['codepen-star-rating (Pop-/Fill-Demos, eigene NOX-Variante mit echter Radio-Group)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Testimonial-/Review-Forms mit Premium-Feedback', 'Produktbewertungen', 'Gamification-Scores'],
      performanceNotes:
        'Nur fill/transform-Transitionen, Pop-Animation einmalig bei Auswahl (deterministischer --i-Stagger), Count-up-rAF nur während der Wert-Änderung, stoppt danach. Kein Dauerbetrieb.',
      mobileNotes:
        'Touch-Ziele ≥ 44px (size + padding); Hover-Vorlauf entfällt auf Touch (Tap = Auswahl).',
      reducedMotionNotes:
        'Kein Pop — Auswahl-Wechsel nur über den fill-Wechsel; Score zusätzlich als Text im aria-label ("n von max").',
      description:
        'Sterne-Bewertung mit Pop-Sequenz: Hover-Vorlauf füllt die Sterne, beim Auswählen springen sie nacheinander mit Feder-Bounce auf (cubic-bezier-Overshoot, Stagger über --i) und der Score zählt im Label hoch. Als echte Radio-Group gebaut — Tastatur und Screenreader sehen die Auswahl (fieldset + legend, native inputs).',
      importPath: '@/motion-arsenal/effects/forms/StarRatingGoldPop',
      usageJsx: '<StarRatingGoldPop value={3} max={5} size={32} pop color="#d4af37" />',
      props: [
        { key: 'value', label: 'Wert', type: 'range', default: 3, min: 0, max: 10, step: 1, group: 'Rating' },
        { key: 'max', label: 'Sterne', type: 'range', default: 5, min: 3, max: 10, step: 1, group: 'Rating' },
        { key: 'size', label: 'Größe px', type: 'range', default: 32, min: 16, max: 64, step: 2, group: 'Rating' },
        { key: 'pop', label: 'Pop-Animation', type: 'boolean', default: true, group: 'Rating' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4af37', group: 'Rating' },
        { key: 'label', label: 'Label', type: 'text', default: '', group: 'Rating' },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./StarRatingGoldPop')),
  },
];
