import { useMemo } from 'react';
import type React from 'react';
export interface ConnectedGridPulseProps { columns?: number; rows?: number; accent?: string; }
export default function ConnectedGridPulse({ columns = 7, rows = 4, accent = '#d4a24a' }: ConnectedGridPulseProps) {
  const nodes = useMemo(() => Array.from({ length: columns * rows }, (_, i) => ({ x: (i % columns) * 100 / (columns - 1), y: Math.floor(i / columns) * 100 / (rows - 1) })), [columns, rows]);
  const links = useMemo(() => nodes.flatMap((node, i) => { const next = []; if (i % columns < columns - 1) next.push([node, nodes[i + 1]]); if (i + columns < nodes.length) next.push([node, nodes[i + columns]]); return next; }), [nodes, columns]);
  return <section className="nox-grid-pulse" style={{ '--grid-accent': accent } as React.CSSProperties} aria-label="Connected grid pulse"><svg viewBox="0 0 100 100" role="img"><g className="nox-grid-pulse__links">{links.map(([a, b], i) => <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} pathLength="1" style={{ '--link-delay': `${(i % 9) * .16}s` } as React.CSSProperties} />)}</g><g>{nodes.map((node, i) => <circle key={i} cx={node.x} cy={node.y} r="1.3" style={{ '--node-delay': `${(i % columns) * .12}s` } as React.CSSProperties} />)}</g></svg><strong>CONNECTED / LIVE</strong><style>{CSS}</style></section>;
}
const CSS = String.raw`.nox-grid-pulse{position:relative;min-height:330px;background:#080a0e;color:var(--grid-accent);display:grid;place-items:center;overflow:hidden}.nox-grid-pulse svg{width:min(760px,90vw);height:auto;overflow:visible}.nox-grid-pulse line{stroke:var(--grid-accent);stroke-width:.18;opacity:.45;stroke-dasharray:.08 .04;animation:grid-line 2.8s linear var(--link-delay) infinite}.nox-grid-pulse circle{fill:#f7e8a4;filter:drop-shadow(0 0 3px var(--grid-accent));animation:grid-node 1.8s ease-in-out var(--node-delay) infinite}.nox-grid-pulse strong{position:absolute;bottom:1rem;font:10px monospace;letter-spacing:.3em;opacity:.6}@keyframes grid-line{to{stroke-dashoffset:-1}}@keyframes grid-node{50%{r:2;opacity:.45}}@media(prefers-reduced-motion:reduce){.nox-grid-pulse line,.nox-grid-pulse circle{animation:none}}`;
