import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { clamp, usePrefersReducedMotion } from '../../lib/animationUtils';

export interface GlslImageGlitchProps { src?: string; alt?: string; intensity?: number; slices?: number; mode?: 'idle' | 'burst'; color?: string; }
export default function GlslImageGlitch({ src = '', alt = 'Glitched artwork', intensity = .4, slices = 10, mode = 'idle', color = '#d4a24a' }: GlslImageGlitchProps) {
  const ref = useRef<HTMLCanvasElement>(null); const reduced = usePrefersReducedMotion(); const [burst, setBurst] = useState(false);
  useEffect(() => { const canvas = ref.current; if (!canvas) return; const gl = canvas.getContext('webgl'); if (!gl) return;
    const vs = `attribute vec2 p; varying vec2 uv; void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
    const fs = `precision mediump float; varying vec2 uv; uniform float t, power, rows; uniform vec3 tint; uniform sampler2D tex; float hash(float n){return fract(sin(n)*43758.5453);} void main(){float row=floor(uv.y*rows);float n=hash(row+floor(t*12.));float off=(n-.5)*power*.12;vec2 r=uv+vec2(off,0.);vec3 c=vec3(texture2D(tex,r).r,texture2D(tex,uv).g,texture2D(tex,uv-vec2(off,0.)).b);float flash=step(.96,hash(row+t*31.));gl_FragColor=vec4(c+ tint*flash*.18,1.);}`;
    const compile=(type:number, code:string)=>{const s=gl.createShader(type)!; gl.shaderSource(s,code); gl.compileShader(s); return s}; const program=gl.createProgram()!; gl.attachShader(program,compile(gl.VERTEX_SHADER,vs)); gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs)); gl.linkProgram(program); gl.useProgram(program);
    const buf=gl.createBuffer()!; gl.bindBuffer(gl.ARRAY_BUFFER,buf); gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW); const loc=gl.getAttribLocation(program,'p'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);
    const tex=gl.createTexture()!; gl.bindTexture(gl.TEXTURE_2D,tex); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR); const image=new Image(); image.onload=()=>gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image); image.src=src;
    let raf=0; const start=performance.now(); const frame=(now:number)=>{const box=canvas.getBoundingClientRect(); const dpr=Math.min(devicePixelRatio||1,2); canvas.width=box.width*dpr; canvas.height=box.height*dpr; gl.viewport(0,0,canvas.width,canvas.height); gl.uniform1f(gl.getUniformLocation(program,'t'),reduced?0:(now-start)/1000); gl.uniform1f(gl.getUniformLocation(program,'power'),reduced?0:(burst||mode==='burst'?intensity:intensity*.25)); gl.uniform1f(gl.getUniformLocation(program,'rows'),clamp(slices,2,30)); gl.uniform3f(gl.getUniformLocation(program,'tint'),.83,.63,.29); gl.drawArrays(gl.TRIANGLE_STRIP,0,4); raf=requestAnimationFrame(frame)}; raf=requestAnimationFrame(frame); return()=>cancelAnimationFrame(raf);
  },[burst,color,intensity,mode,reduced,slices,src]);
  return <button type="button" className="nox-glsl-glitch" onMouseEnter={()=>setBurst(true)} onFocus={()=>setBurst(true)} onClick={()=>setBurst(v=>!v)} style={{'--glitch-tint':color} as CSSProperties}><canvas ref={ref} aria-label={alt}/><span>{alt}</span><style>{`.nox-glsl-glitch{position:relative;display:block;width:min(100%,34rem);aspect-ratio:16/10;padding:0;overflow:hidden;background:#101016;border:1px solid var(--glitch-tint);cursor:pointer}.nox-glsl-glitch canvas{width:100%;height:100%;display:block}.nox-glsl-glitch span{position:absolute;inset:auto 1rem 1rem;color:#fff;text-shadow:0 1px 4px #000}.nox-glsl-glitch:focus-visible{outline:2px solid var(--glitch-tint);outline-offset:4px}`}</style></button>;
}
