// GENERATED by scripts/generate-core-presets.mjs — do not edit by hand.
// Mirrors the niche preset records inside the canonical core components so the
// preset picker loads the complete curated state instead of relying on the
// component's internal `?? preset.x` fallbacks (the arsenal always passes
// every prop explicitly, which would otherwise defeat them).
import type { NicheId } from '../types';

export interface GeneratedCorePreset {
  id: string;
  label: string;
  niche: NicheId;
  props: Record<string, number | string | boolean>;
  performanceProfile: 'lite' | 'balanced' | 'cinematic';
  mobileProfile: 'compact' | 'balanced' | 'full';
  source: 'component';
}

export const GENERATED_CORE_PRESETS: Record<string, GeneratedCorePreset[]> = {
  "bg-atmosphere-field": [
    {
      "id": "bg-atmosphere-field::restaurant",
      "label": "Restaurant / Hospitality",
      "niche": "restaurant",
      "props": {
        "fog": true,
        "glow": true,
        "beams": false,
        "intensity": 0.66,
        "speed": 0.72,
        "glowLayers": 5,
        "parallax": 0.22,
        "beamCount": 7,
        "vignette": 0.46,
        "performanceProfile": "balanced",
        "preset": "restaurant"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::beauty",
      "label": "Beauty / Wellness",
      "niche": "beauty",
      "props": {
        "fog": true,
        "glow": true,
        "beams": false,
        "intensity": 0.54,
        "speed": 0.58,
        "glowLayers": 5,
        "parallax": 0.16,
        "beamCount": 6,
        "vignette": 0.34,
        "performanceProfile": "balanced",
        "preset": "beauty"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "fog": true,
        "glow": true,
        "beams": true,
        "intensity": 0.92,
        "speed": 1.28,
        "glowLayers": 6,
        "parallax": 0.5,
        "beamCount": 12,
        "vignette": 0.58,
        "performanceProfile": "cinematic",
        "preset": "fitness"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::local-service",
      "label": "Handwerk / Local Service",
      "niche": "local-service",
      "props": {
        "fog": true,
        "glow": false,
        "beams": true,
        "intensity": 0.68,
        "speed": 0.9,
        "glowLayers": 4,
        "parallax": 0.18,
        "beamCount": 8,
        "vignette": 0.52,
        "performanceProfile": "balanced",
        "preset": "local-service"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::real-estate",
      "label": "Immobilien",
      "niche": "real-estate",
      "props": {
        "fog": false,
        "glow": true,
        "beams": true,
        "intensity": 0.46,
        "speed": 0.46,
        "glowLayers": 4,
        "parallax": 0.12,
        "beamCount": 6,
        "vignette": 0.3,
        "performanceProfile": "lite",
        "preset": "real-estate"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::automotive",
      "label": "Automotive",
      "niche": "automotive",
      "props": {
        "fog": true,
        "glow": true,
        "beams": true,
        "intensity": 0.84,
        "speed": 1.06,
        "glowLayers": 6,
        "parallax": 0.44,
        "beamCount": 10,
        "vignette": 0.64,
        "performanceProfile": "cinematic",
        "preset": "automotive"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::healthcare",
      "label": "Healthcare / Praxis",
      "niche": "healthcare",
      "props": {
        "fog": false,
        "glow": true,
        "beams": false,
        "intensity": 0.34,
        "speed": 0.4,
        "glowLayers": 4,
        "parallax": 0.08,
        "beamCount": 5,
        "vignette": 0.2,
        "performanceProfile": "lite",
        "preset": "healthcare"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::finance",
      "label": "Kanzlei / Finance",
      "niche": "finance",
      "props": {
        "fog": false,
        "glow": true,
        "beams": true,
        "intensity": 0.4,
        "speed": 0.4,
        "glowLayers": 4,
        "parallax": 0.08,
        "beamCount": 5,
        "vignette": 0.3,
        "performanceProfile": "lite",
        "preset": "finance"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "fog": true,
        "glow": true,
        "beams": true,
        "intensity": 0.74,
        "speed": 0.92,
        "glowLayers": 6,
        "parallax": 0.42,
        "beamCount": 9,
        "vignette": 0.48,
        "performanceProfile": "cinematic",
        "preset": "saas"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::ecommerce",
      "label": "E-Commerce",
      "niche": "ecommerce",
      "props": {
        "fog": true,
        "glow": true,
        "beams": false,
        "intensity": 0.66,
        "speed": 0.82,
        "glowLayers": 5,
        "parallax": 0.3,
        "beamCount": 8,
        "vignette": 0.34,
        "performanceProfile": "balanced",
        "preset": "ecommerce"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "fog": true,
        "glow": true,
        "beams": true,
        "intensity": 0.46,
        "speed": 0.38,
        "glowLayers": 5,
        "parallax": 0.1,
        "beamCount": 6,
        "vignette": 0.42,
        "performanceProfile": "balanced",
        "preset": "luxury"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "bg-atmosphere-field::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "fog": true,
        "glow": true,
        "beams": true,
        "intensity": 0.86,
        "speed": 1.12,
        "glowLayers": 6,
        "parallax": 0.5,
        "beamCount": 11,
        "vignette": 0.48,
        "performanceProfile": "cinematic",
        "preset": "creator"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ],
  "canvasui-particle-field-system": [
    {
      "id": "canvasui-particle-field-system::restaurant",
      "label": "Restaurant / Hospitality",
      "niche": "restaurant",
      "props": {
        "mode": "reveal",
        "density": 2200,
        "particleSize": 1.25,
        "scatter": 8,
        "interactionStrength": 0.72,
        "color": "#D89B5B",
        "preset": "restaurant"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::beauty",
      "label": "Beauty / Wellness",
      "niche": "beauty",
      "props": {
        "mode": "reveal",
        "density": 2500,
        "particleSize": 1.05,
        "scatter": 7,
        "interactionStrength": 0.58,
        "color": "#D9A8B8",
        "preset": "beauty"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "mode": "asset",
        "density": 3300,
        "particleSize": 2.3,
        "scatter": 16,
        "interactionStrength": 1.18,
        "color": "#FF5B2E",
        "preset": "fitness"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::local-service",
      "label": "Handwerk / Local Service",
      "niche": "local-service",
      "props": {
        "mode": "asset",
        "density": 2800,
        "particleSize": 2.15,
        "scatter": 12,
        "interactionStrength": 0.92,
        "color": "#F2B544",
        "preset": "local-service"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::real-estate",
      "label": "Immobilien",
      "niche": "real-estate",
      "props": {
        "mode": "reveal",
        "density": 2100,
        "particleSize": 1.05,
        "scatter": 6,
        "interactionStrength": 0.48,
        "color": "#C8B38A",
        "preset": "real-estate"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::automotive",
      "label": "Automotive",
      "niche": "automotive",
      "props": {
        "mode": "asset",
        "density": 3400,
        "particleSize": 2.25,
        "scatter": 15,
        "interactionStrength": 1.08,
        "color": "#C5D0D9",
        "preset": "automotive"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::healthcare",
      "label": "Healthcare / Praxis",
      "niche": "healthcare",
      "props": {
        "mode": "reveal",
        "density": 1800,
        "particleSize": 1,
        "scatter": 4,
        "interactionStrength": 0.4,
        "color": "#69B8B4",
        "preset": "healthcare"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::finance",
      "label": "Kanzlei / Finance",
      "niche": "finance",
      "props": {
        "mode": "reveal",
        "density": 1900,
        "particleSize": 0.95,
        "scatter": 4,
        "interactionStrength": 0.42,
        "color": "#B8A46B",
        "preset": "finance"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "mode": "asset",
        "density": 3000,
        "particleSize": 1.8,
        "scatter": 11,
        "interactionStrength": 0.88,
        "color": "#62A7FF",
        "preset": "saas"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::ecommerce",
      "label": "E-Commerce",
      "niche": "ecommerce",
      "props": {
        "mode": "asset",
        "density": 3300,
        "particleSize": 2,
        "scatter": 13,
        "interactionStrength": 1,
        "color": "#F078B8",
        "preset": "ecommerce"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "mode": "reveal",
        "density": 2300,
        "particleSize": 0.9,
        "scatter": 5,
        "interactionStrength": 0.38,
        "color": "#C5A56B",
        "preset": "luxury"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "canvasui-particle-field-system::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "mode": "reveal",
        "density": 3100,
        "particleSize": 1.35,
        "scatter": 15,
        "interactionStrength": 1.06,
        "color": "#B86CFF",
        "preset": "creator"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ],
  "scroll-scene-system": [
    {
      "id": "scroll-scene-system::restaurant",
      "label": "Restaurant / Hospitality",
      "niche": "restaurant",
      "props": {
        "layout": "pinned",
        "stations": 4,
        "damping": 8,
        "showRail": false,
        "colorShift": true,
        "objectScale": 1.04,
        "depth": 0.58,
        "accent": "#D89B5B",
        "preset": "restaurant"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::beauty",
      "label": "Beauty / Wellness",
      "niche": "beauty",
      "props": {
        "layout": "free",
        "stations": 4,
        "damping": 10,
        "showRail": false,
        "colorShift": true,
        "objectScale": 0.94,
        "depth": 0.44,
        "accent": "#D9A8B8",
        "preset": "beauty"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "layout": "pinned",
        "stations": 5,
        "damping": 7,
        "showRail": true,
        "colorShift": true,
        "objectScale": 1.08,
        "depth": 0.9,
        "accent": "#FF5B2E",
        "preset": "fitness"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::local-service",
      "label": "Handwerk / Local Service",
      "niche": "local-service",
      "props": {
        "layout": "free",
        "stations": 4,
        "damping": 8,
        "showRail": true,
        "colorShift": false,
        "objectScale": 1,
        "depth": 0.55,
        "accent": "#F2B544",
        "preset": "local-service"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::real-estate",
      "label": "Immobilien",
      "niche": "real-estate",
      "props": {
        "layout": "pinned",
        "stations": 4,
        "damping": 11,
        "showRail": false,
        "colorShift": false,
        "objectScale": 1.02,
        "depth": 0.36,
        "accent": "#C8B38A",
        "preset": "real-estate"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::automotive",
      "label": "Automotive",
      "niche": "automotive",
      "props": {
        "layout": "pinned",
        "stations": 5,
        "damping": 8,
        "showRail": true,
        "colorShift": true,
        "objectScale": 1.08,
        "depth": 0.82,
        "accent": "#C5D0D9",
        "preset": "automotive"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::healthcare",
      "label": "Healthcare / Praxis",
      "niche": "healthcare",
      "props": {
        "layout": "free",
        "stations": 4,
        "damping": 12,
        "showRail": false,
        "colorShift": false,
        "objectScale": 0.9,
        "depth": 0.28,
        "accent": "#69B8B4",
        "preset": "healthcare"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::finance",
      "label": "Kanzlei / Finance",
      "niche": "finance",
      "props": {
        "layout": "free",
        "stations": 4,
        "damping": 12,
        "showRail": true,
        "colorShift": false,
        "objectScale": 0.94,
        "depth": 0.24,
        "accent": "#B8A46B",
        "preset": "finance"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "layout": "pinned",
        "stations": 4,
        "damping": 8,
        "showRail": true,
        "colorShift": true,
        "objectScale": 1,
        "depth": 0.72,
        "accent": "#62A7FF",
        "preset": "saas"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::ecommerce",
      "label": "E-Commerce",
      "niche": "ecommerce",
      "props": {
        "layout": "pinned",
        "stations": 5,
        "damping": 8,
        "showRail": true,
        "colorShift": true,
        "objectScale": 1.04,
        "depth": 0.68,
        "accent": "#F078B8",
        "preset": "ecommerce"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "layout": "free",
        "stations": 4,
        "damping": 13,
        "showRail": false,
        "colorShift": false,
        "objectScale": 0.92,
        "depth": 0.22,
        "accent": "#C5A56B",
        "preset": "luxury"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "scroll-scene-system::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "layout": "pinned",
        "stations": 5,
        "damping": 7,
        "showRail": true,
        "colorShift": true,
        "objectScale": 1.06,
        "depth": 0.78,
        "accent": "#B86CFF",
        "preset": "creator"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ],
  "skilltree-scene-system": [
    {
      "id": "skilltree-scene-system::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "mode": "forge",
        "speed": 1.15,
        "atmosphere": "embers",
        "atmosphereDensity": 14,
        "links": "risk-mix",
        "nodeCount": 6,
        "preset": "fitness"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    },
    {
      "id": "skilltree-scene-system::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "mode": "constellation",
        "speed": 0.8,
        "atmosphere": "stars",
        "atmosphereDensity": 22,
        "links": "state",
        "nodeCount": 6,
        "preset": "saas"
      },
      "performanceProfile": "cinematic",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "skilltree-scene-system::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "mode": "float",
        "speed": 1,
        "atmosphere": "hybrid",
        "atmosphereDensity": 14,
        "links": "flow",
        "nodeCount": 5,
        "preset": "creator"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    },
    {
      "id": "skilltree-scene-system::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "mode": "constellation",
        "speed": 0.55,
        "atmosphere": "stars",
        "atmosphereDensity": 12,
        "links": "state",
        "nodeCount": 5,
        "showLabels": false,
        "preset": "luxury"
      },
      "performanceProfile": "lite",
      "mobileProfile": "compact",
      "source": "component"
    }
  ],
  "skilltree-node-state-system": [
    {
      "id": "skilltree-node-state-system::fitness",
      "label": "Fitness / Progress",
      "niche": "fitness",
      "props": {
        "preset": "fitness"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "skilltree-node-state-system::saas",
      "label": "SaaS / Recommended",
      "niche": "saas",
      "props": {
        "preset": "saas"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "skilltree-node-state-system::creator",
      "label": "Creator / Risk Signal",
      "niche": "creator",
      "props": {
        "preset": "creator"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "skilltree-node-state-system::luxury",
      "label": "Luxury / Focus",
      "niche": "luxury",
      "props": {
        "preset": "luxury"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ],
  "originkit-text-mutation-system": [
    {
      "id": "originkit-text-mutation-system::restaurant",
      "label": "Restaurant / Hospitality",
      "niche": "restaurant",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 72,
        "preset": "restaurant"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::beauty",
      "label": "Beauty / Wellness",
      "niche": "beauty",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 92,
        "preset": "beauty"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "mode": "scramble",
        "trigger": "auto",
        "speed": 34,
        "preset": "fitness"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::local-service",
      "label": "Handwerk / Local Service",
      "niche": "local-service",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 58,
        "preset": "local-service"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::real-estate",
      "label": "Immobilien",
      "niche": "real-estate",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 88,
        "preset": "real-estate"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::automotive",
      "label": "Automotive",
      "niche": "automotive",
      "props": {
        "mode": "scramble",
        "trigger": "auto",
        "speed": 38,
        "preset": "automotive"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::healthcare",
      "label": "Healthcare / Praxis",
      "niche": "healthcare",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 82,
        "preset": "healthcare"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::finance",
      "label": "Kanzlei / Finance",
      "niche": "finance",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 86,
        "preset": "finance"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "mode": "scramble",
        "trigger": "auto",
        "speed": 46,
        "preset": "saas"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::ecommerce",
      "label": "E-Commerce",
      "niche": "ecommerce",
      "props": {
        "mode": "scramble",
        "trigger": "hover",
        "speed": 42,
        "preset": "ecommerce"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "mode": "typewriter",
        "trigger": "once",
        "speed": 112,
        "preset": "luxury"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-text-mutation-system::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "mode": "scramble",
        "trigger": "hover",
        "speed": 36,
        "preset": "creator"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ],
  "originkit-variable-weight-text": [
    {
      "id": "originkit-variable-weight-text::beauty",
      "label": "Beauty / Wellness",
      "niche": "beauty",
      "props": {
        "trigger": "auto",
        "rhythm": "breathe",
        "minWeight": 250,
        "maxWeight": 620,
        "duration": 3.2,
        "stagger": 0.07,
        "scale": 1.015,
        "lift": 1,
        "tracking": 0.01
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-variable-weight-text::fitness",
      "label": "Fitness / Sport",
      "niche": "fitness",
      "props": {
        "trigger": "hover",
        "hoverScope": "group",
        "rhythm": "pulse",
        "minWeight": 350,
        "maxWeight": 900,
        "duration": 0.28,
        "stagger": 0.018,
        "scale": 1.045,
        "lift": 2
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-variable-weight-text::saas",
      "label": "SaaS / Tech",
      "niche": "saas",
      "props": {
        "trigger": "hover",
        "hoverScope": "group",
        "rhythm": "wave",
        "minWeight": 350,
        "maxWeight": 720,
        "duration": 0.34,
        "stagger": 0.022,
        "scale": 1.015,
        "lift": 1
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-variable-weight-text::ecommerce",
      "label": "E-Commerce",
      "niche": "ecommerce",
      "props": {
        "trigger": "hover",
        "hoverScope": "group",
        "rhythm": "pulse",
        "minWeight": 400,
        "maxWeight": 800,
        "duration": 0.3,
        "stagger": 0.018,
        "scale": 1.025
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-variable-weight-text::luxury",
      "label": "Luxury / Premium",
      "niche": "luxury",
      "props": {
        "trigger": "auto",
        "rhythm": "breathe",
        "minWeight": 260,
        "maxWeight": 560,
        "duration": 4.2,
        "stagger": 0.11,
        "scale": 1.008,
        "lift": 0.5,
        "tracking": 0.025
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    },
    {
      "id": "originkit-variable-weight-text::creator",
      "label": "Creator / Personal Brand",
      "niche": "creator",
      "props": {
        "trigger": "auto",
        "rhythm": "wave",
        "minWeight": 220,
        "maxWeight": 850,
        "duration": 2.2,
        "stagger": 0.09,
        "scale": 1.03,
        "lift": 2,
        "direction": "center"
      },
      "performanceProfile": "balanced",
      "mobileProfile": "balanced",
      "source": "component"
    }
  ]
};
