import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const CURSOR_CATALOG: EffectEntry[] = [
  { meta: { id: 'cursor-gooey-cursor-blob', name: 'GooeyCursorBlob', displayName: 'Gooey Cursor Blob', category: 'cursor', sourceWebsite: 'codrops', sourceFiles: ['Vault: nox-gooey-cursor-blob'], mode: 'nox-original', complexity: 'medium', dependencies: [], bestFor: ['Dark Theme Cursor Atmospheres'], performanceNotes: 'Two transform followers in one SVG filter.', mobileNotes: 'Decorative cursor hides without reduced pointer.', reducedMotionNotes: 'Blob is hidden.', description: 'Two damped followers merge into a tactile gold gooey cursor.', importPath: '@/motion-arsenal/effects/cursor/GooeyCursorBlob', usageJsx: '<GooeyCursorBlob intensity={.5} />', props: [{ key: 'intensity', label: 'Intensity', type: 'range', default: .5, min: 0, max: 1, step: .1 }, { key: 'size', label: 'Size', type: 'range', default: .5, min: .2, max: 1.5, step: .1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./GooeyCursorBlob')) },
  { meta: { id: 'cursor-ball-pit-sinkhole-reveal', name: 'BallPitSinkholeReveal', displayName: 'Ball Pit Sinkhole Reveal', category: 'cursor', sourceWebsite: 'nox-original', sourceFiles: ['codemyui cursor reveal', 'Vault: nox-ball-pit-sinkhole-reveal'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Cursor-Reveals', 'Easter Eggs'], performanceNotes: 'Deterministische Canvas-Partikel; rAF endet bei Reduced Motion.', mobileNotes: 'Pointer Events unterstützen Maus und Touch.', reducedMotionNotes: 'Statischer Gold-Sinkhole-Reveal ohne Bewegung.', description: 'Eine deterministische Kugelgrube weicht dem Pointer und legt einen leuchtenden Gold-Sinkhole frei.', importPath: '@/motion-arsenal/effects/cursor/BallPitSinkholeReveal', usageJsx: '<BallPitSinkholeReveal balls={120} />', props: [{ key: 'balls', label: 'Balls', type: 'range', default: 120, min: 30, max: 300, step: 10 }, { key: 'holeRadius', label: 'Hole Radius', type: 'range', default: 70, min: 30, max: 150, step: 5 }, { key: 'sinkSpeed', label: 'Sink Speed', type: 'range', default: 1, min: .1, max: 3, step: .1 }], productionSafe: true, status: 'production-safe', fullBleed: true }, Component: lazy(() => import('./BallPitSinkholeReveal')) },
  {
    meta: {
      id: 'cursor-magnetic-cta',
      name: 'MagneticCTA',
      category: 'cursor',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Cursor-Klasse: attractionRadius ~100px, pullStrength = 1 - d/r, lerp 0.15)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Primäre CTAs', 'Nav-Links auf Premium-Sites'],
      performanceNotes: 'Ein rAF-Loop, zwei Transforms pro Button — vernachlässigbar.',
      mobileNotes: 'Touch: keine Magnetik (Buttons bleiben normal klickbar).',
      reducedMotionNotes: 'Keine Anziehung, statische Buttons.',
      description: 'Buttons mit Lusion-Magnetik: nichtlineare Anziehung im Radius (stärker je näher), Label wandert stärker als der Button (inneres Parallax), Rückkehr mit Overshoot-Settle.',
      importPath: '@/motion-arsenal/effects/cursor/MagneticCTA',
      usageJsx: '<MagneticCTA attractionRadius={110} pullStrength={0.5} />',
      props: [
        { key: 'attractionRadius', label: 'Radius px', type: 'range', default: 110, min: 60, max: 200, step: 5 },
        { key: 'pullStrength', label: 'Pull', type: 'range', default: 0.5, min: 0.1, max: 1, step: 0.05 },
        { key: 'labelParallax', label: 'Label Parallax', type: 'range', default: 0.4, min: 0, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./MagneticCTA')),
  },
  {
    meta: {
      id: 'cursor-light-field',
      name: 'CursorLightField',
      category: 'cursor',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (additive blendFunc(ONE,ONE), gestaffelte Lerp-Follower λ 3/5/8)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Hero-Sektionen', 'Interaktive Feature-Grids'],
      performanceNotes: 'Canvas2D additive Glow-Sprites statt Gradient-Allokationen pro Frame; Loop pausiert offscreen; DPR konfigurierbar.',
      mobileNotes: 'Coarse Pointer nutzt virtuellen Drift, vertikales Scrollen bleibt via pan-y erhalten.',
      reducedMotionNotes: 'Statisches zentriertes Licht ohne Animationsloop.',
      description: 'Additiver Licht-Schleier folgt dem Pointer: mehrere unterschiedlich gedämpfte Follower fächern zu einem organischen Lichtschweif auf, der den Content darunter aufdeckt.',
      importPath: '@/motion-arsenal/effects/cursor/CursorLightField',
      usageJsx: "<CursorLightField lightRadius={140} palette=\"nox\" />",
      props: [
        { key: 'lightRadius', label: 'Radius', type: 'range', default: 140, min: 60, max: 260, step: 10 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 1, min: 0.3, max: 1.5, step: 0.05 },
        { key: 'trailDecay', label: 'Decay', type: 'range', default: 0.16, min: 0.05, max: 0.5, step: 0.01 },
        { key: 'palette', label: 'Palette', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
        { key: 'dprCap', label: 'DPR Cap', type: 'range', default: 1.5, min: 1, max: 2, step: 0.25 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./CursorLightField')),
  },
  {
    meta: {
      id: 'cursor-hover-distortion',
      name: 'HoverDistortionShader',
      category: 'cursor',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Curl-Distortion: uv += curl.xy * strength, noisePos = vec3(uv*2, t*0.5))'],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['Hero-/Portfolio-Flächen', 'Interaktive Poster'],
      performanceNotes: 'Ein WebGL-Fragment-Pass, DPR 1.5 — moderat. Nicht viele Instanzen gleichzeitig.',
      mobileNotes: 'Touch: Auto-Drift des Verzerrungszentrums.',
      reducedMotionNotes: 'Eingefrorener Frame ohne Verzerrungs-Loop.',
      description: 'WebGL-Shader verzerrt ein prozedurales Muster um den Pointer mit Curl-Noise-Offset — die KRANK-Distortion-Mechanik als eigenständige interaktive Fläche.',
      importPath: '@/motion-arsenal/effects/cursor/HoverDistortionShader',
      usageJsx: "<HoverDistortionShader strength={0.18} pattern=\"grid\" />",
      props: [
        { key: 'strength', label: 'Strength', type: 'range', default: 0.18, min: 0, max: 0.4, step: 0.01 },
        { key: 'radius', label: 'Radius', type: 'range', default: 0.35, min: 0.1, max: 0.9, step: 0.05 },
        { key: 'patternScale', label: 'Pattern Scale', type: 'range', default: 14, min: 4, max: 30, step: 1 },
        { key: 'pattern', label: 'Pattern', type: 'select', default: 'grid', options: ['grid', 'stripes'] },
      ],
      productionSafe: true,
      clickToRun: false,
    },
    Component: lazy(() => import('./HoverDistortionShader')),
  },
  {
    meta: {
      id: 'cursor-pointer-parallax-stage',
      name: 'PointerParallaxStage',
      category: 'cursor',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Layering: eine Physik-Quelle treibt DOM+Canvas, damp λ≈10)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Hero-Bühnen', 'Karten-Showcases', 'About-Sektionen'],
      performanceNotes: '4-5 Layer-Transforms in einem Loop — günstig.',
      mobileNotes: 'Touch: sanfte Auto-Bewegung.',
      reducedMotionNotes: 'Statische Bühne mit sichtbarer Tiefenstaffelung.',
      description: 'Mehrschichtige Bühne (Glow, Symbole, Karte, Typo, Grain) mit tiefengestaffeltem Pointer-Parallax und leichter 3D-Rotation — eine gedämpfte Physik-Quelle treibt alle Ebenen.',
      importPath: '@/motion-arsenal/effects/cursor/PointerParallaxStage',
      usageJsx: '<PointerParallaxStage depth={30} tilt={7} />',
      props: [
        { key: 'depth', label: 'Depth px', type: 'range', default: 30, min: 8, max: 60, step: 2 },
        { key: 'tilt', label: 'Tilt °', type: 'range', default: 7, min: 0, max: 16, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 10, min: 3, max: 18, step: 1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./PointerParallaxStage')),
  },
  {
    meta: {
      id: 'cursor-spotlight-reveal',
      name: 'SpotlightReveal',
      category: 'cursor',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Active-Theory-Mechanik: träge Doppel-Follower (λ 4) + radial-gradient Maske'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Teaser-/Mystery-Sektionen', 'Black-Forge-Gate', 'Easter Eggs'],
      performanceNotes: 'mask-image radial-gradient pro Frame — günstig.',
      mobileNotes: 'Touch: Spotlight folgt dem letzten Touch-Punkt.',
      reducedMotionNotes: 'Content voll sichtbar, keine Maske.',
      description: 'Content liegt im Dunkeln; ein Pointer-Spotlight (radiale Maske) deckt auf, ein zweiter trägerer Halo folgt versetzt — versteckte Signal-Details erscheinen nur im Licht.',
      importPath: '@/motion-arsenal/effects/cursor/SpotlightReveal',
      usageJsx: '<SpotlightReveal size={130} darkness={0.92} />',
      props: [
        { key: 'size', label: 'Size px', type: 'range', default: 130, min: 60, max: 240, step: 10 },
        { key: 'haloSize', label: 'Halo px', type: 'range', default: 210, min: 100, max: 360, step: 10 },
        { key: 'darkness', label: 'Darkness', type: 'range', default: 0.92, min: 0.7, max: 1, step: 0.01 },
        { key: 'haloColor', label: 'Halo', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SpotlightReveal')),
  },
  {
    meta: {
      id: 'cursor-interactive-symbol-drift',
      name: 'InteractiveSymbolDrift',
      category: 'cursor',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (Emitter-Partikel, Feder-Rückkehr: vel += (home-pos)*k - vel*damping)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Interaktive Hero-Felder', '404-Seiten', 'Spielerische Sektionen'],
      performanceNotes: 'O(n) Feder-Sim; pausiert offscreen, coarse-pointer Budget max. 30 Glyphen, DPR konfigurierbar.',
      mobileNotes: 'Coarse Pointer nutzt virtuellen Drift mit reduziertem Glyph-Budget; vertikales Scrollen bleibt via pan-y erhalten.',
      reducedMotionNotes: 'Glyphen in Ruhelage, statischer Frame ohne Animationsloop.',
      description: 'Feld prozeduraler Glyphen weicht dem Pointer aus oder folgt ihm (Modus wählbar): Repulsion im Radius, danach federnde Rückkehr zur Ruheposition mit echter Spring-Physik.',
      importPath: '@/motion-arsenal/effects/cursor/InteractiveSymbolDrift',
      usageJsx: "<InteractiveSymbolDrift mode=\"repel\" count={36} />",
      props: [
        { key: 'mode', label: 'Mode', type: 'select', default: 'repel', options: ['repel', 'attract'] },
        { key: 'forceRadius', label: 'Force Radius', type: 'range', default: 120, min: 50, max: 240, step: 10 },
        { key: 'count', label: 'Glyphs', type: 'range', default: 36, min: 12, max: 60, step: 2 },
        { key: 'colorMode', label: 'Colors', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
        { key: 'dprCap', label: 'DPR Cap', type: 'range', default: 1.5, min: 1, max: 2, step: 0.25 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./InteractiveSymbolDrift')),
  },
  {
    meta: {
      id: 'cursor-dodge-button',
      name: 'DodgeButton',
      category: 'cursor',
      sourceWebsite: 'nox-original',
      sourceFiles: ['codemyui „Catch Mouse Pointer When Going to Click a Button" (Konzept)', 'NOX Pointer-Follow-Vokabular (PointerTextDepth, InteractiveSymbolDrift)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Spielerische CTAs', '404-/Easter-Egg-Sektionen', 'Onboarding-Teaser'],
      performanceNotes: 'Ein rAF-Loop (nur Pointer-Tracking), CSS-Transform via translate3d — kein State pro Frame, kein Layout-Trigger.',
      mobileNotes: 'Touch/Stift: kein Dodge (pointerType!==mouse) — Button bleibt normal klickbar.',
      reducedMotionNotes: 'Dodge komplett deaktiviert (rAF-Loop stoppt), Button statisch klickbar; Flash-Animation via Media-Query aus.',
      description: 'Ein Gold-Button weicht dem Mauszeiger aus (gedämpftes Follow, deterministische Richtung aus dem Pointer-Offset) und ergibt sich nach N Annäherungen — dann lässt er sich fangen und bestätigt mit Gold-Flash.',
      importPath: '@/motion-arsenal/effects/cursor/DodgeButton',
      usageJsx: '<DodgeButton dodgeRadius={120} maxDodges={5} />',
      props: [
        { key: 'color', label: 'Gold', type: 'color', default: '#d4a24a' },
        { key: 'dodgeRadius', label: 'Radius px', type: 'range', default: 120, min: 40, max: 260, step: 10 },
        { key: 'dodgeDistance', label: 'Dist px', type: 'range', default: 46, min: 12, max: 120, step: 2 },
        { key: 'maxDodges', label: 'Dodges', type: 'range', default: 5, min: 1, max: 12, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 9, min: 3, max: 18, step: 1 },
        { key: 'label', label: 'Label', type: 'text', default: 'Fang mich' },
        { key: 'successLabel', label: 'Success', type: 'text', default: 'Gefangen ✓' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./DodgeButton')),
  },
  {
    meta: {
      id: 'cursor-label-badge',
      name: 'CursorLabelBadge',
      displayName: 'Cursor Label Badge',
      category: 'cursor',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Cursor DNA', 'Awwwards-Portfolio-Signatur'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Portfolio- und Case-Study-Raster', 'Galerien mit unterschiedlichen Interaktionen', 'Flaechen, deren Bedienung nicht selbsterklaerend ist'],
      performanceNotes: 'Position per Lerp in einer rAF-Schleife, die nur laeuft solange der Zeiger im Feld ist. Transform-only, keine Layout-Animation. Auf Geraeten ohne Hover startet die Schleife gar nicht.',
      mobileNotes: 'Ohne Zeigergeraet entfaellt die Badge vollstaendig; die Labels stehen sichtbar an den Flaechen, die Information geht also nicht verloren.',
      reducedMotionNotes: 'Badge wird nicht eingeblendet, die Kachel-Labels bleiben sichtbar.',
      description: 'Eine kleine Gold-Badge folgt dem Zeiger und wechselt ihre Beschriftung je nachdem, worueber er steht. Die Position wird nachgefedert statt starr gesetzt - das ist der Unterschied zwischen einem Anhaengsel am Cursor und etwas, das reagiert.',
      importPath: '@/motion-arsenal/effects/cursor/CursorLabelBadge',
      usageJsx: '<CursorLabelBadge labels="View / Drag / Explore" size={0.6} />',
      props: [
        { key: 'labels', label: 'Labels (/ trennt)', type: 'text', default: 'View / Drag / Explore', group: 'Content' },
        { key: 'shape', label: 'Badge-Form', type: 'select', default: 'pill', options: ['pill', 'circle', 'square'], group: 'Style' },
        { key: 'size', label: 'Groesse', type: 'range', default: 0.6, min: 0.3, max: 1.5, step: 0.05, group: 'Style' },
        { key: 'speed', label: 'Folge-Tempo', type: 'range', default: 1, min: 0.1, max: 3, step: 0.1, group: 'Motion' },
        { key: 'color', label: 'Farbe', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./CursorLabelBadge')),
  },
  { meta: { id: 'cursor-inverse-glow-cursor', name: 'InverseGlowCursor', displayName: 'Inverse Glow Cursor', category: 'cursor', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Inverse Glow Cursor.md'], mode: 'nox-adapted', complexity: 'low', dependencies: [], bestFor: ['Hero-Flächen', 'Portfolio-Overlays', 'Produkt-Showcases'], performanceNotes: 'Transform-only im rAF-Loop (Spot + Ring), keine Layout-Änderungen pro Frame; blend-mode läuft auf der GPU. Touch-Geräte: Overlay deaktiviert (pointer:coarse).', mobileNotes: 'Auf Touch-Geräten ausgeblendet — kein Stylus-/Finger-Tracking nötig.', reducedMotionNotes: 'Der Ring folgt starr ohne Nachlauf; der invertierende Spot bleibt funktional.', description: 'Invertierter Cursor-Spot mit nachziehendem Akzent-Ring: Der Spot nutzt mix-blend-mode: difference und invertiert die Fläche unter dem Pointer; ein goldener Ring folgt mit elastischem Lag.', importPath: '@/motion-arsenal/effects/cursor/InverseGlowCursor', usageJsx: '<InverseGlowCursor size={96} ringSize={150} lag={0.14} />', props: [{ key: 'size', label: 'Spot-Größe', type: 'range', default: 96, min: 40, max: 160, step: 4 }, { key: 'ringSize', label: 'Ring-Größe', type: 'range', default: 150, min: 60, max: 240, step: 4 }, { key: 'lag', label: 'Nachlauf', type: 'range', default: 0.14, min: 0.02, max: 0.9, step: 0.02 }, { key: 'blend', label: 'Mischmodus', type: 'select', default: 'difference', options: ['difference', 'screen', 'overlay'] }, { key: 'color', label: 'Ring-Farbe', type: 'color', default: '#d4a24a' }, { key: 'showRing', label: 'Akzent-Ring', type: 'boolean', default: true }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./InverseGlowCursor')) },
  { meta: { id: 'cursor-magnetic-grid-navigation', name: 'MagneticGridNavigation', displayName: 'Magnetic Grid Navigation', category: 'cursor', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-magnetic-grid-navigation'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Navigation'], performanceNotes: 'Transform-only magnetic cells.', mobileNotes: 'Tap remains native.', reducedMotionNotes: 'Cells stay still.', description: 'A 3x3 navigation grid magnetizes toward the pointer.', importPath: '@/motion-arsenal/effects/cursor/MagneticGridNavigation', usageJsx: '<MagneticGridNavigation />', props: [], productionSafe: true }, Component: lazy(() => import('./MagneticGridNavigation')) },
];
