import { lazy } from 'react';
import type { EffectEntry } from '../../../types';

export const EDITORIAL_MOSAIC_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'premium-editorial-mosaic',
      name: 'NoxEditorialMosaic',
      displayName: 'Redaktionelles Bildmosaik',
      category: 'premium',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Layout-Muster aus dem NAMIÉ-Kundenbuild, für die Wiederverwendung im Arsenal neutralisiert; keine Kundenassets oder Kundentexte enthalten'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: [
        'Boutique-Wellness- und Studio-Websites',
        'Gastgewerbe- und Interior-Storytelling',
        'Mode- und Markenwelt-Sektionen',
        'Architektur- und Raumkonzepte',
        'Portfolio- und Launch-Kompositionen',
      ],
      performanceNotes: 'Nur DOM/CSS. Fünf responsive Bildkacheln, CSS-Grid, einmalige Einblendung und dezenter Hover-Zoom; keine Canvas-, WebGL- oder dauerhaften rAF-Kosten.',
      mobileNotes: 'Unter 620px wird das Layout zu einer gestaffelten 2-Spalten-Komposition: Hauptbild vollbreit, zwei Detailkacheln, breite Story-Kachel und Band-Kachel. Keine horizontale Scroll-Abhängigkeit.',
      reducedMotionNotes: 'Einblendung und Hover-Übergänge werden vollständig deaktiviert; Layout, Beschriftungen und Wortmarke bleiben unverändert lesbar.',
      description: 'Redaktionelles Fünf-Bild-Mosaik mit großer Hauptkachel, zwei Detailbildern, breiter Story-Kachel und vollbreitem Bildband. Aus einem NOX-Kundenbuild extrahiert, neutralisiert und ohne Kundendaten als wiederverwendbarer Premium-Baustein.',
      currentUsage: ['Musterquelle: NAMIÉ Boutique-Studio-Build. Die wiederverwendbare Arsenal-Version enthält bewusst keine NAMIÉ-/Dilara-Assets, Logo-Pfade, Preise, Aussagen oder Kundentexte.'],
      technicalBasis: 'Responsives CSS-Grid mit stabiler Kachelgeometrie, object-fit-Bildern, optionaler neutraler Wortmarke, CSS-basierter Einstiegsanimation und Reduced-Motion-Fallback.',
      importPath: '@/motion-arsenal/effects/premium/editorial-mosaic/NoxEditorialMosaic',
      usageJsx: '<NoxEditorialMosaic variant="atelier" gap={3} radius={0} showWordmark showLabels motion="subtle" />',
      props: [
        { key: 'variant', label: 'Darstellungsvariante', type: 'select', default: 'atelier', options: ['atelier', 'hospitality', 'portfolio'], group: 'Inhalt' },
        { key: 'eyebrow', label: 'Überzeile', type: 'text', default: 'MARKENWELT', group: 'Inhalt' },
        { key: 'headline', label: 'Überschrift', type: 'text', default: 'Eine Welt in Komposition.', group: 'Inhalt' },
        { key: 'wordmark', label: 'Wortmarke', type: 'text', default: 'NOX', group: 'Marke' },
        { key: 'showWordmark', label: 'Wortmarke anzeigen', type: 'boolean', default: true, group: 'Marke' },
        { key: 'showLabels', label: 'Bildbeschriftungen anzeigen', type: 'boolean', default: true, group: 'Inhalt' },
        { key: 'gap', label: 'Abstand zwischen Kacheln', type: 'range', default: 3, min: 0, max: 18, step: 1, group: 'Layout' },
        { key: 'radius', label: 'Eckenradius', type: 'range', default: 0, min: 0, max: 28, step: 1, group: 'Layout' },
        { key: 'motion', label: 'Bewegung', type: 'select', default: 'subtle', options: ['subtle', 'still'], group: 'Bewegung' },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-08-13T13:15:00.000Z',
      lastImprovedBy: 'chatgpt-gpt-5.6-sol',
      improvementVersion: '1.0.1',
      improvementChangelog: [
        'Freigegebene asymmetrische Fünf-Bild-Komposition aus dem NAMIÉ-Kundenbuild als neutralen Arsenal-Effekt extrahiert.',
        'Alle kundenspezifischen Assets und Texte entfernt; neutrale Vorschauinhalte und drei wiederverwendbare Varianten ergänzt.',
        'Responsive Tablet-/Mobile-Kompositionen, Reduced-Motion-Fallback sowie optionale Beschriftungen und Wortmarke ergänzt.',
        'Sichtbare Bezeichnungen, Regler, Beschreibung und Änderungsprotokoll vollständig auf Deutsch vereinheitlicht.',
      ],
      productionSafe: true,
      status: 'candidate',
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxEditorialMosaic')),
  },
];
