import { useEffect, useRef, useState } from 'react';
import type React from 'react';
export interface RotatingScrollImages3DProps { images?: string[]; depth?: number; speed?: number; gap?: number; }
const fallback = ['#d4a24a','#33425e','#78513b','#263d39'];
export default function RotatingScrollImages3D({ images = [], depth = .5, speed = 1, gap = .5 }: RotatingScrollImages3DProps) {
  const ref = useRef<HTMLElement>(null); const [progress, setProgress] = useState(0); const reduced = typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  useEffect(() => { if (reduced) return; const onScroll = () => { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); setProgress(Math.max(0, Math.min(1, (innerHeight - r.top) / (innerHeight + r.height)))); }; addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => removeEventListener('scroll', onScroll); }, [reduced]);
  const tilt = reduced ? 0 : (progress - .5) * 70 * speed; const list = images.length ? images : fallback;
  const style = { '--rsi-gap': `${Math.max(.2, Math.min(1, gap)) * 2}rem`, '--rsi-depth': `${Math.max(0, Math.min(1, depth)) * 120}px` } as React.CSSProperties;
  return <section ref={ref} className="nox-rsi" style={style} aria-label="3D rotating scroll gallery"><style>{CSS}</style><div className="nox-rsi__track">{list.slice(0, 8).map((image, i) => <figure key={`${image}-${i}`} className="nox-rsi__card" style={{ transform: `rotateY(${tilt + (i - (list.length - 1) / 2) * 8}deg) translateZ(${Math.cos((i + progress) * 1.8) * 25}px)`, background: image.startsWith('#') ? image : undefined }}><div className="nox-rsi__image" style={image.startsWith('#') ? undefined : { backgroundImage: `url(${image})` }} /><figcaption>FRAME {String(i + 1).padStart(2, '0')}</figcaption></figure>)}</div></section>;
}
const CSS = String.raw`.nox-rsi{min-height:360px;display:grid;place-items:center;overflow:hidden;background:#08090d;color:#f7e8a4;perspective:1100px}.nox-rsi__track{display:flex;align-items:center;gap:var(--rsi-gap);transform-style:preserve-3d}.nox-rsi__card{width:clamp(105px,19vw,190px);aspect-ratio:.72;margin:0;position:relative;overflow:hidden;border:1px solid #d4a24a88;box-shadow:0 22px 50px #0008;backface-visibility:hidden;transform-style:preserve-3d;transition:transform .18s ease-out}.nox-rsi__image{position:absolute;inset:0;background:linear-gradient(145deg,#1d2434,#08090d 70%);background-size:cover;background-position:center;filter:saturate(.7) contrast(1.1)}.nox-rsi__card:after{content:'';position:absolute;inset:0;background:linear-gradient(135deg,#f7e8a433,transparent 34%,#0008)}.nox-rsi figcaption{position:absolute;z-index:1;bottom:10px;left:11px;font:10px var(--mono,monospace);letter-spacing:.15em;opacity:.72}@media(prefers-reduced-motion:reduce){.nox-rsi__card{transition:none!important}}`;
