import { lazy } from 'react';
import type { EffectEntry } from '../../types';

// ---------------------------------------------------------------------------
// NOX Forge Skilltree Systems (2026-07-05).
// Single Source für Skilltree-/Dashboard-FX-Experimente. Rekonstruiert und
// perfektioniert aus dem Forge-Design-Lab-Pass (?designLab=1) — hier werden
// die Effekte verglichen und freigegeben, BEVOR sie sauber in NOX Forge
// (Produkt) übernommen werden. Alles CSS/SVG/React-only, kein WebGL.
// ---------------------------------------------------------------------------

export const FORGE_SKILLTREE_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'skilltree-astral-constellation',
      name: 'Astral Skilltree Constellation',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (?designLab=1, Variante „Astral Skilltree")'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Skilltree-Hauptansicht', 'Systemkarte im Dashboard', 'Onboarding-Wow-Moment'],
      performanceNotes: 'Pure CSS + SVG: Float/Puls über transform/opacity, Pfad-Fluss über stroke-dashoffset. 0 rAF, 0 Canvas. Light.',
      mobileNotes: 'Nodes skalieren auf 80% (<640px), Labels kompakter, kein H-Overflow (Prozent-Layout).',
      reducedMotionNotes: 'Alle Loops (Float, Puls, Ring, Fluss, Twinkle) aus — statische, voll lesbare Konstellation.',
      description:
        'Die Voll-Demo: schwebende Skill-Nodes als Konstellation um einen Root-Node, Sternfeld + Signal-Partikel als Atmosphäre, gebogene SVG-Energiepfade, deren Stil dem Node-State folgt (aktiv fließt, gesperrt dimmt, Risiko rot gestrichelt). Alle 6 Node-States in einem Bild — die Referenz für das Skilltree-Zielgefühl.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/AstralSkilltreeConstellation',
      usageJsx: '<AstralSkilltreeConstellation nodeCount={6} speed={1} stars={40} showLabels />',
      props: [
        { key: 'nodeCount', label: 'Nodes', type: 'range', default: 6, min: 1, max: 6, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
        { key: 'stars', label: 'Stars', type: 'range', default: 40, min: 0, max: 80, step: 5 },
        { key: 'showLabels', label: 'Labels', type: 'boolean', default: true },
      ],
      productionSafe: true,
      status: 'candidate',
      fullBleed: true,
    },
    Component: lazy(() => import('./AstralSkilltreeConstellation')),
  },
  {
    meta: {
      id: 'skilltree-floating-nodes',
      name: 'Floating Skill Nodes',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-float Grundmechanik)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Skilltree-Nodes', 'Feature-Icons', 'Dashboard-Orbit'],
      performanceNotes: 'Nur transform:translateY im alternate-Loop, versetzte Phasen über negative animation-delays. Praktisch kostenlos.',
      mobileNotes: 'Unverändert lauffähig; Distanz ggf. auf 4–5px senken, damit nichts wackelig wirkt.',
      reducedMotionNotes: 'Float aus — Nodes stehen ruhig an ihrer Position.',
      description:
        'Das Schwebe-Fundament isoliert: Nodes driften mit individueller Dauer und Phase vertikal (3D-/Game-Gefühl ohne WebGL), Hover skaliert den Kern weich. Baustein für jede Konstellation.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/FloatingSkillNodes',
      usageJsx: '<FloatingSkillNodes count={5} floatDistance={7} floatSpeed={6} />',
      props: [
        { key: 'count', label: 'Count', type: 'range', default: 5, min: 2, max: 8, step: 1 },
        { key: 'floatDistance', label: 'Float (px)', type: 'range', default: 7, min: 2, max: 14, step: 1 },
        { key: 'floatSpeed', label: 'Cycle (s)', type: 'range', default: 6, min: 3, max: 10, step: 0.5 },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./FloatingSkillNodes')),
  },
  {
    meta: {
      id: 'skilltree-active-pulse-ring',
      name: 'Active Node Pulse Ring',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-node--active)', 'Forge index.css (forge-unlock-ring Lineage)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Aktive Quest im Skilltree', 'Laufender Prozess', '„Hier bist du"-Marker'],
      performanceNotes: 'Ein box-shadow-Puls + ein auslaufender ::after-Ring (transform/opacity). Light; box-shadow-Animation auf sehr vielen Nodes gleichzeitig vermeiden (Repaint).',
      mobileNotes: 'Unverändert; Ring bleibt sichtbar, Größe skaliert mit Node.',
      reducedMotionNotes: 'Puls + Ring aus — der Aktiv-State bleibt über den statischen Glow erkennbar.',
      description:
        'Der Aktiv-Zustand isoliert: der Node-Kern atmet über einen Glow-Puls, ein Energiering läuft alle ~2s nach außen aus. Daneben ein ruhender Available-Node als direkter Kontrast — so sieht man genau, was „aktiv" hinzufügt.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/ActiveNodePulseRing',
      usageJsx: '<ActiveNodePulseRing pulseSpeed={1} size={64} />',
      props: [
        { key: 'pulseSpeed', label: 'Pulse Speed', type: 'range', default: 1, min: 0.4, max: 2.5, step: 0.1 },
        { key: 'size', label: 'Node Size', type: 'range', default: 64, min: 40, max: 90, step: 2 },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./ActiveNodePulseRing')),
  },
  {
    meta: {
      id: 'skilltree-recommended-focus-ring',
      name: 'Recommended Node Focus Ring',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-node--recommended)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['„Von NOX empfohlen"-Pfad', 'Next-Best-Action-Marker', 'Onboarding-Fokus'],
      performanceNotes: 'Ein rotierender dashed-Border-Ring (transform:rotate) + statischer Glow. Light.',
      mobileNotes: 'Badge bleibt lesbar (nowrap); bei sehr engen Karten Badge optional ausblenden.',
      reducedMotionNotes: 'Rotation aus — der gestrichelte Ring + Badge bleiben statisch sichtbar.',
      description:
        'Der Empfohlen-Zustand: ein langsam rotierender, gestrichelter Gold-Ring umkreist den Node wie ein Zielfernrohr, darunter das „Von NOX empfohlen"-Badge. Zwischen Locked und Available platziert, damit die Blickführung direkt vergleichbar ist.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/RecommendedNodeFocusRing',
      usageJsx: '<RecommendedNodeFocusRing spinSpeed={1} showBadge />',
      props: [
        { key: 'spinSpeed', label: 'Spin Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'showBadge', label: 'Badge', type: 'boolean', default: true },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./RecommendedNodeFocusRing')),
  },
  {
    meta: {
      id: 'skilltree-locked-path-shadow',
      name: 'Locked Path Shadow',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-node--locked + Locked-Veil-Idee)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Gesperrte Skilltree-Äste', 'Pro-/Tier-Gating visuell', 'Progression-Storytelling'],
      performanceNotes: 'Statischer radialer Dunkel-Veil + gedimmte Pfade + entsättigte Nodes. 0 Animationen im Locked-Bereich — bewusst tot.',
      mobileNotes: 'Veil skaliert mit; Layout prozentbasiert, kein Overflow.',
      reducedMotionNotes: 'Ohnehin fast statisch; der aktive Pfad links verliert nur seinen Fluss.',
      description:
        'Gesperrte Pfade liegen im Schatten: ein radialer Dunkelschleier legt sich über den gesperrten Ast, die Verbindungslinien dimmen auf 8% Weiß, die Nodes verlieren Farbe und Float. Der Kontrast erhellter Pfad ↔ toter Ast erzählt Progression ohne ein einziges Wort.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/LockedPathShadow',
      usageJsx: '<LockedPathShadow veilStrength={0.55} />',
      props: [
        { key: 'veilStrength', label: 'Veil Strength', type: 'range', default: 0.55, min: 0, max: 0.85, step: 0.05, group: 'Veil' },
        { key: 'scanDirection', label: 'Scan Direction', type: 'select', default: 'left-to-right', options: ['left-to-right', 'right-to-left', 'top-to-bottom'], group: 'Scan' },
        { key: 'scanSpeed', label: 'Scan Speed', type: 'range', default: 1, min: 0.3, max: 2.5, step: 0.1, group: 'Scan' },
        { key: 'nodeShape', label: 'Node Shape', type: 'select', default: 'circle', options: ['circle', 'hex', 'diamond'], group: 'Shape' },
        { key: 'dustCount', label: 'Dust Density', type: 'range', default: 32, min: 0, max: 64, step: 4, group: 'Atmosphere' },
        { key: 'shadowColor', label: 'Shadow Tone', type: 'color', default: '#cb97f2', group: 'Color' },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-08-09T02:00:00.000Z',
      lastImprovedBy: 'skilltree',
      improvementVersion: '1.1.0',
      improvementChangelog: [
        'Scanstrahl laeuft wahlweise nach rechts, nach links oder von oben nach unten.',
        'Scan-Tempo regelbar, ohne die Choreografie der Enthuellung zu veraendern.',
        'Gesperrte Knoten als Kreis, Hexagon oder Raute.',
        'Staubdichte von 0 bis 64 einstellbar, Grundton des Schattens frei waehlbar.',
      ],
      productionSafe: true,
      status: 'candidate',
      fullBleed: true,
    },
    Component: lazy(() => import('./LockedPathShadow')),
  },
  {
    meta: {
      id: 'skilltree-corrupted-risk-glitch',
      name: 'Corrupted / Risk Node Glitch',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-node--corrupted)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Risiko-Muster im Skilltree', '„Blockiert durch Muster"-Marker', 'Verhaltens-Widerspruch sichtbar machen'],
      performanceNotes: 'Ein translateX-Zucken (4% des Keyframe-Zyklus) + roter Glow-Spike. Light — kein Dauerflackern, kein Filter-Einsatz.',
      mobileNotes: 'Unverändert; Glitch-Auslenkung ist absolut (px), wirkt auf kleinen Nodes etwas stärker.',
      reducedMotionNotes: 'Glitch aus — der Risiko-State bleibt über rote Border/Glow statisch erkennbar.',
      description:
        'Der Risiko-Zustand: der Node zuckt einmal pro langsamem Zyklus kurz horizontal, der rote Glow spiked mit — gefährlich, aber nicht billig, weil 96% des Zyklus Ruhe sind. Der zugehörige rote, gestrichelte Pfad verbindet das Muster mit dem Ziel, das es blockiert.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/CorruptedRiskNodeGlitch',
      usageJsx: '<CorruptedRiskNodeGlitch glitchIntensity={1} cycleSpeed={1} />',
      props: [
        { key: 'glitchIntensity', label: 'Glitch Intensity', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'cycleSpeed', label: 'Cycle Speed', type: 'range', default: 1, min: 0.4, max: 2.5, step: 0.1 },
      ],
      productionSafe: true,
      status: 'candidate',
    },
    Component: lazy(() => import('./CorruptedRiskNodeGlitch')),
  },
  {
    meta: {
      id: 'skilltree-svg-energy-lines',
      name: 'SVG Energy Lines Flow',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-link--flow)', 'NoxTimelineOrchestrator (stroke-dashoffset-Prinzip)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Node-Verbindungen', 'Fortschritts-Fluss', 'Pipeline-/Pfad-Visualisierung'],
      performanceNotes: 'Nur stroke-dashoffset-Animation auf SVG-Pfaden — GPU-freundlich, beliebig viele Linien möglich. Extrem light.',
      mobileNotes: 'vectorEffect=non-scaling-stroke hält Linien auf jeder Breite gleich fein.',
      reducedMotionNotes: 'Fluss aus — Linien bleiben statisch leuchtend (Zustand bleibt lesbar).',
      description:
        'Die Energiepfade isoliert: gebogene SVG-Quadratic-Pfade mit wanderndem Dash-Muster — der Fortschritt fließt sichtbar durch die Verbindung Richtung Ziel. Gold-fließend vs. rot-gestrichelt (Risiko) im direkten Vergleich, jede Linie mit leicht eigener Geschwindigkeit.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/SvgEnergyLinesFlow',
      usageJsx: '<SvgEnergyLinesFlow lineCount={5} flowSpeed={1} />',
      props: [
        { key: 'lineCount', label: 'Lines', type: 'range', default: 5, min: 2, max: 9, step: 1 },
        { key: 'flowSpeed', label: 'Flow Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./SvgEnergyLinesFlow')),
  },
  {
    meta: {
      id: 'skilltree-progress-energy-ring',
      name: 'Progress Energy Ring',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (dl-ring)', 'system/ProgressRingCharge (conic-Schwester)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['XP zur nächsten Stufe', 'Skill-Level-Fortschritt', 'Dashboard-Meilenstein-Karte'],
      performanceNotes: 'SVG-Kreis mit stroke-dashoffset + CSS-Transition (1s cubic-bezier) — animiert nur beim Wertwechsel, danach 0 Kosten.',
      mobileNotes: 'Frei skalierbar über size-Prop; Text skaliert mit.',
      reducedMotionNotes: 'Transition bleibt (einmalig, kein Loop) — bei Bedarf per transition:none abschaltbar.',
      description:
        'Der stroke-basierte Fortschrittsring mit Glow (drop-shadow auf dem Füllkreis): lädt beim Mount weich auf den Zielwert. Die ruhige Schwester des conic-ProgressRingCharge — für Dashboards, wo der Ring dauerhaft steht statt zu performen.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/ProgressEnergyRing',
      usageJsx: '<ProgressEnergyRing value={65} size={140} />',
      props: [
        { key: 'value', label: 'Value (%)', type: 'range', default: 65, min: 0, max: 100, step: 1 },
        { key: 'size', label: 'Size (px)', type: 'range', default: 140, min: 80, max: 220, step: 5 },
        { key: 'strokeWidth', label: 'Stroke', type: 'range', default: 5, min: 3, max: 10, step: 0.5 },
        { key: 'animateIn', label: 'Animate In', type: 'boolean', default: true },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./ProgressEnergyRing')),
  },
  {
    meta: {
      id: 'skilltree-border-trace-quest-card',
      name: 'Border Trace Quest Card',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['cards/BorderTraceDepth (Mechanik-Vorlage)', 'NOX Forge Design-Lab (dl-trace CSS-only-Variante)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Aktive Quest-Karte', 'Laufende Mission', '„Hier passiert gerade etwas"-Panel'],
      performanceNotes: 'CSS-only-Variante des BorderTrace: conic-gradient-Ringmaske, Winkel via @property animiert — 0 rAF (im Gegensatz zur JS-Variante in cards/). Fallback ohne @property: Ring statisch.',
      mobileNotes: 'Karten stapeln bei Enge (flex-wrap); Trace unverändert.',
      reducedMotionNotes: 'Rotation aus — die aktive Karte behält den statischen Goldrahmen.',
      description:
        'Die aktive Quest-Karte: ein rotierender conic-Lichtkopf läuft als schmale Ringmaske um die Glass-Karte — daneben eine erledigte Karte ohne Trace als Ruhe-Kontrast. Genau der Moment „diese eine Sache läuft jetzt" im Dashboard.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/BorderTraceQuestCard',
      usageJsx: "<BorderTraceQuestCard traceSpeed={1} accent=\"#d4af37\" />",
      props: [
        { key: 'traceSpeed', label: 'Trace Speed', type: 'range', default: 1, min: 0.3, max: 3, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4af37' },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./BorderTraceQuestCard')),
  },
  {
    meta: {
      id: 'skilltree-glass-metal-panel',
      name: 'Glass/Metal Skilltree Panel',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['cards/GlassMetalPanel (Vorlage)', 'NOX Forge Design-Lab (dl-glass)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Systemkarte-Container', 'Dashboard-Panels', 'Stat-Karten'],
      performanceNotes: 'backdrop-filter:blur ist der einzige Kostenpunkt — auf wenigen großen Panels fein, nicht auf 30 kleinen Karten gleichzeitig stapeln.',
      mobileNotes: 'Blur ggf. auf 6px senken (ältere Geräte); Panel bleibt ohne backdrop-filter-Support einfach dunkel-transparent.',
      reducedMotionNotes: 'Keine Loops enthalten; Hover-Lift ist eine einmalige Transition.',
      description:
        'Das Skilltree-Panel als Glass/Metal-Fläche: transluzenter Grund mit backdrop-blur über der Atmosphäre, eine Metall-Lichtkante oben, Hover hebt das Panel mit Glow-Schatten an. Mini-Nodes im Panel zeigen den Einsatz als Systemkarte.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/GlassMetalSkilltreePanel',
      usageJsx: '<GlassMetalSkilltreePanel blur={9} hoverLift />',
      props: [
        { key: 'blur', label: 'Blur (px)', type: 'range', default: 9, min: 0, max: 18, step: 1 },
        { key: 'hoverLift', label: 'Hover Lift', type: 'boolean', default: true },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./GlassMetalSkilltreePanel')),
  },
  {
    meta: {
      id: 'skilltree-particle-atmosphere-light',
      name: 'Particle Atmosphere Light',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['backgrounds/DepthGlowLayerStack (CSS-Atmosphäre-Prinzip)', 'premium/NoxSignalParticles (Ideengeber, hier ohne Canvas)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Unterlage für Skilltree/Dashboard', 'Sektion-Atmosphäre', 'Hero-Ruhe-Layer'],
      performanceNotes: 'Radiale Gradients + kleine CSS-Partikel/Sterne (transform/opacity-Loops). 0 rAF, 0 Canvas — die billigste Atmosphäre im Arsenal.',
      mobileNotes: 'Partikelzahl über Props senken; Ember-Klasse ist mobil ohnehin ausgeblendet.',
      reducedMotionNotes: 'Drift + Twinkle aus — Gradients bleiben als statische Atmosphäre.',
      description:
        'Die leichteste Atmosphäre: violett-goldene Glow-Gradients plus deterministisch platzierte, driftende Lichtpunkte und funkelnde Sterne. Gedacht als Unterlage, auf der Glass-Panels und Konstellationen erst Tiefe bekommen.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/ParticleAtmosphereLight',
      usageJsx: '<ParticleAtmosphereLight particles={20} stars={30} />',
      props: [
        { key: 'particles', label: 'Particles', type: 'range', default: 20, min: 0, max: 60, step: 2 },
        { key: 'stars', label: 'Stars', type: 'range', default: 30, min: 0, max: 80, step: 5 },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./ParticleAtmosphereLight')),
  },
  {
    meta: {
      id: 'skilltree-forge-chamber-hard-mode',
      name: 'Forge Chamber Hard Mode Variant',
      category: 'forge-skilltree',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Forge Design-Lab (Variante „Forge Chamber")'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Black Forge / Hard Mode', 'Elite-Protokoll-Ansicht', 'Sprint-Tracking'],
      performanceNotes: 'Wie die Astral-Variante (CSS/SVG-only) plus Ember-Partikel (transform/opacity-Aufstieg). Light; Ember mobil per CSS aus.',
      mobileNotes: 'Ember ausgeblendet (<640px), Nodes kompakter, prozentbasiertes Layout ohne Overflow.',
      reducedMotionNotes: 'Alle Loops inkl. Ember aus — die Kammer steht als statisches Tableau.',
      description:
        'Die harte Schwester der Konstellation für Black Forge: rote Ember-Funken steigen aus der Tiefe auf, die Node-Kerne werden kantig (Ritual-Siegel statt Orbs), rot-goldene Pfade um das zentrale Protokoll, ein Risiko-Muster hängt sichtbar im Ast. Ritualisiert, metallisch, kompromisslos.',
      importPath: '@/motion-arsenal/effects/forge-skilltree/ForgeChamberHardMode',
      usageJsx: '<ForgeChamberHardMode embers={14} speed={1} />',
      props: [
        { key: 'embers', label: 'Embers', type: 'range', default: 14, min: 0, max: 30, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
      ],
      productionSafe: true,
      status: 'candidate',
      fullBleed: true,
    },
    Component: lazy(() => import('./ForgeChamberHardMode')),
  },
];
