import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SCROLL_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'scroll-pinned-product-stage',
      name: 'PinnedProductStageCoreSystem',
      displayName: 'Product Stage Variant System',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: [
        'Shopify Szenen-Mechanik (Theatre.js: scroll → Timeline-Frame)',
        'PinnedProductStageVariants.tsx (NOX preset registry)',
        'PinnedProductStageCoreSystem.tsx (five semantic core artifacts)',
        'public/agent-manifests/pinned-product-stage-variants.json',
      ],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['NOX Produktpräsentationen', 'High-Ticket-Angebote', 'Agenten-Systeme', 'Kunden-Landingpages'],
      performanceNotes: 'Eine sticky Stage, transform-basierte Produkt-Layer und ein gedämpfter rAF-Loop; die Core-Artefakte laufen vollständig über CSS/SVG. Rotation, Licht, Hintergrund und Stufen-Visuals hängen an CSS-Variablen — ein Frame schreibt eine Transform plus acht Variablen, unabhängig von der Anzahl der Controls. Ambient-Partikel sind DOM-Punkte mit CSS-Drift, kein zweiter Canvas; im Page-Modus pausieren die Frames ausserhalb des Viewports.',
      mobileNotes: 'Touch-Scroll, horizontale Preset-Auswahl und kompakter Content-Stack sind integriert. Eigene Mobile-Regler: mobileRotationTurns (Default 0.25 statt 0.85), mobileObjectScale, mobileEffectsQuality (low blendet Ambient-Partikel und Atmosphäre aus) und disableRotationOnMobile. Die Umschaltung hängt an der Boxbreite (<700px), nicht am Viewport — die Vorschau im Arsenal verhält sich dadurch wie die echte Einbindung.',
      reducedMotionNotes: 'Kein rAF-Loop. reducedMotionRotation bestimmt den Standbildzustand: off = reine Basisrotation, stage-only = Basisrotation plus die Rotation der letzten Stufe, static = vollständiger Endzustand. Presets, Core-Formen und Referenzcodes bleiben bedienbar.',
      description: 'Referenzierbares Produkt-Story-System mit sechs fertigen NOX-Presets (inkl. nox-revenue-os für noxlabs.net) und zwei Scroll-Treibern: interner Scrollport für die Arsenal-Vorschau, `scrollDriver="page"` für echte Webseiten, wo die Stage im Dokumentfluss gepinnt wird statt das Mausrad einzufangen. Jede Variante besitzt eigene Kapitel, Module, Kennzahlen, CTA, stabile Agenten-Referenz und ein sichtbar anderes semantisches Kernobjekt: Revenue Reactor, Agent Nexus, Signal Nucleus, Conversion Prism oder Automation Kernel.',
      currentUsage: ['NOX Labs Produktpräsentation', 'Project-X Agentenzentrale', 'zukünftige Kundenwebseiten'],
      technicalBasis: 'Sticky scroll timeline + CSS-3D layers + five semantic CSS/SVG core artifacts + exported preset registry + public agent manifest. Zwei Rotationsmodi: `free-spin` (progress x turns x 360, für abstrakte Kernobjekte) und `depth-flip` (pro Kapitel 0 → readableAngle → 0 plus stackDrift über die Sektion, für lesbare Tafeln — der Winkel bleibt unter der 90°-Kante, deshalb wird die Fläche nie zur Linie und die Rückseite nie sichtbar).',
      importPath: '@/motion-arsenal/effects/scroll/PinnedProductStageCoreSystem',
      usageJsx: '<PinnedProductStageCoreSystem variant="nox-revenue-os" scrollRotationEnabled rotationMode="depth-flip" readableAngle={55} stackDrift={16} rotationAxis="y" stageRotationInfluence={0.35} rotationSmoothing={0.12} perspective={1100} objectTilt={6} glow={0.6} bloom={0.35} />',
      props: [
        {
          key: 'variant',
          label: 'Product Variant',
          type: 'select',
          default: 'nox-global-sales-os',
          options: [
            'nox-floating-card-os',
            'nox-revenue-os',
            'nox-scroll-story',
            'nox-global-sales-os',
            'project-x-command-center',
            'ai-growth-engine',
            'conversion-website-system',
            'automation-ops-system',
          ],
          group: 'Content',
        },

        { key: 'layoutMode', label: 'Layout Mode', type: 'select', default: 'pinned-stage', options: ['pinned-stage', 'sticky-story'], group: 'Sticky Story' },
        { key: 'chapterHeight', label: 'Story Chapter Height (vh)', type: 'range', default: 68, min: 45, max: 100, step: 1, group: 'Sticky Story' },
        { key: 'stickyOffset', label: 'Sticky Offset (vh)', type: 'range', default: 0, min: 0, max: 20, step: 1, group: 'Sticky Story' },
        { key: 'activeThreshold', label: 'Active Threshold', type: 'range', default: 0.42, min: 0.2, max: 0.8, step: 0.01, group: 'Sticky Story' },
        // panelTilt ist im Code ein Tupel; die Oberfläche steuert beide Achsen
        // einzeln und bleibt damit im serialisierbaren Control-Schema.
        { key: 'panelTiltX', label: 'Panel Tilt X (°)', type: 'range', default: 4, min: 0, max: 6, step: 1, group: 'Sticky Story' },
        { key: 'panelTiltY', label: 'Panel Tilt Y (°)', type: 'range', default: -6, min: -14, max: 14, step: 1, group: 'Sticky Story' },
        { key: 'panelDepth', label: 'Panel Depth (px)', type: 'range', default: -30, min: -80, max: 0, step: 5, group: 'Sticky Story' },
        { key: 'contentTransition', label: 'Content Transition (ms)', type: 'range', default: 160, min: 100, max: 180, step: 10, group: 'Sticky Story' },
        { key: 'textReveal', label: 'Text Reveal', type: 'select', default: 'blur-rise', options: ['blur-rise', 'fade', 'none'], group: 'Sticky Story' },
        { key: 'mobileStack', label: 'Mobile Stack', type: 'boolean', default: true, group: 'Sticky Story' },
        { key: 'showVariantSwitcher', label: 'Show Variant Switcher', type: 'boolean', default: true, group: 'Content' },
        { key: 'chrome', label: 'Chrome', type: 'select', default: 'demo', options: ['demo', 'minimal'], group: 'Content' },
        { key: 'stage', label: 'Fixed Stage (-1 = Scroll)', type: 'range', default: -1, min: -1, max: 4, step: 1, group: 'Content' },
        { key: 'autoProgress', label: 'Auto Progress', type: 'boolean', default: false, group: 'Content' },
        { key: 'autoProgressSpeed', label: 'Auto Progress Speed (s/Kapitel)', type: 'range', default: 2.4, min: 0.6, max: 8, step: 0.1, group: 'Content' },
        { key: 'pageScrollMode', label: 'Page Scroll Mode', type: 'boolean', default: false, group: 'Content' },
        { key: 'showStepNavigation', label: 'Show Step Navigation', type: 'boolean', default: true, group: 'Content' },
        { key: 'showLabels', label: 'Show Labels', type: 'boolean', default: true, group: 'Content' },
        { key: 'compactScroll', label: 'Chapter Height (vh)', type: 'range', default: 0.78, min: 0.55, max: 1.2, step: 0.01, group: 'Content' },

        { key: 'scrollDriver', label: 'Scroll Driver', type: 'select', default: 'internal', options: ['internal', 'page'], group: 'Scroll' },
        { key: 'scrollLength', label: 'Scroll Length (vh, 0 = auto)', type: 'range', default: 0, min: 0, max: 8, step: 0.1, group: 'Scroll' },
        { key: 'scrollSmoothing', label: 'Scroll Smoothing', type: 'range', default: 0.18, min: 0, max: 0.9, step: 0.01, group: 'Scroll' },
        { key: 'stageSnapStrength', label: 'Stage Snap Strength', type: 'range', default: 0, min: 0, max: 1, step: 0.05, group: 'Scroll' },
        { key: 'stageTransitionDuration', label: 'Stage Transition Duration (s)', type: 'range', default: 0.5, min: 0.1, max: 1.6, step: 0.05, group: 'Scroll' },

        { key: 'scrollRotationEnabled', label: 'Scroll Rotation', type: 'boolean', default: true, group: 'Object Rotation' },
        { key: 'rotationMode', label: 'Rotation Mode', type: 'select', default: 'free-spin', options: ['free-spin', 'depth-flip'], group: 'Object Rotation' },
        { key: 'readableAngle', label: 'Readable Angle (°, depth-flip)', type: 'range', default: 55, min: 15, max: 80, step: 1, group: 'Object Rotation' },
        { key: 'stackDrift', label: 'Stack Drift (°, depth-flip)', type: 'range', default: 16, min: 0, max: 60, step: 1, group: 'Object Rotation' },
        { key: 'rotationAxis', label: 'Rotation Axis', type: 'select', default: 'y', options: ['x', 'y', 'z', 'xy', 'xyz'], group: 'Object Rotation' },
        { key: 'rotationTurns', label: 'Rotation Turns (free-spin)', type: 'range', default: 0.85, min: 0, max: 4, step: 0.05, group: 'Object Rotation' },
        { key: 'rotationDirection', label: 'Rotation Direction', type: 'select', default: 'clockwise', options: ['clockwise', 'counter-clockwise'], group: 'Object Rotation' },
        { key: 'baseRotationX', label: 'Base Rotation X (°)', type: 'range', default: 0, min: -180, max: 180, step: 1, group: 'Object Rotation' },
        { key: 'baseRotationY', label: 'Base Rotation Y (°)', type: 'range', default: 0, min: -180, max: 180, step: 1, group: 'Object Rotation' },
        { key: 'baseRotationZ', label: 'Base Rotation Z (°)', type: 'range', default: 0, min: -180, max: 180, step: 1, group: 'Object Rotation' },
        { key: 'stageRotationInfluence', label: 'Stage Rotation Influence', type: 'range', default: 0.35, min: 0, max: 1, step: 0.05, group: 'Object Rotation' },
        { key: 'rotationSmoothing', label: 'Rotation Smoothing', type: 'range', default: 0.12, min: 0, max: 0.9, step: 0.01, group: 'Object Rotation' },

        { key: 'objectScale', label: 'Object Scale', type: 'range', default: 1, min: 0.4, max: 2, step: 0.05, group: 'Object Presentation' },
        { key: 'objectDepth', label: 'Object Depth', type: 'range', default: 1, min: 0, max: 2.5, step: 0.05, group: 'Object Presentation' },
        { key: 'perspective', label: 'Perspective (px)', type: 'range', default: 1100, min: 400, max: 2600, step: 50, group: 'Object Presentation' },
        { key: 'cameraDistance', label: 'Camera Distance (px)', type: 'range', default: 0, min: -300, max: 400, step: 10, group: 'Object Presentation' },
        { key: 'objectTilt', label: 'Object Tilt (°)', type: 'range', default: 6, min: -30, max: 30, step: 1, group: 'Object Presentation' },
        { key: 'objectFloat', label: 'Object Float (px)', type: 'range', default: 0, min: 0, max: 40, step: 1, group: 'Object Presentation' },
        { key: 'objectFloatSpeed', label: 'Object Float Speed', type: 'range', default: 0.5, min: 0.05, max: 2, step: 0.05, group: 'Object Presentation' },
        { key: 'cardStyle', label: 'Card Style', type: 'select', default: 'glass', options: ['glass', 'obsidian', 'signal'], group: 'Floating Card OS' },
        { key: 'stageCardVariant', label: 'Stage Card Variant', type: 'select', default: 'auto', options: ['auto', 'radar', 'score', 'mutation', 'timeline', 'command'], group: 'Floating Card OS' },
        { key: 'cardScale', label: 'Card Scale', type: 'range', default: 1.12, min: 0.6, max: 1.8, step: 0.05, group: 'Floating Card OS' },
        { key: 'cardTilt', label: 'Card Tilt', type: 'range', default: 5, min: -18, max: 18, step: 1, group: 'Floating Card OS' },
        { key: 'cardFloat', label: 'Card Float', type: 'range', default: 8, min: 0, max: 24, step: 1, group: 'Floating Card OS' },
        { key: 'cardFloatSpeed', label: 'Card Float Speed', type: 'range', default: 0.16, min: 0.05, max: 0.8, step: 0.01, group: 'Floating Card OS' },
        { key: 'scrollRotationTurns', label: 'Scroll Rotation Turns', type: 'range', default: 0.18, min: 0, max: 1, step: 0.01, group: 'Floating Card OS' },
        { key: 'morphStrength', label: 'Morph Strength', type: 'range', default: 0.8, min: 0, max: 1.5, step: 0.05, group: 'Floating Card OS' },
        { key: 'stageSpread', label: 'Stage Spread', type: 'range', default: 0.9, min: 0.4, max: 1.6, step: 0.05, group: 'Floating Card OS' },
        { key: 'depth', label: 'Depth', type: 'range', default: 1, min: 0.2, max: 2, step: 0.05, group: 'Floating Card OS' },
        { key: 'showHud', label: 'Show HUD', type: 'boolean', default: true, group: 'Floating Card OS' },

        { key: 'glow', label: 'Glow', type: 'range', default: 0.6, min: 0, max: 1.6, step: 0.05, group: 'Lighting' },
        { key: 'bloom', label: 'Bloom', type: 'range', default: 0.35, min: 0, max: 1.4, step: 0.05, group: 'Lighting' },
        { key: 'rimLight', label: 'Rim Light', type: 'range', default: 1, min: 0, max: 1.4, step: 0.05, group: 'Lighting' },
        { key: 'highlightIntensity', label: 'Highlight Intensity', type: 'range', default: 1, min: 0, max: 3, step: 0.1, group: 'Lighting' },
        { key: 'shadowIntensity', label: 'Shadow Intensity', type: 'range', default: 1, min: 0, max: 2.5, step: 0.1, group: 'Lighting' },
        { key: 'glassOpacity', label: 'Glass Opacity', type: 'range', default: 1, min: 0.2, max: 1.4, step: 0.05, group: 'Lighting' },
        { key: 'blurStrength', label: 'Blur Strength', type: 'range', default: 1, min: 0, max: 2.5, step: 0.05, group: 'Lighting' },

        { key: 'backgroundIntensity', label: 'Background Intensity', type: 'range', default: 1, min: 0, max: 1.6, step: 0.05, group: 'Background' },
        { key: 'gridOpacity', label: 'Grid Opacity', type: 'range', default: 1, min: 0, max: 2, step: 0.05, group: 'Background' },
        { key: 'ambientParticles', label: 'Ambient Particles', type: 'range', default: 0, min: 0, max: 60, step: 1, group: 'Background' },
        { key: 'vignette', label: 'Vignette', type: 'range', default: 0, min: 0, max: 1, step: 0.05, group: 'Background' },
        { key: 'atmosphericGlow', label: 'Atmospheric Glow', type: 'range', default: 0, min: 0, max: 1, step: 0.05, group: 'Background' },

        { key: 'visualMode', label: 'Visual Mode', type: 'select', default: 'shells', options: ['shells', 'signal-flow'], group: 'Stage Visuals' },
        { key: 'stageVisualIntensity', label: 'Stage Visual Intensity', type: 'range', default: 1, min: 0, max: 2, step: 0.05, group: 'Stage Visuals' },
        { key: 'stageMorphStrength', label: 'Stage Morph Strength', type: 'range', default: 1, min: 0, max: 2, step: 0.05, group: 'Stage Visuals' },
        { key: 'stageColorShift', label: 'Stage Color Shift', type: 'range', default: 1, min: 0, max: 1, step: 0.05, group: 'Stage Visuals' },
        { key: 'stageObjectSpread', label: 'Stage Object Spread', type: 'range', default: 1, min: 0.2, max: 2, step: 0.05, group: 'Stage Visuals' },
        { key: 'stageSymbolScale', label: 'Stage Symbol Scale', type: 'range', default: 1, min: 0.5, max: 2, step: 0.05, group: 'Stage Visuals' },

        { key: 'mobileRotationTurns', label: 'Mobile Rotation Turns', type: 'range', default: 0.25, min: 0, max: 2, step: 0.05, group: 'Mobile' },
        { key: 'mobileObjectScale', label: 'Mobile Object Scale', type: 'range', default: 1, min: 0.4, max: 1.6, step: 0.05, group: 'Mobile' },
        { key: 'mobileEffectsQuality', label: 'Mobile Effects Quality', type: 'select', default: 'medium', options: ['low', 'medium', 'high'], group: 'Mobile' },
        { key: 'disableRotationOnMobile', label: 'Disable Rotation On Mobile', type: 'boolean', default: false, group: 'Mobile' },

        { key: 'reducedMotionRotation', label: 'Reduced Motion Rotation', type: 'select', default: 'static', options: ['off', 'stage-only', 'static'], group: 'Reduced Motion' },

        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1, group: 'Legacy' },
        { key: 'rotatePerSection', label: 'Rotate/Section', type: 'range', default: 90, min: 20, max: 180, step: 10, group: 'Legacy' },
        { key: 'scalePulse', label: 'Scale Pulse', type: 'range', default: 0.18, min: 0, max: 0.4, step: 0.05, group: 'Legacy' },
        { key: 'colorShift', label: 'Color Shift', type: 'boolean', default: true, group: 'Legacy' },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./PinnedProductStageCoreSystem')),
  },
  {
    meta: {
      id: 'scroll-object-transform',
      name: 'ScrollObjectTransform',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['Shopify Theatre.js-Keyframe-Stationen', 'KRANK smoothstep-Mapping'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Scroll-Stories', 'Prozess-Erklärungen mit wanderndem Objekt'],
      performanceNotes: 'Ein Objekt-Transform pro Frame, smoothstep zwischen Stationen — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Objekt an letzter Station, statisch.',
      description: 'Ein Objekt wandert scroll-getrieben durch klare Keyframe-Stationen (Position, Rotation, Morph via border-radius) mit smoothstep-Interpolation — Timeline-Keyframes wie in Theatre.js, ohne Library.',
      importPath: '@/motion-arsenal/effects/scroll/ScrollObjectTransform',
      usageJsx: '<ScrollObjectTransform stations={4} spin={1} morph={0.8} />',
      props: [
        { key: 'stations', label: 'Stations', type: 'range', default: 4, min: 2, max: 6, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'spin', label: 'Spin', type: 'range', default: 1, min: 0, max: 3, step: 0.1 },
        { key: 'morph', label: 'Morph', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'showRail', label: 'Station Rail', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScrollObjectTransform')),
  },
  {
    meta: {
      id: 'scroll-parallax-symbol-layers',
      name: 'ParallaxSymbolLayers',
      category: 'scroll',
      sourceWebsite: 'oryzo-screenshot',
      sourceFiles: ['ORYZO Tiefenstaffelung (Scroll-Variante)', 'KRANK Layering (eine Physik-Quelle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Content-Seiten mit Tiefe', 'Über-uns/Story-Sektionen'],
      performanceNotes: '3-4 transform-Layer, damped — günstig. Blur nur auf tiefster Ebene.',
      mobileNotes: 'Touch-tauglich; travel ≤ 0.8 auf Mobile.',
      reducedMotionNotes: 'Layer statisch versetzt (Tiefe bleibt sichtbar).',
      description: 'Drei bis vier Tiefenebenen aus prozeduralen Glyphen/Symbolen scrollen mit unterschiedlichen Geschwindigkeiten und Blur-Staffelung — die ORYZO-Tiefe als Scroll-Choreografie.',
      importPath: '@/motion-arsenal/effects/scroll/ParallaxSymbolLayers',
      usageJsx: '<ParallaxSymbolLayers layers={4} travel={0.8} colorMode="nox" />',
      props: [
        { key: 'layers', label: 'Layers', type: 'range', default: 4, min: 3, max: 4, step: 1 },
        { key: 'travel', label: 'Travel', type: 'range', default: 0.8, min: 0.3, max: 1.2, step: 0.05 },
        { key: 'blurMax', label: 'Max Blur', type: 'range', default: 5, min: 0, max: 10, step: 0.5 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'colorMode', label: 'Colors', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ParallaxSymbolLayers')),
  },
  {
    meta: {
      id: 'scroll-timeline-progress-rail',
      name: 'TimelineProgressRail',
      category: 'scroll',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash Draw (Checkmarks)', 'Lenis-damped Progress (shopify_editions.md)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Prozess-/Roadmap-Sektionen', 'Onboarding-Strecken', 'NOX Forge Protokoll-Ansicht'],
      performanceNotes: 'Eine Progress-Linie + N Meilenstein-Nodes — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Rail komplett gefüllt, alle Nodes gezündet.',
      description: 'Vertikale Timeline: die Progress-Linie füllt mit gedämpftem Scroll, Meilenstein-Nodes zünden nacheinander mit Glow-Puls und Checkmark-Draw, der aktive Abschnitt hebt sich.',
      importPath: '@/motion-arsenal/effects/scroll/TimelineProgressRail',
      usageJsx: '<TimelineProgressRail milestones={5} glow={0.8} />',
      props: [
        { key: 'milestones', label: 'Milestones', type: 'range', default: 5, min: 3, max: 6, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'glow', label: 'Glow', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'showPercent', label: 'Percent', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TimelineProgressRail')),
  },
  {
    meta: {
      id: 'scroll-velocity-skew',
      name: 'ScrollVelocitySkew',
      category: 'scroll',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (SecondOrderDynamics: velocity accumulation → damping 8-15)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Editorial-/Fashion-Feel', 'Marquee-lastige Seiten', 'Portfolio'],
      performanceNotes: 'Velocity-Ableitung + transform/blur auf einem Container + Marquee-Offsets — günstig; blur nur bei aktiver Bewegung.',
      mobileNotes: 'Touch-Scroll erzeugt dieselbe Velocity — funktioniert.',
      reducedMotionNotes: 'Keine Skew/Marquee-Reaktion, statischer Content.',
      description: 'Der Inhalt reagiert auf Scroll-GESCHWINDIGKEIT statt Position: skewY, Letter-Spacing und Blur wachsen mit der Velocity und federn gedämpft zurück; Marquee-Zeilen beschleunigen mit.',
      importPath: '@/motion-arsenal/effects/scroll/ScrollVelocitySkew',
      usageJsx: '<ScrollVelocitySkew skewMax={10} damping={9} />',
      props: [
        { key: 'skewMax', label: 'Skew Max °', type: 'range', default: 10, min: 2, max: 20, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 9, min: 3, max: 16, step: 1 },
        { key: 'marqueeBase', label: 'Marquee px/s', type: 'range', default: 40, min: 0, max: 120, step: 5 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScrollVelocitySkew')),
  },
  {
    meta: {
      id: 'scroll-section-snap-depth',
      name: 'SectionSnapDepth',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['RiveInner (IntersectionObserver Lazy-Aktivierung)', 'Nav-Cascade-Timing'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Fullscreen-Story-Seiten', 'Pitch-/Launch-Pages', 'NOX Forge Phasen-Erklärung'],
      performanceNotes: 'CSS scroll-snap + IntersectionObserver — kein rAF-Loop.',
      mobileNotes: 'scroll-snap ist mobiles Kern-Pattern — sehr gut.',
      reducedMotionNotes: 'Kein Snap-Zwang, alle Sektionen im Endzustand.',
      description: 'Sektionen snappen (CSS scroll-snap); die aktive baut sich mit Tiefen-Stagger auf (scale 0.94→1 + Layer-Cascade), inaktive dimmen und blurren weg — Fokus-Tiefe wie eine Kamera.',
      importPath: '@/motion-arsenal/effects/scroll/SectionSnapDepth',
      usageJsx: '<SectionSnapDepth sectionCount={4} dimStrength={0.7} />',
      props: [
        { key: 'sectionCount', label: 'Sections', type: 'range', default: 4, min: 2, max: 5, step: 1 },
        { key: 'dimStrength', label: 'Dim', type: 'range', default: 0.7, min: 0.2, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SectionSnapDepth')),
  },
];
