import { useState, type CSSProperties } from 'react';
export interface DistortedButtonImageRevealProps { label?: string; src?: string; distortion?: number; color?: string; }
export default function DistortedButtonImageReveal({ label = 'VIEW PROJECT', src = '', distortion = .7, color = '#d4a24a' }: DistortedButtonImageRevealProps) {
  const [hover, setHover] = useState(false); const css = { '--distort': distortion, '--button-color': color, '--button-image': `url(${src})` } as CSSProperties;
  return <button className={`nox-distort-button ${hover ? 'is-hover' : ''}`} style={css} onPointerEnter={() => setHover(true)} onPointerLeave={() => setHover(false)} onFocus={() => setHover(true)} onBlur={() => setHover(false)}>
    <span>{label}</span><b aria-hidden="true">{label}</b><i aria-hidden="true" />
    <style>{`.nox-distort-button{position:relative;isolation:isolate;overflow:hidden;min-width:220px;padding:18px 25px;border:1px solid var(--button-color);background:#0c0a08;color:var(--button-color);font:700 .78rem ui-monospace;letter-spacing:.16em;cursor:pointer}.nox-distort-button:before{content:"";position:absolute;inset:0;z-index:-1;background:var(--button-image) center/cover;filter:saturate(.5) contrast(1.4);opacity:0;transform:scale(1.2)}.nox-distort-button b{position:absolute;inset:0;padding:18px 25px;color:#f7e8a4;opacity:0;transform:translate(calc(var(--distort)*8px),-2px);mix-blend-mode:screen}.nox-distort-button i{position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 12px,var(--button-color) 13px 14px);opacity:0;transform:translateX(-100%)}.nox-distort-button.is-hover:before{opacity:.55;transform:scale(1);transition:opacity .35s,transform .7s}.nox-distort-button.is-hover b{opacity:.8;animation:distort-glitch .4s steps(2)}.nox-distort-button.is-hover i{opacity:.45;animation:distort-sweep .65s steps(5)}.nox-distort-button:focus-visible{outline:2px solid var(--button-color);outline-offset:4px}@keyframes distort-glitch{50%{transform:translate(-5px,2px);clip-path:inset(30% 0 30% 0)}}@keyframes distort-sweep{to{transform:translateX(100%)}}@media(prefers-reduced-motion:reduce){.nox-distort-button.is-hover b{animation:none}.nox-distort-button.is-hover i{animation:none;transform:none}}`}</style>
  </button>;
}
