import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const TRANSITIONS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'transitions-smooth-section-wipe',
      name: 'SmoothSectionWipe',
      category: 'transitions',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (JS-getriebene Page-Transitions, lerp-Choreografie)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Routenwechsel', 'Sektions-Übergänge auf One-Pagern'],
      performanceNotes: 'Nur transform auf 2-3 Panels — GPU-composited, sehr günstig.',
      mobileNotes: 'Voll mobiletauglich.',
      reducedMotionNotes: 'Kein Wipe, Ziel-Sektion direkt sichtbar.',
      description: 'Mehrlagiger Wipe: 2-3 versetzte Panels (dunkel → Akzent → neue Seite) wischen mit gestaffeltem outExpo durch die Bühne; Richtung wählbar.',
      importPath: '@/motion-arsenal/effects/transitions/SmoothSectionWipe',
      usageJsx: "<SmoothSectionWipe direction=\"left\" panelCount={3} />",
      props: [
        { key: 'direction', label: 'Direction', type: 'select', default: 'left', options: ['left', 'right', 'up', 'down'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'panelCount', label: 'Panels', type: 'range', default: 3, min: 2, max: 3, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SmoothSectionWipe')),
  },
  {
    meta: {
      id: 'transitions-masked-route',
      name: 'MaskedRouteTransition',
      category: 'transitions',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (view-transition-name: navigation)', 'shopify.css (mask-Techniken, 46 Refs)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Routenwechsel mit Marken-Moment', 'App-artige Übergänge'],
      performanceNotes: 'clip-path-Animation, GPU-composited.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Direkter Seitenwechsel ohne Maske.',
      description: 'Übergang durch wachsende/schrumpfende Masken-Form (Kreis/Diamant) von wählbarem Ursprung — die View-Transition-Ästhetik von Shopify Editions, nachgebaut mit clip-path + Scale-Choreografie.',
      importPath: '@/motion-arsenal/effects/transitions/MaskedRouteTransition',
      usageJsx: "<MaskedRouteTransition shape=\"circle\" origin=\"center\" />",
      props: [
        { key: 'shape', label: 'Shape', type: 'select', default: 'circle', options: ['circle', 'diamond'] },
        { key: 'origin', label: 'Origin', type: 'select', default: 'center', options: ['center', 'top-left', 'bottom-right'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./MaskedRouteTransition')),
  },
  {
    meta: {
      id: 'transitions-clip-path-reveal',
      name: 'ClipPathReveal',
      category: 'transitions',
      sourceWebsite: 'nox-original',
      sourceFiles: ['shopify.css (mask/clip-Reveals)', 'NOX forge-cut Ästhetik'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Sektionen', 'Tech-/System-Markenauftritte'],
      performanceNotes: 'clip-path polygon Animation + eine Glow-Linie — günstig.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Sektion direkt sichtbar.',
      description: 'Neue Sektion wird über einen animierten diagonalen Notch-Schnitt (clip-path polygon) aufgedeckt; eine Kanten-Glow-Linie folgt der Schnittkante.',
      importPath: '@/motion-arsenal/effects/transitions/ClipPathReveal',
      usageJsx: "<ClipPathReveal direction=\"left\" notch={12} />",
      props: [
        { key: 'direction', label: 'Direction', type: 'select', default: 'left', options: ['left', 'right'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'notch', label: 'Notch %', type: 'range', default: 12, min: 4, max: 22, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ClipPathReveal')),
  },
  {
    meta: {
      id: 'transitions-layered-page-enter',
      name: 'LayeredPageEnter',
      category: 'transitions',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (Nav-Entrance-Cascade: animation-delay 500ms + 100ms-Steps, motion-safe)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Seiten-Einstiege', 'Hero-Aufbau nach Route-Wechsel'],
      performanceNotes: 'Gestaffelte transform/opacity-Layer + Pointer-Parallax-Loop.',
      mobileNotes: 'Parallax entfällt ohne Pointer; Cascade bleibt.',
      reducedMotionNotes: 'Alle Layer sofort im Endzustand.',
      description: 'Neue Seite kommt als Layer-Stack: Hintergrund → Panel → Typo → UI-Details staggern mit Shopify-Cascade-Timing herein, jeder Layer behält Parallax-Tiefe am Pointer.',
      importPath: '@/motion-arsenal/effects/transitions/LayeredPageEnter',
      usageJsx: '<LayeredPageEnter stepMs={100} parallax={0.5} />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'stepMs', label: 'Step ms', type: 'range', default: 100, min: 60, max: 160, step: 10 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./LayeredPageEnter')),
  },
  {
    meta: {
      id: 'transitions-panel-shift',
      name: 'PanelShiftTransition',
      category: 'transitions',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Easing cubic-bezier(.3,0,.66,-.3) auf Transform-Slides)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Split-Flap-/Editorial-Übergänge', 'Portfolio-Wechsel'],
      performanceNotes: '3-4 Streifen-Transforms, GPU-composited.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Direkter Wechsel ohne Streifen.',
      description: 'Alte Seite bricht in 3-4 Streifen, die versetzt hinausschieben, während die neue hereinschiebt — das Settle nutzt die KRANK-Overshoot-Kurve für den mechanischen Split-Flap-Moment.',
      importPath: '@/motion-arsenal/effects/transitions/PanelShiftTransition',
      usageJsx: "<PanelShiftTransition axis=\"horizontal\" strips={4} />",
      props: [
        { key: 'axis', label: 'Axis', type: 'select', default: 'horizontal', options: ['horizontal', 'vertical'] },
        { key: 'strips', label: 'Strips', type: 'range', default: 4, min: 3, max: 4, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./PanelShiftTransition')),
  },
  { meta: { id: 'transitions-cube-spin-route-transition', name: 'CubeSpinRouteTransition', displayName: 'Cube Spin Route Transition', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX route cube transition'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Route Changes', 'Product Steps'], performanceNotes: 'CSS 3D transform only.', mobileNotes: 'Tap and keyboard buttons supported.', reducedMotionNotes: 'Label changes without rotation.', description: 'A tactile route selector that flips its surface like a 3D cube.', importPath: '@/motion-arsenal/effects/transitions/CubeSpinRouteTransition', usageJsx: '<CubeSpinRouteTransition />', props: [{ key: 'labels', label: 'Labels', type: 'text', default: 'ORIGIN,SIGNAL,MOTION' }, { key: 'duration', label: 'Duration', type: 'range', default: .8, min: .2, max: 1.5, step: .1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./CubeSpinRouteTransition')) },
  { meta: { id: 'transitions-frame-repeat-image-transition', name: 'FrameRepeatImageTransition', displayName: 'Frame Repeat Image Transition', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX repeated-frame image transition'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Gallery Changes', 'Image Reveals'], performanceNotes: 'Fixed clipped transform layers.', mobileNotes: 'Tap replays the transition.', reducedMotionNotes: 'Image remains crisp.', description: 'Repeated image frames peel across a surface before settling into one sharp image.', importPath: '@/motion-arsenal/effects/transitions/FrameRepeatImageTransition', usageJsx: '<FrameRepeatImageTransition src="/image.jpg" />', props: [{ key: 'src', label: 'Image', type: 'text', default: '' }, { key: 'alt', label: 'Alt', type: 'text', default: 'Frame transition' }, { key: 'repeats', label: 'Repeats', type: 'range', default: 5, min: 3, max: 9, step: 1 }, { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' }], productionSafe: true }, Component: lazy(() => import('./FrameRepeatImageTransition')) },
  { meta: { id: 'transitions-bayer-dither-dissolve', name: 'BayerDitherDissolve', displayName: 'Bayer Dither Dissolve', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal_Neue-Effekte_2026-08-01-02.zip / Effekte/Bayer Dither Dissolve.md'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Abschnittswechsel', 'Portfolio-Umschläge', 'System-/Debug-Ästhetik'], performanceNotes: 'Canvas ImageData nur auf reduzierter Auflösung (Zellgröße 4–16 px), hochskaliert per image-rendering: pixelated. Neuzeichnen nur bei Progress-Änderung, kein rAF-Loop.', mobileNotes: 'Touch-tauglich; der Toggle-Button bleibt groß genug für Finger.', reducedMotionNotes: 'Die Panels wechseln ohne Dither — der Inhalt bleibt vollständig lesbar.', description: 'Bayer-geditherter Abschnittswechsel mit Gold-Kante: Eine 4×4-Bayer-Matrix auf reduzierter Canvas-Auflösung löst die Vorderfläche zellenweise in die Rückfläche auf. Deterministisch, kein Math.random.', importPath: '@/motion-arsenal/effects/transitions/BayerDitherDissolve', usageJsx: '<BayerDitherDissolve frontLabel="NOX" backLabel="ARSENAL" duration={1600} />', props: [{ key: 'frontLabel', label: 'Vorderfläche', type: 'text', default: 'NOX' }, { key: 'backLabel', label: 'Rückfläche', type: 'text', default: 'ARSENAL' }, { key: 'duration', label: 'Dauer ms', type: 'range', default: 1600, min: 600, max: 3000, step: 100 }, { key: 'cellSize', label: 'Zellgröße', type: 'range', default: 8, min: 4, max: 16, step: 1 }, { key: 'goldEdge', label: 'Gold-Kante', type: 'boolean', default: true }, { key: 'autoPlay', label: 'Auto-Play', type: 'boolean', default: true }, { key: 'seed', label: 'Seed', type: 'range', default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true, fullBleed: true }, Component: lazy(() => import('./BayerDitherDissolve')) },
  { meta: { id: 'transitions-iron-filings-magnet-transition', name: 'IronFilingsMagnetTransition', displayName: 'Iron Filings Magnet Transition', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['Vault: nox-iron-filings-magnet-transition'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Kinetic Reveals'], performanceNotes: 'Seeded DOM filings.', mobileNotes: 'Tap activates field.', reducedMotionNotes: 'Filings snap into place.', description: 'Deterministic iron filings align around a magnetic field.', importPath: '@/motion-arsenal/effects/transitions/IronFilingsMagnetTransition', usageJsx: '<IronFilingsMagnetTransition />', props: [], productionSafe: true }, Component: lazy(() => import('./IronFilingsMagnetTransition')) },
  { meta: { id: 'transitions-vertical-slit-slideshow', name: 'VerticalSlitSlideshow', displayName: 'Vertical Slit Slideshow', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Galerien', 'Hero Rotators'], performanceNotes: '3D-Transform + Stagger, kein Layout-Write.', mobileNotes: 'Touch: Prev/Next-Buttons.', reducedMotionNotes: 'Direkter Bildwechsel ohne Slits.', description: 'Slideshow mit vertikalen Gold-Slits: Bild zerfaellt in Streifen, die gestaffelt kippen und das naechste freigeben.', importPath: '@/motion-arsenal/effects/transitions/VerticalSlitSlideshow', usageJsx: '<VerticalSlitSlideshow />', props: [{ key: "slits", label: "Streifen", type: "range", default: 8, min: 4, max: 16, step: 1 }, { key: "interval", label: "Autoplay", type: "range", default: 4, min: 2, max: 10, step: 1 }], productionSafe: true }, Component: lazy(() => import('./VerticalSlitSlideshow')) },
  { meta: { id: 'transitions-view-transition-list-filter', name: 'ViewTransitionListFilter', displayName: 'View Transition List Filter', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Dashboards', 'Filter Listen'], performanceNotes: 'Natives Browser-FLIP; kein rAF.', mobileNotes: 'Touch: Chips sind Buttons.', reducedMotionNotes: 'Direkter Update ohne Morph.', description: 'Filter-Chips sortieren eine Liste; jedes Item hat eigene view-transition-name, DOM-Update in startViewTransition (natives FLIP).', importPath: '@/motion-arsenal/effects/transitions/ViewTransitionListFilter', usageJsx: '<ViewTransitionListFilter />', props: [{ key: "seed", label: "Seed", type: "range", default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./ViewTransitionListFilter')) },
  { meta: { id: 'transitions-view-transition-crossfade', name: 'ViewTransitionCrossFade', displayName: 'View Transition Cross-Fade', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['State Switchers', 'Dashboards'], performanceNotes: 'Natives Browser-Transition-API, kein rAF.', mobileNotes: 'Touch: Pfeil-Buttons.', reducedMotionNotes: 'Direkter Wechsel ohne Fade.', description: 'Dunkelraum-optimierter nativer Crossfade fuer DOM-Zustaende via document.startViewTransition mit Feature-Detect + Fallback.', importPath: '@/motion-arsenal/effects/transitions/ViewTransitionCrossFade', usageJsx: '<ViewTransitionCrossFade />', props: [{ key: "states", label: "Zustaende", type: "text", default: "IDLE,SIGNAL,LOCK,DRIFT,PULSE" }, { key: "seed", label: "Seed", type: "range", default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./ViewTransitionCrossFade')) },
  { meta: { id: 'transitions-webgl-water-slider', name: 'WebGLWaterSlider', displayName: 'WebGL Water Distortion Slider', category: 'transitions', sourceWebsite: 'nox-original', sourceFiles: ['NOX-Arsenal Konzept'], mode: 'nox-adapted', complexity: 'medium', dependencies: [], bestFor: ['Premium Galleries', 'Before/After'], performanceNotes: 'ImageData nur auf 160px-Raster, hochskaliert; rAF nur waehrend Drag.', mobileNotes: 'Touch: Ziehen auf der Flaeche.', reducedMotionNotes: 'CSS-Blur-Slide (dokumentierter Fallback).', description: 'Bild-Slider mit Wasser-Verzerrung: echtes ImageData-Wellen-Displacement (fbm-artige Sinus-Ueberlagerung, Drag skaliert Amplitude).', importPath: '@/motion-arsenal/effects/transitions/WebGLWaterSlider', usageJsx: '<WebGLWaterSlider />', props: [{ key: "seed", label: "Seed", type: "range", default: 20260810, min: 1, max: 99999999, step: 1 }], productionSafe: true }, Component: lazy(() => import('./WebGLWaterSlider')) },
];
