import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const TRANSITIONS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'transitions-route-system', name: 'RouteTransitionSystem', displayName: 'Route Transition System', category: 'transitions', sourceWebsite: 'nox-consolidated',
      sourceFiles: ['RouteTransitionSystem.tsx (canonical selector)', 'SmoothSectionWipe.tsx', 'MaskedRouteTransition.tsx', 'ClipPathReveal.tsx', 'PanelShiftTransition.tsx'], mode: 'nox-adapted', complexity: 'medium', dependencies: [],
      bestFor: ['Route changes', 'Section handoffs', 'App-like navigation moments'], performanceNotes: 'Renders one preserved transition implementation at a time; transforms and clip-path costs remain mode-specific.', mobileNotes: 'All selected modes retain their existing mobile behavior.', reducedMotionNotes: 'Delegates to the selected effect\'s existing reduced-motion state.',
      description: 'Canonical selector for wipe, masked, clip, and panel route transitions. LayeredPageEnter remains a standalone entrance composer.', technicalBasis: 'React composition over preserved standalone route-transition effects.', importPath: '@/motion-arsenal/effects/transitions/RouteTransitionSystem', usageJsx: '<RouteTransitionSystem mode="masked" speed={1} />',
      props: [{ key: 'mode', label: 'Transition Mode', type: 'select', default: 'wipe', options: ['wipe', 'masked', 'clip', 'panel'] }, { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' }, { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 }],
      supersedes: ['SmoothSectionWipe', 'MaskedRouteTransition', 'ClipPathReveal', 'PanelShiftTransition'], legacyIds: ['transitions-smooth-section-wipe', 'transitions-masked-route', 'transitions-clip-path-reveal', 'transitions-panel-shift'], deprecationNotes: 'Direct standalone component imports remain supported.', productionSafe: true, status: 'production-safe',
    }, Component: lazy(() => import('./RouteTransitionSystem')),
  },
  {
    meta: {
      id: 'transitions-smooth-section-wipe',
      name: 'SmoothSectionWipe',
      category: 'transitions',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (JS-getriebene Page-Transitions, lerp-Choreografie)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Routenwechsel', 'Sektions-Übergänge auf One-Pagern'],
      performanceNotes: 'Nur transform auf 2-3 Panels — GPU-composited, sehr günstig.',
      mobileNotes: 'Voll mobiletauglich.',
      reducedMotionNotes: 'Kein Wipe, Ziel-Sektion direkt sichtbar.',
      description: 'Mehrlagiger Wipe: 2-3 versetzte Panels (dunkel → Akzent → neue Seite) wischen mit gestaffeltem outExpo durch die Bühne; Richtung wählbar.',
      importPath: '@/motion-arsenal/effects/transitions/SmoothSectionWipe',
      usageJsx: "<SmoothSectionWipe direction=\"left\" panelCount={3} />",
      props: [
        { key: 'direction', label: 'Direction', type: 'select', default: 'left', options: ['left', 'right', 'up', 'down'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'panelCount', label: 'Panels', type: 'range', default: 3, min: 2, max: 3, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SmoothSectionWipe')),
  },
  {
    meta: {
      id: 'transitions-masked-route',
      name: 'MaskedRouteTransition',
      category: 'transitions',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (view-transition-name: navigation)', 'shopify.css (mask-Techniken, 46 Refs)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Routenwechsel mit Marken-Moment', 'App-artige Übergänge'],
      performanceNotes: 'clip-path-Animation, GPU-composited.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Direkter Seitenwechsel ohne Maske.',
      description: 'Übergang durch wachsende/schrumpfende Masken-Form (Kreis/Diamant) von wählbarem Ursprung — die View-Transition-Ästhetik von Shopify Editions, nachgebaut mit clip-path + Scale-Choreografie.',
      importPath: '@/motion-arsenal/effects/transitions/MaskedRouteTransition',
      usageJsx: "<MaskedRouteTransition shape=\"circle\" origin=\"center\" />",
      props: [
        { key: 'shape', label: 'Shape', type: 'select', default: 'circle', options: ['circle', 'diamond'] },
        { key: 'origin', label: 'Origin', type: 'select', default: 'center', options: ['center', 'top-left', 'bottom-right'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./MaskedRouteTransition')),
  },
  {
    meta: {
      id: 'transitions-clip-path-reveal',
      name: 'ClipPathReveal',
      category: 'transitions',
      sourceWebsite: 'nox-original',
      sourceFiles: ['shopify.css (mask/clip-Reveals)', 'NOX forge-cut Ästhetik'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Sektionen', 'Tech-/System-Markenauftritte'],
      performanceNotes: 'clip-path polygon Animation + eine Glow-Linie — günstig.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Sektion direkt sichtbar.',
      description: 'Neue Sektion wird über einen animierten diagonalen Notch-Schnitt (clip-path polygon) aufgedeckt; eine Kanten-Glow-Linie folgt der Schnittkante.',
      importPath: '@/motion-arsenal/effects/transitions/ClipPathReveal',
      usageJsx: "<ClipPathReveal direction=\"left\" notch={12} />",
      props: [
        { key: 'direction', label: 'Direction', type: 'select', default: 'left', options: ['left', 'right'] },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'notch', label: 'Notch %', type: 'range', default: 12, min: 4, max: 22, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ClipPathReveal')),
  },
  {
    meta: {
      id: 'transitions-layered-page-enter',
      name: 'LayeredPageEnter',
      category: 'transitions',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (Nav-Entrance-Cascade: animation-delay 500ms + 100ms-Steps, motion-safe)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Seiten-Einstiege', 'Hero-Aufbau nach Route-Wechsel'],
      performanceNotes: 'Gestaffelte transform/opacity-Layer + Pointer-Parallax-Loop.',
      mobileNotes: 'Parallax entfällt ohne Pointer; Cascade bleibt.',
      reducedMotionNotes: 'Alle Layer sofort im Endzustand.',
      description: 'Neue Seite kommt als Layer-Stack: Hintergrund → Panel → Typo → UI-Details staggern mit Shopify-Cascade-Timing herein, jeder Layer behält Parallax-Tiefe am Pointer.',
      importPath: '@/motion-arsenal/effects/transitions/LayeredPageEnter',
      usageJsx: '<LayeredPageEnter stepMs={100} parallax={0.5} />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'stepMs', label: 'Step ms', type: 'range', default: 100, min: 60, max: 160, step: 10 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./LayeredPageEnter')),
  },
  {
    meta: {
      id: 'transitions-panel-shift',
      name: 'PanelShiftTransition',
      category: 'transitions',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/index.css (Overshoot-Easing cubic-bezier(.3,0,.66,-.3) auf Transform-Slides)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Split-Flap-/Editorial-Übergänge', 'Portfolio-Wechsel'],
      performanceNotes: '3-4 Streifen-Transforms, GPU-composited.',
      mobileNotes: 'Mobiletauglich.',
      reducedMotionNotes: 'Direkter Wechsel ohne Streifen.',
      description: 'Alte Seite bricht in 3-4 Streifen, die versetzt hinausschieben, während die neue hereinschiebt — das Settle nutzt die KRANK-Overshoot-Kurve für den mechanischen Split-Flap-Moment.',
      importPath: '@/motion-arsenal/effects/transitions/PanelShiftTransition',
      usageJsx: "<PanelShiftTransition axis=\"horizontal\" strips={4} />",
      props: [
        { key: 'axis', label: 'Axis', type: 'select', default: 'horizontal', options: ['horizontal', 'vertical'] },
        { key: 'strips', label: 'Strips', type: 'range', default: 4, min: 3, max: 4, step: 1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.5, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./PanelShiftTransition')),
  },
];
