import { useState, type CSSProperties } from 'react';
export interface FrameRepeatImageTransitionProps { src?: string; alt?: string; repeats?: number; color?: string; }
export default function FrameRepeatImageTransition({ src = '', alt = 'Frame transition', repeats = 5, color = '#d4a24a' }: FrameRepeatImageTransitionProps) {
  const [run, setRun] = useState(false); const count = Math.max(3, Math.min(9, repeats));
  return <button className={`nox-frame-repeat ${run ? 'is-running' : ''}`} onClick={() => setRun(v => !v)} style={{ '--frame-image': `url(${src})`, '--frame-color': color } as CSSProperties} aria-label="Replay image transition">
    <span className="nox-frame-repeat__image" style={{ backgroundImage: `url(${src})` }} />{Array.from({ length: count }, (_, i) => <span key={i} className="nox-frame-repeat__frame" style={{ '--i': i } as CSSProperties} aria-hidden="true" />)}
    <style>{`.nox-frame-repeat{position:relative;display:block;width:min(100%,430px);aspect-ratio:16/10;overflow:hidden;border:1px solid var(--frame-color);background:#100d09;cursor:pointer}.nox-frame-repeat__image,.nox-frame-repeat__frame{position:absolute;inset:0;background-position:center;background-size:cover}.nox-frame-repeat__image{filter:saturate(.7);transition:transform .6s,filter .6s}.nox-frame-repeat__frame{opacity:0;border:1px solid color-mix(in srgb,var(--frame-color),transparent 25%);background-image:var(--frame-image);mix-blend-mode:screen;transform:translateX(calc(var(--i)*-8px)) scale(calc(1 + var(--i)*.015));clip-path:inset(calc(var(--i)*8%) 0 calc((8 - var(--i))*8%) 0)}.nox-frame-repeat.is-running .nox-frame-repeat__image{transform:scale(1.08);filter:blur(3px) saturate(.5)}.nox-frame-repeat.is-running .nox-frame-repeat__frame{animation:frame-repeat .8s cubic-bezier(.2,1,.3,1) calc(var(--i)*.07s) both}.nox-frame-repeat:focus-visible{outline:2px solid var(--frame-color);outline-offset:4px}@keyframes frame-repeat{0%{opacity:0;transform:translateX(calc(var(--i)*-22px)) scale(1.12)}35%{opacity:.8}100%{opacity:0;transform:translateX(0) scale(1)}}@media(prefers-reduced-motion:reduce){.nox-frame-repeat.is-running .nox-frame-repeat__image{filter:none;transform:none}.nox-frame-repeat.is-running .nox-frame-repeat__frame{animation:none;opacity:0}}`}</style>
  </button>;
}
