import { useMemo, useState, type CSSProperties } from 'react';
import { seededRandom } from '../../lib/animationUtils';
export interface IronFilingsMagnetTransitionProps { particles?: number; label?: string; color?: string; }
export default function IronFilingsMagnetTransition({ particles = 42, label = 'MAGNETIC TRANSFER', color = '#d4a24a' }: IronFilingsMagnetTransitionProps) {
  const [active, setActive] = useState(false); const count = Math.max(18, Math.min(100, particles));
  const filings = useMemo(() => { const r = seededRandom(813); return Array.from({ length: count }, (_, i) => ({ i, x: 8 + r() * 84, y: 12 + r() * 76, dx: (r() - .5) * 90, dy: (r() - .5) * 90, rot: r() * 180 })); }, [count]);
  return <button className={`nox-filings ${active ? 'is-attracted' : ''}`} onClick={() => setActive(v => !v)} aria-pressed={active} style={{ '--filing-gold': color } as CSSProperties}><span className="nox-filings__field">{filings.map(p => <i key={p.i} style={{ '--x': `${p.x}%`, '--y': `${p.y}%`, '--dx': `${p.dx}px`, '--dy': `${p.dy}px`, '--rot': `${p.rot}deg`, '--delay': `${p.i * 18}ms` } as CSSProperties}/>)}</span><strong>{label}</strong><small>{active ? 'FIELD LOCKED · CLICK TO RELEASE' : 'CLICK TO ACTIVATE FIELD'}</small><style>{CSS}</style></button>;
}
const CSS = `.nox-filings{position:relative;display:grid;place-items:center;gap:12px;width:100%;min-height:280px;border:1px solid #d4a24a44;background:radial-gradient(circle at 50% 50%,#d4a24a20,transparent 45%),#090a0d;color:#f7e8a4;overflow:hidden;cursor:pointer}.nox-filings__field{position:absolute;inset:0}.nox-filings i{position:absolute;left:var(--x);top:var(--y);width:20px;height:2px;border-radius:50%;background:linear-gradient(90deg,transparent,#d4a24a,#f7e8a4);box-shadow:0 0 7px #d4a24a;transform:translate(-50%,-50%) rotate(var(--rot));transition:transform .9s cubic-bezier(.2,1.4,.25,1) var(--delay),opacity .5s;opacity:.5}.nox-filings.is-attracted i{transform:translate(calc(-50% + var(--dx)),calc(-50% + var(--dy))) rotate(calc(var(--rot) + 90deg)) scaleX(1.8);opacity:1}.nox-filings strong,.nox-filings small{z-index:1;letter-spacing:.18em}.nox-filings strong{font-size:clamp(1rem,3vw,1.8rem)}.nox-filings small{font:10px ui-monospace;opacity:.65}.nox-filings:focus-visible{outline:2px solid var(--filing-gold);outline-offset:5px}@media(prefers-reduced-motion:reduce){.nox-filings i{transition:none}.nox-filings.is-attracted i{transform:translate(-50%,-50%) rotate(90deg)}}`;
